export type Faction = 'warrior' | 'mage' | 'paladin' | 'rogue' | string;
export type Rarity = 'common' | 'uncommon' | 'rare' | 'epic' | 'legendary' | 'mythic' | 'founder' | string;
export interface CardRecord { id:string; code?:string|null; name?:string|null; faction?:Faction|null; rarity?:Rarity|null; specialization?:string|null; power?:number|null; affinity?:number|null; prestige?:number|null; charge?:number|null; lore?:string|null; prompt?:string|null; image_url?:string|null; region_id?:string|null; card_tier?:string|null; card_tags?:unknown[]|null; synergy_json?:Record<string,unknown>|null; evolution_json?:Record<string,unknown>|null; card_domain?:string|null; marketable?:boolean|null; fusion_enabled?:boolean|null; active?:boolean|null; supply?:number|null; minted?:number|null; is_founder?:boolean|null; is_legendary?:boolean|null; market_fee_override?:number|null; market_lock?:boolean|null; }
export interface PlayerCardRecord { id?:string; card_id:string; quantity?:number|null; locked?:boolean|null; listed?:boolean|null; source_tracking?:Record<string,unknown>|null; card?:CardRecord|null; }
export interface DeckSlot { id?:string; slot_number:number; is_champion?:boolean|null; card_id?:string|null; code?:string|null; name?:string|null; rarity?:Rarity|null; faction?:Faction|null; power?:number|null; image_url?:string|null; }
export interface DeckValidation { valid:boolean; errors?:string[]|null; card_count?:number|null; mythic_count?:number|null; legendary_count?:number|null; [key:string]:unknown; }
export interface WalletRecord { vex_ingame?:number|null; vex_tradeable?:number|null; reserved_ingame?:number|null; reserved_tradeable?:number|null; }
export interface PlayerProgressRecord { level?:number|null; xp?:number|null; xp_to_next?:number|null; energy?:number|null; max_energy?:number|null; tutorial_step?:number|null; starter_region?:string|null; updated_at?:string|null; }
export interface ProfileRecord { id?:string; display_name?:string|null; email?:string|null; level?:number|null; xp?:number|null; faction?:string|null; role?:string|null; status?:string|null; is_admin?:boolean|null; is_super_admin?:boolean|null; avatar_url?:string|null; [key:string]:unknown; }
export interface MissionRecord { id:string; code?:string|null; name?:string|null; region_id?:string|null; mission_type?:string|null; energy_cost?:number|null; reward_xp?:number|null; reward_vex_ingame?:number|null; reward_vex_tradeable?:number|null; cooldown_seconds?:number|null; rules_json?:Record<string,unknown>|null; active?:boolean|null; difficulty?:string|null; mission_group?:string|null; requirements_json?:Record<string,unknown>|null; rewards_json?:Record<string,unknown>|null; system_locked?:boolean|null; health_status?:string|null; production_ready?:boolean|null; mission_order?:number|null; }
export interface BattleEvent { event_type:string; actor_id?:string|null; target_id?:string|null; amount?:number|null; round?:number|null; payload?:unknown; }
export interface BattleUnitState { id:string; hp?:number|null; max_hp?:number|null; status?:string|null; slot?:string|null; card_id?:string|null; image_url?:string|null; side?:string|null; [key:string]:unknown; }
export interface BattleTurn { turn:number; actor?:string|null; action?:string|null; target?:string|null; amount?:number|null; [key:string]:unknown; }
export interface FormationSnapshot { champion_id?:string|null; vanguard_id?:string|null; sentinel_id?:string|null; reserve_ids?:string[]; }
export interface BattleResult { ok:boolean; status?:string|null; match_id?:string|null; winner_id?:string|null; you_won?:boolean|null; total_turns?:number|null; events?:BattleEvent[]|null; engine?:string|null; turns?:BattleTurn[]|null; final_units?:BattleUnitState[]|null; rewards?:Record<string,unknown>|null; error?:string|null; [key:string]:unknown; }
export interface PvpOpponent { id:string; player_id?:string|null; display_name?:string|null; mmr?:number|null; wins?:number|null; losses?:number|null; draws?:number|null; deck_size?:number|null; has_deck?:boolean|null; power?:number|null; faction?:string|null; avatar_url?:string|null; }
export interface MarketListing { id:string; reference_id?:string|null; player_id?:string|null; player_card_id?:string|null; card_id?:string|null; price?:number|null; fee?:number|null; status?:string|null; expires_at?:string|null; locked?:boolean|null; card_name?:string|null; card_rarity?:string|null; image_url?:string|null; }
export interface TreasuryWallet { chain:string; token_symbol:string; wallet_address:string; token_standard?:string|null; }
export interface DepositRecord { id:string; amount_usdt:number; vex_credited:number; chain:string; token_symbol:string; tx_hash:string; status:string; created_at:string; }
export interface WithdrawalRequest { id:string; player_id:string; tradeable_amount:number; usdt_gross:number; fee_usdt:number; usdt_net:number; status:string; rejected_reason?:string|null; payout_tx_hash?:string|null; created_at:string; processed_at?:string|null; }
export interface Pack { pack_key:string; pack_name:string; price_vex:number; price_usdt:number; card_count:number; notes?:string|null; rarity_weights?:Record<string,number>|null; }
export interface OpenedCard { id:string; name?:string|null; rarity?:string|null; image_url?:string|null; card_id?:string|null; code?:string|null; }
export interface ShopItem { id:string; item_key:string; name:string; description?:string|null; category?:string|null; price_usdt?:number|null; price_vex?:number|null; active?:boolean|null; icon?:string|null; }
export interface ShopOrder { id:string; item_key?:string|null; status?:string|null; amount_usdt?:number|null; amount_vex?:number|null; [key:string]:unknown; }
export interface RaidRun { id:string; raid_code?:string|null; region_id?:string|null; status?:string|null; started_at?:string|null; ended_at?:string|null; metadata?:Record<string,unknown>|null; created_at?:string|null; }
export interface WorldBoss { id:string; boss_code?:string|null; name?:string|null; region_id?:string|null; tier?:number|null; power_level?:number|null; hp?:number|null; reward_pool?:Record<string,unknown>|null; active?:boolean|null; metadata?:Record<string,unknown>|null; image_url?:string|null; }
export interface BossEncounter { id:string; world_boss_id:string; player_id:string; damage?:number|null; reward_json?:Record<string,unknown>|null; status?:string|null; created_at?:string|null; }
export interface LoreEntry { id:string; entry_code?:string|null; title?:string|null; content?:string|null; category?:string|null; related_entity?:string|null; metadata?:Record<string,unknown>|null; created_at?:string|null; }
export interface SeasonPass { id:string; name?:string|null; season_number?:number|null; start_at?:string|null; end_at?:string|null; active?:boolean|null; metadata?:Record<string,unknown>|null; }
export interface SeasonTier { tier:number; xp_required:number; is_premium:boolean; reward:Record<string,unknown>; unlocked:boolean; claimed:boolean; }
export interface SeasonProgress { season_xp?:number|null; current_tier?:number|null; tiers?:SeasonTier[]; [key:string]:unknown; }
export interface SeasonRanking { rank_position?:number|null; mmr?:number|null; wins?:number|null; losses?:number|null; draws?:number|null; season_key?:string|null; player_id?:string|null; display_name?:string|null; }
export interface SocialActionResult { ok:boolean; reason?:string|null; [key:string]:unknown; }
export interface SocialFriend { id?:string; player_id?:string; display_name?:string|null; role?:string|null; is_online?:boolean|null; }
export interface SocialFriendRequest { id?:string; request_id?:string; player_id?:string; display_name?:string|null; created_at?:string|null; }
export interface SocialSearchPlayer { id:string; display_name?:string|null; role?:string|null; friend_state?:string|null; request_id?:string|null; is_online?:boolean|null; }
export interface SocialFriendData { ok:boolean; reason?:string|null; friends?:SocialFriend[]|null; incoming_requests?:SocialFriendRequest[]|null; outgoing_requests?:SocialFriendRequest[]|null; }
export interface SocialSearchData { ok:boolean; reason?:string|null; players?:SocialSearchPlayer[]|null; }
export interface SocialConversation { conversation_id:string; other_player_id:string; other_display_name?:string|null; last_message?:string|null; last_message_at?:string|null; unread_count?:number|null; }
export interface SocialConversationData { ok:boolean; reason?:string|null; conversations?:SocialConversation[]|null; }
export interface SocialMessage { id:string; sender_player_id:string; sender_display_name?:string|null; body:string; created_at?:string|null; is_mine?:boolean|null; }
export interface SocialMessageData { ok:boolean; reason?:string|null; messages?:SocialMessage[]|null; }
export interface SocialClanMember { player_id:string; display_name?:string|null; role?:string|null; contribution_accumulated?:number|null; }
export interface SocialClanWar { id:string; reference_id?:string|null; status?:string|null; clan_a_id?:string|null; clan_b_id?:string|null; clan_a_name?:string|null; clan_b_name?:string|null; created_at?:string|null; resolved_at?:string|null; }
export interface SocialClan { id:string; code?:string|null; name?:string|null; prestige?:number|null; role?:string|null; member_count?:number|null; members?:SocialClanMember[]|null; active_wars?:SocialClanWar[]|null; }
export interface SocialClanDiscovery { id:string; code?:string|null; name?:string|null; prestige?:number|null; member_count?:number|null; }
export interface SocialClanData { ok:boolean; reason?:string|null; has_clan?:boolean; clan?:SocialClan|null; available_clans?:SocialClanDiscovery[]|null; }
export interface WorldSnapshot { bosses:WorldBoss[]; raids:RaidRun[]; lore:LoreEntry[]; season:SeasonPass|null; tiers:SeasonTier[]; encounters:BossEncounter[]; seasonProgress:SeasonProgress|null; rankings:SeasonRanking[]; myRaidIds:string[]; }
export type RpcResult<T = unknown> = { ok?:boolean; success?:boolean; reason?:string|null; data?:T; error?:string|null; [key:string]:unknown; };
