import React,{useEffect,useState}from'react';
import{Pressable,ScrollView,StyleSheet,Text,View}from'react-native';
import{useRouter}from'expo-router';
import{WorldBackdrop}from'../src/render/WorldBackdrop';
import{RuntimeHeader}from'../src/app/RuntimeHeader';
import{useGame}from'../src/app/GameProvider';
import{COLORS,QUALITY_BUDGETS,SCENE_ACCENT,type SceneVariant}from'../src/core/constants';
import{RuneButton,SectionTitle,StatSeal,StatusPill,WorldObject,WorldTitle}from'../src/render/Diegetic';
import{BattlefieldCanvas}from'../src/render/BattlefieldCanvas';
import{classifyBattleEvent}from'../src/engine/presentation';
import{currentActor,dispatchPlayerAction,legalActions,legalTargets,startTacticalSession}from'../src/engine/tacticalInteractive';
import type{TacticalActionType,TacticalSession}from'../src/engine/tacticalInteractive';
import{TRAINING_CARDS,TRAINING_ENEMY,makeSeed}from'../src/engine/tacticalLabEngine';
const STEPS=[
 ['NEXUS','DESPERTAR','Tu punto de partida. Aprende la geografía del Nexus, la navegación principal y cómo regresar siempre al ciclo central.','/','nexus'],
 ['CUENTA','IDENTIDAD Y SESIÓN','La cuenta abre tu estado real. Aprende acceso, persistencia de sesión y por qué el cliente nunca fabrica tu perfil.','/auth','nexus'],
 ['ARCHIVO','LAS CARTAS SON EL MUNDO','Inspecciona artwork oficial, facción, rareza, estadísticas, sinergias, propiedad, progreso y lore.','/archive','archive'],
 ['FORJA','CONSTRUIR FORMACIÓN','Aprende Champion, Vanguard, Sentinel y Reserve, validación de deck, selección y guardado.','/forge','forge'],
 ['ARENA','INICIATIVA Y RONDAS','Comprende Velocidad, orden de turno, daño, críticos, HP, estados, energía y lectura del campo.','/arena','arena'],
 ['ARENA','HABILIDADES Y RESPUESTA','Practica Ataque, Habilidad y Guardia. Aprende a seleccionar objetivos y leer consecuencias sin tocar el settlement real.','/arena','arena'],
 ['PVE','AVANZAR EN EL MUNDO','Normal, Elite, Boss, Raid y Event. El PvE es una columna de progreso, no un menú aislado.','/missions','missions'],
 ['MUNDO','BOSSES Y RAIDS','Explora encuentros únicos, fases, participación cooperativa, contribución y recompensas que llegan del servidor.','/world','world'],
 ['ENERGÍA','RITMO DE PROGRESO','La energía limita el ritmo, se sincroniza con el servidor y conecta misiones, PvE y retorno al juego.','/missions','missions'],
 ['ECONOMÍA','CIRCULACIÓN DE VALOR','VEX in-game, VEX tradeable, Gold y Energy. Aprende fuentes, sinks, locks, trazabilidad e idempotencia.','/economy','economy'],
 ['MERCADO','OFERTAR Y ADQUIRIR','Los precios y fees vienen del servidor. Aprende a listar una carta, comprar, cancelar y leer el estado del listing.','/economy','economy'],
 ['TESORERÍA','DEPÓSITOS Y RETIROS','Registra transacciones externas y solicitudes de retiro. La elegibilidad, acreditación y settlement siguen reglas server-side.','/economy','economy'],
 ['TIENDA','PACKS Y REVELACIÓN','Aprende adquisición, órdenes, pago externo, apertura y ceremonia de cartas sin lanzar odds locales.','/store','store'],
 ['FORJA DE CARTAS','FUSIÓN Y EVOLUCIÓN','Las cartas también son progresión. Aprende a consultar política y ejecutar operaciones autorizadas por servidor.','/store','forge'],
 ['SOCIAL','EL META HUMANO','Amigos, solicitudes, búsquedas, chat global, privados, clan, presencia y contribución colectiva.','/social','social'],
 ['TEMPORADA','RANKED Y LEGADO','Rangos, MMR, victorias, derrotas, pase de temporada y recompensas estructuran el ciclo competitivo.','/world','world'],
 ['CÓDICE','LORE Y SIGNIFICADO','El lore conecta regiones, cartas, bosses, facciones y economía. Explora las entradas oficiales del mundo.','/world','world'],
 ['LIVE OPS','UN MUNDO QUE CAMBIA','Eventos, rotaciones y temporadas mantienen el ecosistema vivo. El contenido dinámico se publica por el backend.','/world','events'],
 ['DOMINIO','TU SIGUIENTE SESIÓN','Ya conoces el circuito completo. El dominio real aparece cuando conviertes conocimiento en decisiones, colección, combate y economía sostenible.','/','nexus'],
] as const;
export default function Tutorial(){
 const router=useRouter();const{quality,tutorialStep,setTutorialStep}=useGame();const i=Math.min(tutorialStep,STEPS.length-1);const s=STEPS[i];const accent=SCENE_ACCENT[s[4] as SceneVariant]??COLORS.gold;const progress=Math.round(((i+1)/STEPS.length)*100);const open=()=>router.push(s[3] as never);
 const[practice,setPractice]=useState<TacticalSession|null>(null);const[action,setAction]=useState<TacticalActionType>('attack');const[targetId,setTargetId]=useState<string|null>(null);
 useEffect(()=>{if((i===4||i===5)&&!practice)setPractice(startTacticalSession(TRAINING_CARDS,TRAINING_ENEMY,makeSeed(`tutorial-drill-${i}`)));if(i!==4&&i!==5)setPractice(null)},[i,practice]);
 const actor=practice?currentActor(practice):null;const targets=practice?legalTargets(practice,action):[];const actions=practice?legalActions(practice):[];const activeEvent=practice?.events[practice.events.length-1]??null;
 const dispatch=(type:TacticalActionType)=>{if(!practice||!actor)return;const chosen=type==='guard'?actor.id:targetId??targets[0]?.id;if(!chosen&&type!=='guard')return;setPractice(dispatchPlayerAction(practice,{actorId:actor.id,type,targetId:chosen}));setTargetId(null)};
 const next=async()=>{if(i===STEPS.length-1){await setTutorialStep(STEPS.length);router.back();return;}await setTutorialStep(i+1)};
 const practiceUnits=practice?[...practice.player,...practice.enemy].map(u=>({id:u.id,hp:u.hpNow,max_hp:u.hp,side:u.side,card_id:u.name,status:u.alive?'alive':'defeated',statuses:u.statuses,energy:u.energy,max_energy:u.maxEnergy,role:u.role,faction:u.faction,rarity:u.rarity})):[];
 return<View style={styles.root}><WorldBackdrop variant={s[4] as SceneVariant} tier={quality}/><RuntimeHeader/><ScrollView contentContainerStyle={styles.content}><WorldTitle kicker={`TUTORIAL VIVO · ${s[0]}`} title={s[1]} subtitle={s[2]}/><WorldObject accent={accent} style={styles.progress}><StatusPill label={`${progress}% · ${i+1}/${STEPS.length}`} accent={accent}/><View style={styles.track}><View style={[styles.fill,{width:`${progress}%`,backgroundColor:accent}]}/></View><Text style={styles.hint}>Ruta educativa, no jaula: el objetivo es que comprendas el sistema y puedas actuar dentro de él.</Text><RuneButton label="EXPLORAR ESTE SISTEMA" onPress={open} accent={accent}/></WorldObject>
 {(i===4||i===5)?<><SectionTitle kicker="CAMPO DE PRÁCTICA" title="APRENDE HACIENDO" right={<StatusPill label="SIN SETTLEMENT" accent={COLORS.mint}/>} /><BattlefieldCanvas units={practiceUnits} activeEvent={activeEvent?{event_type:activeEvent.event_type,actor_id:activeEvent.actor_id,target_id:activeEvent.target_id,amount:activeEvent.amount,round:activeEvent.round,payload:activeEvent.payload}:null} activeKind={activeEvent?classifyBattleEvent(activeEvent):'neutral'} selectedTargetId={targetId} onSelectTarget={setTargetId} compact maxAnimatedUnits={QUALITY_BUDGETS[quality].maxAnimatedUnits}/><WorldObject accent={COLORS.arcaneBright} style={styles.drill}><View style={styles.seals}><StatSeal compact label="RONDA" value={practice?.round??0} accent={COLORS.goldBright}/><StatSeal compact label="ACTOR" value={actor?.name??'—'} accent={COLORS.arcaneBright}/><StatSeal compact label="ESTADO" value={practice?.ended?'CERRADO':'ACTIVO'} accent={practice?.ended?COLORS.mint:COLORS.crimson}/></View><Text style={styles.hint}>El ejercicio es un teatro visual local: enseña el vocabulario de acciones, estados y lectura del campo sin crear resultados, recompensas ni autoridad competitiva. En el paso 05 lee la iniciativa; en el 06 practica respuesta.</Text><View style={styles.controls}><RuneButton label="ATAQUE" disabled={!actions.includes('attack')} onPress={()=>setAction('attack')} accent={action==='attack'?COLORS.crimson:COLORS.steel}/><RuneButton label="HABILIDAD" disabled={!actions.includes('skill')} onPress={()=>setAction('skill')} accent={action==='skill'?COLORS.arcaneBright:COLORS.steel}/><RuneButton label="GUARDIA" disabled={!actions.includes('guard')} onPress={()=>setAction('guard')} accent={action==='guard'?COLORS.mint:COLORS.steel}/><RuneButton label="REINICIAR DRILL" onPress={()=>setPractice(startTacticalSession(TRAINING_CARDS,TRAINING_ENEMY,makeSeed(`tutorial-reset-${Date.now()}`)))} accent={COLORS.goldBright}/></View>{action!=='guard'&&targets.length?<View style={styles.targetGrid}>{targets.map(t=><Pressable key={t.id} onPress={()=>setTargetId(t.id)}><WorldObject accent={targetId===t.id?COLORS.goldBright:COLORS.steel} style={styles.target}><Text style={styles.stepT}>{t.name}</Text><Text style={styles.targetMeta}>{t.hpNow}/{t.hp} HP · {t.statuses.marked?'MARCADA':'ESTABLE'}</Text></WorldObject></Pressable>)}</View>:null}<RuneButton label="EJECUTAR ACCIÓN" disabled={!practice||practice.ended||(!targetId&&action!=='guard')} onPress={()=>dispatch(action)} accent={COLORS.goldBright}/></WorldObject></>:null}
 <SectionTitle kicker="MAPA DEL CONOCIMIENTO" title="TODO EL ECOSISTEMA"/>{STEPS.map((x,n)=><WorldObject key={x[0]+x[1]} accent={n<=i?COLORS.mint:COLORS.steel} style={styles.step}><Text style={[styles.stepNo,{color:n<=i?COLORS.mint:COLORS.goldDim}]}>{String(n+1).padStart(2,'0')}</Text><View style={{flex:1}}><Text style={styles.stepK}>{x[0]}</Text><Text style={styles.stepT}>{x[1]}</Text></View><Text style={styles.mark}>{n<i?'✓':n===i?'◆':'○'}</Text></WorldObject>)}<View style={styles.controls}><RuneButton label={i>0?'ANTERIOR':'CERRAR'} onPress={()=>i>0?void setTutorialStep(i-1):router.back()} accent={COLORS.steel}/><RuneButton label={i===STEPS.length-1?'FINALIZAR':'SIGUIENTE'} onPress={()=>void next()} accent={COLORS.goldBright}/></View></ScrollView></View>
}
const styles=StyleSheet.create({root:{flex:1},content:{padding:14,paddingBottom:130,gap:10},progress:{gap:8},track:{height:5,borderRadius:4,backgroundColor:'rgba(255,255,255,.09)',overflow:'hidden'},fill:{height:5,borderRadius:4},hint:{color:COLORS.ash,fontSize:7.5,lineHeight:12},drill:{gap:9},seals:{flexDirection:'row',gap:6,flexWrap:'wrap'},step:{flexDirection:'row',alignItems:'center',gap:10,paddingVertical:10},stepNo:{fontSize:14,fontWeight:'900',width:25,textAlign:'center'},stepK:{color:COLORS.goldDim,fontSize:5.5,fontWeight:'900',letterSpacing:1.4},stepT:{color:COLORS.white,fontFamily:'Cinzel_700Bold',fontSize:9.5,marginTop:2},mark:{color:COLORS.goldBright,fontSize:14},controls:{flexDirection:'row',gap:7,flexWrap:'wrap'},targetGrid:{gap:6,marginTop:2},target:{paddingVertical:9},targetMeta:{color:COLORS.ash,fontSize:6.5,marginTop:3}});
