import { typography, typeScale } from '@/constants/typography';

/**
 * VEXFORGE — UX/CX TIER 1 2026 experience tokens.
 *
 * Source of truth: docs/VE-UXCX-TIER1-2026/00_LOVABLE_MASTER_DIRECTIVE.md
 *
 * The directive requires the five domains to read as places inside one game
 * instead of independent administrative modules. This module holds the shared
 * identity + motion language so no screen invents its own vocabulary.
 */

export type DomainKey = 'foja' | 'arena' | 'archivo' | 'forja' | 'legado';

export type DomainTone = 'accent' | 'primary' | 'danger' | 'success' | 'rarityEpic' | 'rarityRare';

export type DomainIdentity = {
  /** Canonical place name of the domain inside the world. */
  place: string;
  /** Player-facing title of the screen. */
  title: string;
  /** One line that states what the player does here. */
  purpose: string;
  /** Feather icon used as the domain sigil. */
  sigil: string;
  tone: DomainTone;
};

export const DOMAIN_IDENTITY: Record<DomainKey, DomainIdentity> = {
  foja: {
    place: 'FOJA',
    title: 'Nexus de la Forja',
    purpose: 'El lugar al que vuelves entre combates.',
    sigil: 'home',
    tone: 'accent',
  },
  arena: {
    place: 'ARENA',
    title: 'Arena oficial',
    purpose: 'Aqui se prueba lo forjado.',
    sigil: 'zap',
    tone: 'danger',
  },
  archivo: {
    place: 'ARCHIVO',
    title: 'Archivo de cartas',
    purpose: 'Tus cartas son objetos que posees, descubres y estudias.',
    sigil: 'layers',
    tone: 'rarityRare',
  },
  forja: {
    place: 'FORJA',
    title: 'Forja de mazos',
    purpose: 'Aqui construyes tu arma estrategica.',
    sigil: 'columns',
    tone: 'primary',
  },
  legado: {
    place: 'LEGADO',
    title: 'Legado del forjador',
    purpose: 'Esto es lo que has conseguido en VEXFORGE.',
    sigil: 'award',
    tone: 'rarityEpic',
  },
};

/** Motion tokens. Nivel 1 micro, nivel 2 ambiente, nivel 3 navegacion. */
export const MOTION = {
  micro: 160,
  reveal: 320,
  navigation: 460,
  ambient: 2800,
} as const;

/** Depth tokens for the layered scene language. */
export const DEPTH = {
  scene: 0,
  ambient: 1,
  surface: 2,
  focus: 3,
} as const;

/**
 * T2V shared visual-system contract.
 *
 * These values describe presentation roles only. They must not become a
 * source of gameplay state, card data, combat timing, or reward logic.
 * Screens consume the roles and resolve their actual colors through useColors.
 */
export const VISUAL_TOKENS = {
  material: {
    scene: { elevation: DEPTH.scene, opacity: 1 },
    ambient: { elevation: DEPTH.ambient, opacity: 0.72 },
    panel: { elevation: DEPTH.surface, opacity: 0.9 },
    focus: { elevation: DEPTH.focus, opacity: 0.96 },
    borderOpacity: { toned: 0.58, neutral: 0.78 },
  },
  colorRoles: {
    scene: 'background',
    surface: 'panel',
    surfaceStrong: 'panelStrong',
    text: 'foreground',
    secondaryText: 'mutedForeground',
    divider: 'border',
    focus: 'accent',
    danger: 'danger',
  },
  typography: {
    display: { fontFamily: typography.display, fontSize: typeScale.display, lineHeight: 44, letterSpacing: 0.2 },
    title: { fontFamily: typography.display, fontSize: typeScale.title, lineHeight: 32, letterSpacing: 0.1 },
    section: { fontFamily: typography.display, fontSize: typeScale.section, lineHeight: 25 },
    body: { fontFamily: typography.body, fontSize: typeScale.body, lineHeight: 21 },
    meta: { fontFamily: typography.bodySemiBold, fontSize: typeScale.meta, lineHeight: 15, letterSpacing: 0.9 },
    label: { fontFamily: typography.bodyBold, fontSize: typeScale.label, lineHeight: 13, letterSpacing: 1.5 },
  },
  radius: {
    compact: 10,
    surface: 14,
    modal: 18,
    pill: 999,
  },
  border: {
    hairline: 1,
    standard: 1,
    focus: 2,
  },
  shadow: {
    ambient: { opacity: 0.12, radius: 8, elevation: 2 },
    surface: { opacity: 0.22, radius: 12, elevation: 4 },
    focus: { opacity: 0.3, radius: 16, elevation: 7 },
  },
  icon: {
    defaultStroke: 1.7,
    activeStroke: 2.1,
    disabledOpacity: 0.46,
  },
  spacing: {
    micro: 4,
    compact: 8,
    control: 12,
    surface: 16,
    section: 24,
    scene: 32,
  },
  safeArea: {
    horizontal: 16,
    topContent: 18,
    bottomNavigation: 108,
    webTopInset: 67,
    webBottomInset: 34,
  },
  motion: {
    micro: MOTION.micro,
    reveal: MOTION.reveal,
    navigation: MOTION.navigation,
    ambient: MOTION.ambient,
  },
  qualityTiers: {
    low: { ambient: false, particles: false, blur: false },
    standard: { ambient: true, particles: false, blur: true },
    high: { ambient: true, particles: true, blur: true },
  },
  control: {
    button: {
      minHeight: 46,
      radius: 12,
      paddingHorizontal: 14,
      iconSize: 16,
      gap: 8,
      pressedOpacity: 0.72,
      disabledOpacity: 0.45,
    },
    progress: {
      height: 6,
      radius: 4,
    },
  },
  domainHeader: {
    rootPaddingBottom: 16,
    sigilSize: 36,
    sigilRadius: 12,
    sigilStroke: 1,
    identityGap: 10,
    place: { fontSize: 10, letterSpacing: 2 },
    ruleWidth: 54,
    ruleRadius: 1,
    trailingMargin: 12,
    title: { fontSize: 30, letterSpacing: -0.7 },
    titleTop: 14,
    purpose: { fontSize: 13, lineHeight: 18 },
    purposeTop: 5,
    childrenTop: 12,
  },
  worldHeader: {
    root: { paddingHorizontal: 17, gap: 13 },
    top: { gap: 12 },
    seal: { size: 43, radius: 14, borderWidth: 1, iconSize: 19 },
    refresh: { size: 40, radius: 13, borderWidth: 1, iconSize: 17 },
    eyebrow: { fontSize: 10, fontWeight: '900', letterSpacing: 1.45 },
    title: { fontSize: 27, fontWeight: '800', marginTop: 3 },
    copy: { fontSize: 12, lineHeight: 18 },
    tabs: { gap: 8, paddingVertical: 3, paddingRight: 12 },
    tab: { minHeight: 38, borderWidth: 1, radius: 12, paddingHorizontal: 12, gap: 7 },
    tabText: { fontSize: 10, fontWeight: '900', letterSpacing: 0.45 },
  },
  worldBoss: {
    card: { borderWidth: 1, radius: 17 },
    art: { height: 148, padding: 14 },
    missingArt: { borderWidth: 1, gap: 7, paddingHorizontal: 18 },
    missingArtText: { fontSize: 9, fontWeight: '900', letterSpacing: 0.7 },
    artCopy: { paddingRight: 76 },
    code: { fontSize: 9, fontWeight: '900', letterSpacing: 1.1 },
    title: { fontSize: 20, fontWeight: '900', marginTop: 5 },
    tier: { right: 13, top: 13, paddingHorizontal: 9, paddingVertical: 5, radius: 8, borderWidth: 1 },
    tierText: { fontSize: 9, fontWeight: '900', letterSpacing: 0.7 },
    body: { padding: 14, gap: 10 },
    lore: { fontSize: 12, lineHeight: 18 },
    metaRow: { gap: 8 },
    metaText: { fontSize: 10, fontWeight: '700', letterSpacing: 0.45 },
    hpRow: { gap: 9 },
    hpTrack: { height: 6, radius: 4 },
    hpText: { fontSize: 10, fontWeight: '800' },
    rewardRow: { gap: 8 },
    rewardText: { fontSize: 10, fontWeight: '800' },
    damageText: { fontSize: 10, fontWeight: '800' },
    action: { minHeight: 45, radius: 11, paddingHorizontal: 14, gap: 8, iconSize: 15 },
    actionText: { fontSize: 10, fontWeight: '900', letterSpacing: 0.7 },
    integrityNote: { fontSize: 9, lineHeight: 14 },
  },
  scene: {
    backgroundOpacity: 0.74,
    ambientGlow: {
      size: 300,
      radius: 150,
      leftTop: 96,
      leftOffset: -174,
      rightTop: 300,
      rightOffset: -188,
    },
    orbit: {
      size: 430,
      radius: 215,
      borderWidth: 1,
      top: 86,
      right: -250,
      rotation: '18deg',
    },
    watermark: {
      size: 220,
      top: 12,
      right: -54,
      opacity: 0.16,
    },
    ambientMotion: {
      left: { baseOpacity: 0.1, pulseOpacity: 0.1, translateY: -16, scale: 0.08 },
      right: { baseOpacity: 0.08, pulseOpacity: 0.1, translateY: 14, scale: 0.06 },
    },
  },
  state: {
    gap: 9,
    marginTop: 10,
    paddingHorizontal: 18,
    paddingVertical: 22,
    skeletonWidth: '78%',
    skeletonGap: 6,
    skeletonMargin: 2,
    skeletonHeight: 7,
    skeletonRadius: 4,
    skeletonLineLongWidth: '88%',
    skeletonLineShortWidth: '62%',
    titleSize: 15,
    titleWeight: '800',
    titleTracking: 0.4,
    messageSize: 12,
    messageLineHeight: 18,
    messageMaxWidth: 310,
    iconSize: 34,
    actionRadius: 10,
    actionTop: 3,
    actionHorizontalPadding: 12,
    actionVerticalPadding: 9,
    actionTextSize: 10,
    actionTextWeight: '800',
    actionTextTracking: 1,
    assetError: {
      rootInset: 20,
      rootTop: '42%',
      panelBorderWidth: 1,
      panelRadius: 14,
      panelPaddingHorizontal: 16,
      panelPaddingVertical: 12,
      titleSize: 10,
      titleTracking: 1.4,
      bodySize: 12,
      bodyMarginTop: 4,
    },
    errorFallback: {
      containerPadding: 24,
      contentGap: 16,
      contentMaxWidth: 600,
      title: { fontSize: 28, lineHeight: 40 },
      titleWeight: '700',
      message: { fontSize: 16, lineHeight: 24 },
      debugIconSize: 20,
      closeIconSize: 24,
      topButton: { inset: 16, size: 44, radius: 8 },
      button: {
        paddingVertical: 16,
        radius: 8,
        paddingHorizontal: 24,
        minWidth: 200,
        elevation: 3,
        shadow: { offsetWidth: 0, offsetHeight: 2, opacity: 0.1, radius: 4 },
      },
      buttonTextSize: 16,
      buttonTextWeight: '600',
      modalOverlayOpacity: 0.5,
      modal: { height: '90%', radius: 16 },
      modalHeader: { paddingHorizontal: 16, paddingTop: 16, paddingBottom: 12, borderWidth: 1 },
      modalTitleSize: 20,
      modalTitleWeight: '600',
      closeButtonSize: 44,
      errorContainer: { radius: 8, padding: 16 },
      errorText: { fontSize: 12, lineHeight: 18 },
    },
  },
  navigation: {
    bar: {
      webHeight: 84,
      mobileBaseHeight: 72,
      topPadding: 6,
      bottomPadding: 6,
      horizontalPadding: 7,
      itemMinHeight: 56,
      itemPaddingVertical: 3,
      elevation: 12,
      topRailInset: 18,
      topRailHeight: 1,
    },
    label: {
      fontSize: 9,
      letterSpacing: 1,
    },
    seal: {
      width: 38,
      height: 30,
      radius: 4,
      borderWidth: 1,
      beaconSize: 4,
      beaconRadius: 2,
      beaconBottom: 3,
    },
    authLoading: {
      gap: 14,
      labelSize: 10,
      labelTracking: 1.5,
    },
  },
  identityMark: {
    frame: {
      size: 38,
      borderWidth: 1,
      radius: 12,
      rotation: '45deg',
    },
    compact: {
      size: 30,
      radius: 9,
    },
    image: {
      scale: '72%',
      radius: 6,
    },
  },
  metricPlaque: {
    width: '31%',
    minHeight: 84,
    radius: 12,
    gap: 4,
    borderWidth: 1,
    iconSize: 18,
    valueSize: 18,
    labelSize: 8,
    labelTracking: 0.6,
  },
  profileIdentity: {
    card: { borderWidth: 1, radius: 16, padding: 14, gap: 11 },
    avatar: { size: 54, borderWidth: 1, radius: 17, textSize: 20, textWeight: '900' },
    eyebrow: { fontSize: 8, letterSpacing: 1.1 },
    name: { fontSize: 20, marginTop: 3 },
    meta: { fontSize: 10, marginTop: 3 },
    status: { fontSize: 9, marginTop: 5 },
    action: { size: 36, borderWidth: 1, radius: 10, iconSize: 17 },
  },
  profileStats: {
    gridGap: 8,
    card: { width: '48%', minHeight: 82, borderWidth: 1, radius: 13, padding: 10, gap: 4 },
    iconSize: 16,
    valueSize: 20,
    label: { fontSize: 8, letterSpacing: 0.8 },
  },
  profileProgress: {
    card: { borderWidth: 1, radius: 14, padding: 13 },
    header: { gap: 8 },
    eyebrow: { fontSize: 8, letterSpacing: 1 },
    title: { fontSize: 18, marginTop: 4 },
    value: { fontSize: 10, marginTop: 2 },
    track: { height: 8, radius: 8, marginTop: 13 },
    meta: { marginTop: 7, gap: 8 },
    metaTextSize: 9,
  },
  profileActions: {
    title: { fontSize: 9, letterSpacing: 1.2, marginTop: 2 },
    gridGap: 8,
    card: { width: '48%', minHeight: 58, borderWidth: 1, radius: 12, paddingHorizontal: 11, gap: 9 },
    iconSize: 18,
    labelSize: 11,
  },
  profileFeedback: {
    notice: {
      horizontalInset: 18,
      bottomInset: 14,
      minHeight: 42,
      borderWidth: 1,
      radius: 12,
      paddingHorizontal: 12,
      paddingVertical: 8,
      gap: 8,
      iconSize: 16,
      textSize: 11,
      lineHeight: 15,
    },
    loading: { gap: 10, labelSize: 10, labelTracking: 1.3 },
  },
  profileModal: {
    backdropColor: '#000000B8',
    panel: { maxHeight: '78%', minHeight: 260, borderTopWidth: 1, radius: 20, padding: 18 },
    header: { marginBottom: 16 },
    close: { size: 36, borderWidth: 1, radius: 10, iconSize: 18 },
    gridGap: 8,
    content: {
      eyebrow: { fontSize: 9, letterSpacing: 1 },
      title: { fontSize: 22, marginTop: 4 },
      body: { fontSize: 18 },
      muted: { fontSize: 12, lineHeight: 17 },
      copyGap: 8,
      listMaxHeight: 320,
      row: { minHeight: 58, borderWidth: 1, radius: 11, padding: 10, marginBottom: 7, gap: 9 },
      rowTitle: { fontSize: 13 },
      points: { fontSize: 12 },
      rank: { width: 35, fontSize: 15 },
      signOut: { minHeight: 46, borderWidth: 1, radius: 11, paddingHorizontal: 14, gap: 8, marginTop: 10 },
      signOutText: { fontSize: 11, letterSpacing: 0.8 },
    },
  },
  battlefield: {
    root: { radius: 22, padding: 12, gap: 10 },
    typography: {
      eyebrow: { fontSize: 8, fontWeight: '900', letterSpacing: 1.2 },
      title: { fontSize: 18, fontWeight: '900', letterSpacing: 0.4, marginTop: 3 },
      turnValue: { fontSize: 13, fontWeight: '900' },
      turnLabel: { fontSize: 7, fontWeight: '900', letterSpacing: 0.6, marginTop: 2 },
      identityKicker: { fontSize: 8, fontWeight: '900', letterSpacing: 0.9 },
      identityName: { fontSize: 12, fontWeight: '800', marginTop: 2 },
      identityStatus: { fontSize: 8, fontWeight: '900', letterSpacing: 0.7 },
      roleText: { fontSize: 7, fontWeight: '900', letterSpacing: 0.45 },
      fallenText: { fontSize: 6, fontWeight: '900', letterSpacing: 0.4 },
      artMissing: { fontSize: 6, fontWeight: '900' },
      unitName: { fontSize: 10, lineHeight: 13, fontWeight: '800', minHeight: 26 },
      unitFaction: { fontSize: 7, fontWeight: '900', letterSpacing: 0.3 },
      hpText: { fontSize: 7, fontWeight: '700' },
      keyword: { fontSize: 5.5, fontWeight: '900', letterSpacing: 0.2 },
      reserveTitle: { fontSize: 7, fontWeight: '900', letterSpacing: 0.5 },
      emptyReserve: { fontSize: 7, fontWeight: '900' },
      laneLabel: { fontSize: 9, fontWeight: '900', letterSpacing: 0.8 },
      laneCopy: { fontSize: 9 },
      damageLabel: { fontSize: 11, fontWeight: '900', marginTop: 2 },
      outcome: { fontSize: 9, fontWeight: '900', letterSpacing: 0.7, paddingVertical: 4 },
    },
    controls: {
      borderWidth: 1,
      topBarPaddingHorizontal: 3,
      turnBadge: { minWidth: 54, radius: 12, paddingVertical: 6 },
      sideBlockGap: 7,
      stateRail: { gap: 7, paddingTop: 2 },
      roleRow: { minHeight: 14, gap: 3 },
      artMissing: { borderWidth: 1, gap: 3 },
      hpTrack: { height: 5, radius: 3, marginTop: 3 },
      keywordRow: { gap: 3, minHeight: 13 },
      keyword: { borderWidth: 1, radius: 4, paddingHorizontal: 3, paddingVertical: 2 },
      reserveHeader: { gap: 4, minWidth: 62 },
      reserveItemsGap: 4,
      reserveBorderWidth: 1,
      laneLine: { width: 34, height: 2, radius: 1, marginBottom: 2 },
    },
    identity: { markSize: 30, markRadius: 10, gap: 8, paddingHorizontal: 3 },
    formation: { gap: 6 },
    unitCard: { radius: 13, padding: 6, gap: 3 },
    unitArt: { height: 74, radius: 9 },
    championArtHeight: 92,
    reserve: {
      gap: 8,
      minHeight: 28,
      paddingHorizontal: 3,
      itemWidth: 24,
      itemHeight: 28,
      itemRadius: 5,
    },
    lane: { radius: 12, paddingVertical: 8, paddingHorizontal: 10, gap: 2 },
  },
  domainPortal: {
    object: { minHeight: 137, paddingHorizontal: 4, paddingVertical: 8 },
    halo: { size: 54, radius: 31, borderWidth: 1, rotation: '45deg' },
    sigil: { size: 34, borderWidth: 1, rotation: '-45deg' },
    core: { size: 6, radius: 3, offset: 1 },
    trace: { width: 34, height: 1 },
    label: { fontSize: 8, letterSpacing: 1.35, marginTop: 4 },
    title: { fontSize: 11.5, lineHeight: 15, marginTop: 3 },
    status: { gap: 5, marginTop: 4, markSize: 4, markRadius: 2 },
    iconSize: 17,
  },
  formation: {
    root: { radius: 18, padding: 14, gap: 10 },
    heading: { gap: 10 },
    seal: { size: 36, radius: 12 },
    kicker: { fontSize: 9, fontWeight: '900', letterSpacing: 1.2 },
    title: { fontSize: 19, fontWeight: '900', marginTop: 2 },
    count: { fontSize: 11, fontWeight: '800' },
    copy: { fontSize: 11, lineHeight: 17 },
    section: { fontSize: 9, fontWeight: '900', letterSpacing: 1, marginTop: 3 },
    rows: { gap: 6 },
    card: { minWidth: 92, radius: 12, padding: 8, gap: 4 },
    cardHeader: { gap: 4 },
    cardArt: { height: 64, radius: 8, placeholderBackground: 'rgba(0,0,0,0.2)' },
    role: { fontSize: 8, fontWeight: '900', letterSpacing: 0.5 },
    name: { fontSize: 11, lineHeight: 14, fontWeight: '800', minHeight: 28 },
    meta: { fontSize: 8, lineHeight: 12 },
    power: { fontSize: 8, fontWeight: '900', marginTop: 2 },
    emptyCard: { fontSize: 10, lineHeight: 14, minHeight: 28 },
    feedback: {
      minHeight: 50,
      radius: 12,
      padding: 10,
      gap: 8,
      borderColor: 'rgba(255,255,255,0.12)',
    },
    feedbackText: { fontSize: 9, fontWeight: '900', letterSpacing: 0.4, lineHeight: 14 },
    retry: { radius: 8, paddingHorizontal: 8, paddingVertical: 7 },
    retryText: { fontSize: 8, fontWeight: '900', letterSpacing: 0.5 },
    footnote: { fontSize: 9, lineHeight: 14 },
  },
} as const;
