import { db } from './supabase';
import type { Env } from './env';
import { error, json } from './response';
const SESSION_COOKIE='kivora_session', CSRF_COOKIE='kivora_csrf';
const enc=new TextEncoder();
function b64(bytes:Uint8Array){let s='';for(const b of bytes)s+=String.fromCharCode(b);return btoa(s).replaceAll('+','-').replaceAll('/','_').replaceAll('=','');}
function bytesFromB64(s:string){const pad='='.repeat((4-(s.length%4))%4);const bin=atob(s.replaceAll('-','+').replaceAll('_','/')+pad);return Uint8Array.from(bin,c=>c.charCodeAt(0));}
function randomB64(size=32){const b=new Uint8Array(size);crypto.getRandomValues(b);return b64(b);}
export async function sha256(value:string){return b64(new Uint8Array(await crypto.subtle.digest('SHA-256',enc.encode(value))))}
export async function hashPassword(password:string){const iterations=210000;const salt=new Uint8Array(16);crypto.getRandomValues(salt);const key=await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',salt,iterations,hash:'SHA-256'},key,256);return {hash:b64(new Uint8Array(bits)),salt:b64(salt),iterations};}
export async function verifyPassword(password:string,storedHash:string,storedSalt:string,iterations:number){try{const key=await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',salt:bytesFromB64(storedSalt),iterations,hash:'SHA-256'},key,256);const a=new Uint8Array(bits),b=bytesFromB64(storedHash);if(a.length!==b.length)return false;let diff=0;for(let i=0;i<a.length;i++)diff|=a[i]^b[i];return diff===0;}catch{return false;}}
function cookie(name:string,value:string,maxAge:number,httpOnly:boolean,secure:boolean){return `${name}=${value}; Max-Age=${maxAge}; Path=/; SameSite=Strict${secure?'; Secure':''}${httpOnly?'; HttpOnly':''}`;}
export function clearAuthHeaders(request:Request){const h=new Headers();const secure=new URL(request.url).protocol==='https:';h.append('set-cookie',cookie(SESSION_COOKIE,'',0,true,secure));h.append('set-cookie',cookie(CSRF_COOKIE,'',0,false,secure));return h;}
export async function issueSession(env:Env,accountId:string,request:Request){const token=randomB64(32),csrf=randomB64(24),client=db(env);await client.from('sessions').delete().eq('account_id',accountId).lt('expires_at',new Date().toISOString());const {error:insertError}=await client.from('sessions').insert({account_id:accountId,token_hash:await sha256(token),csrf_hash:await sha256(csrf),expires_at:new Date(Date.now()+1000*60*60*24*14).toISOString()});if(insertError)throw new Error(insertError.message);const headers=new Headers(),secure=new URL(request.url).protocol==='https:';headers.append('set-cookie',cookie(SESSION_COOKIE,token,60*60*24*14,true,secure));headers.append('set-cookie',cookie(CSRF_COOKIE,csrf,60*60*24*14,false,secure));return {headers};}
export async function requireSession(request:Request,env:Env){const raw=request.headers.get('Cookie')??'',match=raw.match(new RegExp(`${SESSION_COOKIE}=([^;]+)`));if(!match)return null;const tokenHash=await sha256(match[1]);const {data,error:dbError}=await db(env).from('sessions').select('id,account_id,csrf_hash,expires_at').eq('token_hash',tokenHash).maybeSingle();if(dbError||!data)return null;if(new Date(data.expires_at).getTime()<=Date.now()){await db(env).from('sessions').delete().eq('id',data.id);return null;}return {sessionId:data.id,accountId:data.account_id,csrfHash:data.csrf_hash};}
export async function requireCsrf(request:Request,session:{csrfHash:string}){const token=request.headers.get('x-csrf-token');if(!token)return false;return (await sha256(token))===session.csrfHash;}
export async function currentAccount(request:Request,env:Env){const session=await requireSession(request,env);if(!session)return null;const {data,error:dbError}=await db(env).from('accounts').select('id,public_id,username,email,role,status').eq('id',session.accountId).maybeSingle();if(dbError||!data||data.status!=='active')return null;return {session,account:data};}
export async function requireUser(request:Request,env:Env){const current=await currentAccount(request,env);return current??{error:error('Authentication required.',401)};}
export async function requireAdmin(request:Request,env:Env){const current=await currentAccount(request,env);if(!current)return {error:error('Authentication required.',401)};if(current.account.role!=='admin')return {error:error('Admin access required.',403)};return current;}
export async function rateKey(request:Request){const ip=request.headers.get('CF-Connecting-IP')??request.headers.get('x-forwarded-for')?.split(',')[0]?.trim()??'unknown';return sha256(ip);}
export async function allowRate(env:Env,key:string,limit:number,windowSeconds:number){const {data,error}=await db(env).rpc('consume_rate_limit',{p_key:key,p_limit:limit,p_window_seconds:windowSeconds});if(error)throw new Error(error.message);return Boolean(data);}
export async function logout(env:Env,request:Request){const session=await requireSession(request,env);if(session)await db(env).from('sessions').delete().eq('id',session.sessionId);return json(null,200,clearAuthHeaders(request));}
