import { Check, CircleDollarSign, Clock3, Database, ShieldCheck, Users, WalletCards, X } from 'lucide-react';
import type { TreasurySummary, Withdrawal } from '../lib/types';
import { points, shortDate } from '../lib/format';

export function AdminPage({ summary, treasury, withdrawals, onAction }: { summary: any; treasury: TreasurySummary | null; withdrawals: Withdrawal[]; onAction: (id: string, action: 'approve' | 'reject' | 'paid', note?: string) => Promise<void> }) {
  const treasurySummary = treasury?.summary ?? summary ?? {};
  const movements = treasury?.movements ?? [];
  const settlements = treasury?.settlements ?? [];
  return <div className="page-stack scene-page treasury-control">
    <section className="scene-page-heading"><div><span className="scene-eyebrow"><ShieldCheck size={12} /> TREASURY CONTROL</span><h1>Separate activity from cash.</h1><p>Owner-only operations for payout review, provider reconciliation and treasury evidence. No automatic signing or invented settlement records.</p></div><div className="admin-badge"><ShieldCheck size={15} /> Restricted</div></section>
    <section className="treasury-command-grid"><div className="scene-panel treasury-rail-card"><span className="scene-eyebrow">FIXED RAIL</span><strong>{treasurySummary?.payoutAsset || 'USDT'} · {treasurySummary?.payoutNetwork || 'TRC20'}</strong><p>Starting balance is zero. Seed receipts and provider settlements must be recorded before payment.</p></div><div className="scene-panel treasury-rail-card"><span className="scene-eyebrow">PROVIDER</span><strong>BitcoTasks</strong><p>{Number(treasurySummary?.providerActivityUsd ?? 0).toFixed(2)} USD activity · {Number(treasurySummary?.providerSettlementsUsd ?? 0).toFixed(2)} USD recorded receipts.</p></div></section>
    <div className="stats-grid"><div className="stat-card tone-cyan"><div className="stat-icon"><Users size={18} /></div><div className="stat-copy"><small>Total accounts</small><strong>{summary?.accounts ?? '—'}</strong></div></div><div className="stat-card tone-amber"><div className="stat-icon"><Clock3 size={18} /></div><div className="stat-copy"><small>Pending withdrawals</small><strong>{summary?.pendingWithdrawals ?? '—'}</strong></div></div><div className="stat-card tone-violet"><div className="stat-icon"><CircleDollarSign size={18} /></div><div className="stat-copy"><small>User liability</small><strong>{points(Number(summary?.pointsAvailableLiability ?? 0))} KP</strong></div></div><div className="stat-card tone-green"><div className="stat-icon"><WalletCards size={18} /></div><div className="stat-copy"><small>Recorded treasury</small><strong>{Number(treasurySummary?.treasuryBalanceCrypto ?? 0).toFixed(2)} USDT</strong></div></div></div>
    <section><div className="scene-section-heading"><div><span className="scene-eyebrow">QUEUE</span><h2>Withdrawals needing review</h2></div></div><div className="admin-grid">{withdrawals.length ? withdrawals.map((withdrawal) => <article className="admin-card" key={withdrawal.id}><div className="admin-card-head"><span className={`status ${withdrawal.status}`}>{withdrawal.status}</span><small>{shortDate(withdrawal.createdAt)}</small></div><div className="admin-amount"><strong>{points(withdrawal.amountPoints)} KP</strong><span>{withdrawal.asset} · {withdrawal.network}{withdrawal.amountUsdReference ? ` · $${withdrawal.amountUsdReference.toFixed(2)} reference` : ''}</span></div><code>{withdrawal.destination}</code><div className="admin-actions">{withdrawal.status === 'pending' && <><button className="secondary-button" onClick={() => void onAction(withdrawal.id, 'reject', 'Rejected during manual review')}><X size={15} /> Reject</button><button className="primary-button" onClick={() => void onAction(withdrawal.id, 'approve')}><Check size={15} /> Approve</button></>}{withdrawal.status === 'approved' && <button className="primary-button" onClick={() => void onAction(withdrawal.id, 'paid', 'Paid manually; transaction hash recorded')}>Mark paid</button>}</div></article>) : <div className="empty-state"><ShieldCheck size={28} /><h3>The queue is clear</h3><p>Pending withdrawal requests will appear here.</p></div>}</div></section>
    <section className="scene-panel evidence-panel"><div className="scene-section-heading"><div><span className="scene-eyebrow"><Database size={12} /> EVIDENCE REGISTER</span><h2>Recorded treasury facts.</h2></div><span className="scene-readonly">SOURCE DATA ONLY</span></div><div className="evidence-grid"><div><strong>{movements.length}</strong><span>treasury movements</span><small>{movements.length ? `Latest ${shortDate(movements[0].created_at)}` : 'No movements recorded yet.'}</small></div><div><strong>{settlements.length}</strong><span>provider settlements</span><small>{settlements.length ? `Latest ${shortDate(settlements[0].received_at ?? settlements[0].created_at)}` : 'No settlement receipts recorded yet.'}</small></div><div><strong>{Number(treasurySummary?.treasuryBalanceCrypto ?? 0).toFixed(2)}</strong><span>USDT recorded</span><small>Manual balance evidence only</small></div></div>{movements.length > 0 && <div className="evidence-list">{movements.slice(0, 5).map((movement: any) => <div className="evidence-row" key={movement.id}><span>{movement.movement_type}</span><strong>{Number(movement.amount_crypto ?? 0).toFixed(4)} {movement.asset}</strong><small>{movement.reference_id ?? 'No reference'} · {shortDate(movement.created_at)}</small></div>)}</div>}</section>
  </div>;
}