import { ArrowRight, BadgeCheck, CircleDollarSign, ChevronRight, Gift, Layers3, ShieldCheck, Sparkles, Timer, WalletCards, Zap, CheckCircle2 } from 'lucide-react';
import { Logo } from '../components/Logo';

export function LandingPage({onLogin,onRegister,onLegal,onShowDemo}:{onLogin:()=>void;onRegister:()=>void;onLegal:(p:string)=>void;onShowDemo:()=>void}){
 return <div className="landing-shell">
  <nav className="landing-nav"><Logo/><div className="landing-links"><a href="#how">How it works</a><a href="#earn">Ways to earn</a><a href="#payouts">Cashout</a></div><div className="landing-nav-actions"><button className="text-button" onClick={onLogin}>Sign in</button><button className="primary-button compact" onClick={onRegister}>Join Kivora <ArrowRight size={15}/></button></div></nav>
  <main>
   <section className="landing-hero">
    <div className="landing-copy"><span className="kicker"><Sparkles size={13}/> TURN ATTENTION INTO VALUE</span><h1>Earn with a<br/><em>clearer path.</em></h1><p>Kivora is a modern rewards network for verified digital opportunities. Discover tasks, see the reward before you start, build Kivora Points, and choose when to request a crypto payout.</p><div className="hero-actions"><button className="primary-button hero-button" onClick={onRegister}>Start earning free <ArrowRight size={17}/></button><button className="secondary-button hero-button" onClick={onShowDemo}>See how it works <ChevronRight size={17}/></button></div><div className="hero-proof"><span><BadgeCheck size={14}/> Provider-confirmed rewards</span><span><ShieldCheck size={14}/> Server-side integrity</span><span><WalletCards size={14}/> Reviewed cashout</span></div></div>
    <div className="hero-stage" aria-label="Kivora rewards experience preview">
      <div className="hero-art"><img src="/kivora-hero.webp" alt="Abstract Kivora reward environment" fetchPriority="high"/></div>
      <div className="hero-art-shade"/>
      <div className="hero-ring ring-a"/><div className="hero-ring ring-b"/>
      <div className="hero-core"><div className="core-top"><span>REWARD FLOW</span><i/></div><strong>KIVORA</strong><span className="core-points">DISCOVER · COMPLETE · VERIFY</span><div className="core-progress"><i/></div><div className="core-stats"><div><small>STEP 01</small><b>DISCOVER</b></div><div><small>STEP 02</small><b>VERIFY</b></div><div><small>STEP 03</small><b>CASH OUT</b></div></div></div>
      <div className="float-card fc-a"><Timer size={15}/><div><b>Quick actions</b><span>PTC · video · articles</span></div><strong>LIVE</strong></div>
      <div className="float-card fc-b"><CheckCircle2 size={15}/><div><b>Verified by provider</b><span>Rewards settle after confirmation</span></div><ChevronRight size={15}/></div>
    </div>
   </section>
   <section className="social-proof"><span>ONE REWARDS LAYER</span><div><b>Offers</b><b>Surveys</b><b>PTC</b><b>Video</b><b>Tasks</b><b>Shortlinks</b><b>Articles</b><b>Faucets</b></div></section>
   <section className="landing-section" id="how"><div className="section-intro"><span className="kicker">THE LOOP</span><h2>Every reward follows a visible path.</h2><p>No mystery balance changes. Your activity moves through discovery, provider verification and the Kivora ledger.</p></div><div className="loop-grid"><div><span>01</span><Zap size={20}/><h3>Discover</h3><p>Browse live campaigns with the reward and requirements visible before you begin.</p></div><div><span>02</span><Layers3 size={20}/><h3>Complete</h3><p>Follow the advertiser's instructions exactly and keep your campaign conditions intact.</p></div><div><span>03</span><CircleDollarSign size={20}/><h3>Verify</h3><p>BitcoTasks confirms the event server-to-server before Kivora settles the reward.</p></div><div><span>04</span><WalletCards size={20}/><h3>Cash out</h3><p>Request supported crypto from your internal points balance through a reviewed queue.</p></div></div></section>
   <section className="landing-section light-section" id="earn"><div className="section-intro"><span className="kicker">WAYS TO EARN</span><h2>A rewards hub, not a link farm.</h2><p>Kivora groups different task rhythms into one searchable workspace so you can choose what fits your time.</p></div><div className="method-grid"><div><div className="method-icon"><Layers3 size={18}/></div><h3>Offer missions</h3><p>App installs, registrations and milestone-based campaigns with visible progress where the provider supplies it.</p><span>Higher potential</span></div><div><div className="method-icon"><Timer size={18}/></div><h3>Quick actions</h3><p>PTC, shortlinks, reading and other smaller actions for shorter sessions.</p><span>Low friction</span></div><div><div className="method-icon"><Gift size={18}/></div><h3>Progress that stays visible</h3><p>Levels, streak signals, activity history and a single points balance keep the journey understandable.</p><span>Built for rhythm</span></div></div></section>
   <section className="landing-section payout-section" id="payouts"><div className="payout-card"><div><span className="kicker">KIVORA WALLET</span><h2>Your points stay internal until you choose to withdraw.</h2><p>The platform does not store blockchain private keys. Withdrawal requests reserve points immediately, then pass through manual review before an external crypto transfer is recorded.</p></div><div className="payout-options"><span>USDC · BASE</span><span>USDC · SOLANA</span><span>BTC · BITCOIN</span><span>LTC · LITECOIN</span></div></div></section>
   <section className="final-cta"><span className="kicker"><Sparkles size={13}/> KIVORA</span><h2>Your next reward starts with one action.</h2><button className="primary-button hero-button" onClick={onRegister}>Create your Kivora account <ArrowRight size={17}/></button></section>
  </main>
  <footer className="landing-footer"><span>© 2026 Kivora · A VEXFORGE ecosystem product</span><div><button onClick={()=>onLegal('/terms')}>Terms</button><button onClick={()=>onLegal('/privacy')}>Privacy</button></div></footer>
 </div>;
}
