import { ArrowRight, BadgeDollarSign, CalendarDays, ChevronRight, CircleDollarSign, Flame, Gift, ShieldCheck, Sparkles, Trophy, WalletCards } from 'lucide-react';
import type { EarnItem, PlatformConfig, User, Wallet, LedgerEntry } from '../lib/types';
import { points, usdFromPoints } from '../lib/format';
import { StatCard } from '../components/StatCard';
import { OfferCard } from '../components/OfferCard';
import { ActivityFeed } from '../components/ActivityFeed';

function metrics(entries:LedgerEntry[]){
 const today=new Date(); const days=new Set(entries.filter(e=>e.type==='reward'&&e.pointsDelta>0).map(e=>new Date(e.createdAt).toISOString().slice(0,10)));
 let streak=0; const d=new Date(today); for(let i=0;i<30;i++){const key=d.toISOString().slice(0,10);if(days.has(key)){streak++;d.setDate(d.getDate()-1)}else break}
 const todayRewards=entries.filter(e=>e.type==='reward'&&new Date(e.createdAt).toDateString()===today.toDateString()).length; return {streak,todayRewards};
}
function level(pointsEarned:number){const levels=[0,1000,5000,15000,40000,100000];let idx=0;for(let i=0;i<levels.length;i++)if(pointsEarned>=levels[i])idx=i;const current=levels[idx],next=levels[idx+1]??current;const progress=next===current?100:Math.min(100,((pointsEarned-current)/(next-current))*100);return {name:['Newcomer','Spark','Momentum','Orbit','Pulse','Nova'][idx],next,progress}}
export function OverviewPage({user,wallet,offers,config,entries,onNavigate}:{user:User;wallet:Wallet;offers:EarnItem[];config:PlatformConfig;entries:LedgerEntry[];onNavigate:(p:string)=>void}){
 const m=metrics(entries), l=level(wallet.lifetimeEarnedPoints), top=[...offers].sort((a,b)=>b.reward-a.reward).slice(0,3);
 return <div className="page-stack">
  <section className="dashboard-hero"><div className="hero-glow"/><div className="hero-copy"><span className="kicker"><Sparkles size={12}/> GOOD TO SEE YOU, {user.username.toUpperCase()}</span><h1>Keep your <em>momentum.</em></h1><p>There are {offers.length||0} live opportunities in your current inventory. Pick a rhythm and keep building your balance.</p><div className="hero-actions"><button className="primary-button" onClick={()=>onNavigate('/earn')}>Open Earn Hub <ArrowRight size={16}/></button><button className="secondary-button" onClick={()=>onNavigate('/wallet')}>View wallet</button></div></div><div className="hero-balance"><span>AVAILABLE</span><strong>{points(wallet.availablePoints)}</strong><small>KIVORA POINTS</small><div className="hero-usd">≈ ${usdFromPoints(wallet.availablePoints,config.pointsPerUsdDisplay).toFixed(2)} display reference</div><div className="balance-track"><i style={{width:`${Math.min(100,Math.max(5,wallet.availablePoints/config.withdrawalMinPoints*100))}%`}}/></div><div className="balance-foot"><span>Min. payout {points(config.withdrawalMinPoints)} pts</span><button onClick={()=>onNavigate('/withdraw')}>Cash out <ChevronRight size={14}/></button></div></div></section>
  <div className="stats-grid"><StatCard label="Lifetime earned" value={`${points(wallet.lifetimeEarnedPoints)} pts`} hint="Confirmed provider rewards" icon={<BadgeDollarSign size={18}/>} tone="cyan"/><StatCard label="Daily rhythm" value={`${m.todayRewards} actions`} hint={`${m.streak}-day streak`} icon={<Flame size={18}/>} tone="amber"/><StatCard label="Pending" value={`${points(wallet.pendingPoints)} pts`} hint="Awaiting settlement" icon={<CircleDollarSign size={18}/>} tone="violet"/><StatCard label="Level" value={l.name} hint={l.next?`${points(l.next-wallet.lifetimeEarnedPoints)} pts to next level`:'Top tier'} icon={<Trophy size={18}/>} tone="green"/></div>
  <section className="dashboard-columns"><div className="main-column"><div className="section-heading"><div><span className="kicker">RECOMMENDED</span><h2>Start with these</h2><p>Sorted by the currently displayed provider reward.</p></div><button className="text-button" onClick={()=>onNavigate('/earn')}>See all <ChevronRight size={15}/></button></div><div className="offer-grid">{top.map(o=><OfferCard key={`${o.category}-${o.id}`} item={o} onOpen={()=>onNavigate('/earn')}/>) }{!top.length&&<div className="empty-state"><Gift size={26}/><h3>Your live inventory is loading</h3><p>Once BitcoTasks approves Kivora, available opportunities will appear here.</p></div>}</div></div><aside className="side-column"><div className="side-panel level-panel"><div className="panel-top"><div><span className="kicker">PROGRESS</span><h3>{l.name} level</h3></div><div className="level-badge">{l.name.slice(0,1)}</div></div><div className="level-track"><i style={{width:`${l.progress}%`}}/></div><div className="level-foot"><span>{points(wallet.lifetimeEarnedPoints)} pts earned</span><span>{l.next?points(l.next)+' next':'MAX'}</span></div></div><div className="side-panel"><div className="panel-top"><div><span className="kicker">RECENT ACTIVITY</span><h3>Your ledger</h3></div><button className="text-button" onClick={()=>onNavigate('/activity')}>View <ChevronRight size={14}/></button></div><ActivityFeed entries={entries}/></div><div className="side-panel goal-panel"><div className="goal-art"><CalendarDays size={18}/></div><div><span className="kicker">DAILY GOAL</span><h3>{Math.min(3,m.todayRewards)} of 3 verified actions</h3><p>Keep your rhythm today. Goals are progress signals, not guaranteed bonus payouts.</p></div></div></aside></section>
  <section className="trust-strip"><div><ShieldCheck size={17}/><strong>Reward integrity</strong><span>Credits are accepted only after provider verification.</span></div><div><WalletCards size={17}/><strong>Controlled cashout</strong><span>Withdrawals pass through a manual review queue.</span></div><div><Gift size={17}/><strong>Points first</strong><span>Blockchain payouts happen only after your request.</span></div></section>
 </div>;
}
