import { ArrowDownToLine, CheckCircle2, CircleHelp, Coins, History, ShieldCheck } from 'lucide-react';
import type { PlatformConfig, Wallet, Withdrawal } from '../lib/types';
import { maskAddress, points, shortDate, usdFromPoints } from '../lib/format';
export function WalletPage({wallet,withdrawals,config,onNavigate}:{wallet:Wallet;withdrawals:Withdrawal[];config:PlatformConfig;onNavigate:(p:string)=>void}){
 return <div className="page-stack"><section className="wallet-hero"><div><span className="kicker">KIVORA WALLET</span><h1>Your points, clearly accounted for.</h1><p>Internal Kivora Points are the accounting layer. Crypto is only sent after a withdrawal passes manual review.</p><div className="wallet-big"><strong>{points(wallet.availablePoints)}</strong><span>available points</span></div><div className="wallet-usd">Display reference ≈ ${usdFromPoints(wallet.availablePoints,config.pointsPerUsdDisplay).toFixed(2)}</div></div><div className="wallet-side"><div className="wallet-side-stat"><small>PENDING</small><strong>{points(wallet.pendingPoints)}</strong><span>points settling</span></div><div className="wallet-side-stat"><small>WITHDRAWN</small><strong>{points(wallet.lifetimeWithdrawnPoints)}</strong><span>points paid</span></div><button className="primary-button" onClick={()=>onNavigate('/withdraw')}><ArrowDownToLine size={16}/> Request payout</button></div></section>
 <div className="wallet-notice"><ShieldCheck size={18}/><div><strong>No private keys are stored.</strong><span>Your Kivora balance is an internal rewards ledger; external crypto wallets are used only when you submit a payout destination.</span></div></div>{wallet.debtPoints>0&&<div className="wallet-notice debt"><ShieldCheck size={18}/><div><strong>Settlement balance: {points(wallet.debtPoints)} pts</strong><span>A provider reversal exceeded the available balance. Withdrawals stay locked until that settlement balance is cleared by future verified rewards or an admin adjustment.</span></div></div> }
 <section><div className="section-heading"><div><span className="kicker">PAYOUT HISTORY</span><h2>Recent withdrawals</h2></div><button className="text-button" onClick={()=>onNavigate('/activity')}>View ledger <History size={15}/></button></div><div className="table-card"><div className="table-scroll"><table><thead><tr><th>Date</th><th>Asset</th><th>Destination</th><th>Points</th><th>Status</th></tr></thead><tbody>{withdrawals.map(w=><tr key={w.id}><td>{shortDate(w.createdAt)}</td><td><strong>{w.asset}</strong><small>{w.network}</small></td><td><code>{maskAddress(w.destination)}</code></td><td>{points(w.amountPoints)}</td><td><span className={`status ${w.status}`}>{w.status}</span></td></tr>)}{!withdrawals.length&&<tr><td colSpan={5} className="table-empty">No payout requests yet.</td></tr>}</tbody></table></div></div></section>
 <section className="payout-methods"><div className="method-heading"><span className="kicker">SUPPORTED DESTINATIONS</span><h2>Choose the network that matches your wallet.</h2></div><div className="method-pills">{config.supportedPayouts.map(x=><div key={`${x.asset}-${x.network}`}><Coins size={15}/><strong>{x.asset}</strong><span>{x.network}</span></div>)}</div><div className="small-note"><CircleHelp size={14}/> Minimum withdrawal: {points(config.withdrawalMinPoints)} points. Payouts are reviewed manually.</div></section></div>;
}
