import { ArrowDownToLine, CircleHelp, Coins, History, ShieldCheck, WalletCards } from 'lucide-react';
import type { PlatformConfig, Wallet, Withdrawal } from '../lib/types';
import { maskAddress, points, shortDate, usdFromPoints } from '../lib/format';

function level(pointsEarned: number) {
  const levels = [0, 1000, 5000, 15000, 40000, 100000];
  let index = 0;
  for (let i = 0; i < levels.length; i += 1) if (pointsEarned >= levels[i]) index = i;
  return { name: ['Newcomer', 'Spark', 'Momentum', 'Orbit', 'Pulse', 'Nova'][index], next: levels[index + 1] ?? null, progress: levels[index + 1] ? Math.min(100, ((pointsEarned - levels[index]) / (levels[index + 1] - levels[index])) * 100) : 100 };
}

export function WalletPage({ wallet, withdrawals, config, onNavigate }: { wallet: Wallet; withdrawals: Withdrawal[]; config: PlatformConfig; onNavigate: (p: string) => void }) {
  const currentLevel = level(wallet.lifetimeEarnedPoints);
  return <div className="page-stack scene-page vault-page">
    <section className="scene-hero vault-hero">
      <div className="scene-hero-copy"><span className="scene-eyebrow"><WalletCards size={12} /> VAULT</span><h1>Everything is represented in Kivora's <em>internal ledger.</em></h1><p>Points are the accounting layer. External crypto is only sent after a withdrawal passes manual review and treasury controls.</p><div className="vault-balance-display"><strong>{points(wallet.availablePoints)} KP</strong><span>${usdFromPoints(wallet.availablePoints, config.pointsPerUsdDisplay).toFixed(2)} display reference</span></div></div>
      <div className="vault-control-card"><div className="scene-card-top"><span>AVAILABLE BALANCE</span><WalletCards size={15} /></div><strong>{points(wallet.availablePoints)}</strong><small>KIVORA POINTS</small><div className="scene-progress"><i style={{ width: `${Math.min(100, Math.max(5, wallet.availablePoints / config.withdrawalMinPoints * 100))}%` }} /></div><div className="vault-control-foot"><span>Minimum payout {points(config.withdrawalMinPoints)} KP</span><button className="primary-button compact" onClick={() => onNavigate('/withdraw')}><ArrowDownToLine size={14} /> Request payout</button></div></div>
    </section>
    <section className="scene-panel vault-ledger-panel"><div className="scene-section-heading"><div><span className="scene-eyebrow">BALANCE ZONES</span><h2>Know where every point sits.</h2></div><span className="scene-readonly">LIVE ACCOUNT VIEW</span></div><div className="vault-zone-grid"><div className="vault-zone available"><small>AVAILABLE</small><strong>{points(wallet.availablePoints)}</strong><span>ready for a request</span></div><div className="vault-zone pending"><small>PENDING VERIFICATION</small><strong>{points(wallet.pendingPoints)}</strong><span>awaiting provider settlement</span></div><div className="vault-zone reserved"><small>RESERVED FOR PAYOUT</small><strong>{points(wallet.withdrawalReservedPoints)}</strong><span>held for manual review</span></div><div className="vault-zone lifetime"><small>LIFETIME WITHDRAWN</small><strong>{points(wallet.lifetimeWithdrawnPoints)}</strong><span>paid points to date</span></div></div></section>
    <div className="wallet-notice"><ShieldCheck size={18} /><div><strong>No private keys are stored.</strong><span>Your Kivora balance is an internal rewards ledger; external crypto wallets are used only when you submit a payout destination.</span></div></div>
    {wallet.debtPoints > 0 && <div className="wallet-notice debt"><ShieldCheck size={18} /><div><strong>Settlement balance: {points(wallet.debtPoints)} KP</strong><span>A provider reversal exceeded the available balance. Withdrawals stay locked until that settlement balance is cleared.</span></div></div>}
    <section className="scene-panel settlement-note"><div><span className="scene-eyebrow">SETTLEMENT · ONE RAIL</span><h2>{config.payoutAsset} · {config.payoutNetwork}</h2><p>The payout asset and network match the publisher settlement rail. The app does not custody private keys.</p></div><button className="secondary-button" onClick={() => onNavigate('/withdraw')}>Open Settlement Terminal <ArrowDownToLine size={15} /></button></section>
    <section><div className="scene-section-heading"><div><span className="scene-eyebrow"><History size={12} /> PAYOUT HISTORY</span><h2>Manual requests</h2></div><button className="text-button" onClick={() => onNavigate('/activity')}>View chronicle <History size={15} /></button></div><div className="table-card"><div className="table-scroll"><table><thead><tr><th>Date</th><th>Asset</th><th>Destination</th><th>Points</th><th>Status</th></tr></thead><tbody>{withdrawals.map((withdrawal) => <tr key={withdrawal.id}><td>{shortDate(withdrawal.createdAt)}</td><td><strong>{withdrawal.asset}</strong><small>{withdrawal.network}</small></td><td><code>{maskAddress(withdrawal.destination)}</code></td><td>{points(withdrawal.amountPoints)}</td><td><span className={`status ${withdrawal.status}`}>{withdrawal.status}</span></td></tr>)}{!withdrawals.length && <tr><td colSpan={5} className="table-empty">No payout requests yet.</td></tr>}</tbody></table></div></div></section>
    <section className="payout-methods"><div className="method-heading"><span className="scene-eyebrow">SUPPORTED DESTINATIONS</span><h2>Fixed publisher rail</h2></div><div className="method-pills">{config.supportedPayouts.map((method) => <div key={`${method.asset}-${method.network}`}><Coins size={15} /><strong>{method.asset}</strong><span>{method.network}</span></div>)}</div><div className="small-note"><CircleHelp size={14} /> Minimum withdrawal: {points(config.withdrawalMinPoints)} KP. Payouts are reviewed manually.</div></section>
  </div>;
}