import { AlertTriangle, ArrowDownToLine, CheckCircle2, ShieldCheck } from 'lucide-react';
import { FormEvent, useMemo, useState } from 'react';
import type { PlatformConfig, Wallet } from '../lib/types';
import { points } from '../lib/format';
function validateDestination(network:string,value:string){const v=value.trim();if(network==='Base')return /^0x[a-fA-F0-9]{40}$/.test(v);if(network==='Solana')return /^[1-9A-HJ-NP-Za-km-z]{32,44}$/.test(v);if(network==='Bitcoin')return /^(bc1|[13])[a-zA-HJ-NP-Z0-9]{20,90}$/i.test(v);if(network==='Litecoin')return /^(ltc1|[LM3])[a-zA-HJ-NP-Z0-9]{20,90}$/i.test(v);return v.length>=12&&v.length<=256;}
export function WithdrawPage({wallet,config,onSubmit,onNavigate}:{wallet:Wallet;config:PlatformConfig;onSubmit:(p:any)=>Promise<void>;onNavigate:(p:string)=>void}){
 const [amount,setAmount]=useState('');const [destination,setDestination]=useState('');const [assetIndex,setAssetIndex]=useState(0);const [status,setStatus]=useState('');const [busy,setBusy]=useState(false);const selected=config.supportedPayouts[assetIndex];
 const can=useMemo(()=>{const n=Number(amount);return Number.isFinite(n)&&n>=config.withdrawalMinPoints&&n<=wallet.availablePoints&&validateDestination(selected?.network??'',destination)},[amount,wallet.availablePoints,config.withdrawalMinPoints,selected,destination]);
 const submit=async(e:FormEvent)=>{e.preventDefault();setStatus('');const n=Number(amount);if(n<config.withdrawalMinPoints)return setStatus(`Minimum withdrawal is ${points(config.withdrawalMinPoints)} points.`);if(n>wallet.availablePoints)return setStatus('You do not have enough available points.');if(!validateDestination(selected.network,destination))return setStatus(`The ${selected.network} address format does not look valid. Check it carefully before submitting.`);setBusy(true);try{await onSubmit({amountPoints:n,asset:selected.asset,network:selected.network,destination:destination.trim()});setStatus('Withdrawal submitted for manual review.');setAmount('');setDestination('')}catch(err){setStatus(err instanceof Error?err.message:'Could not submit withdrawal.')}finally{setBusy(false)}};
 return <div className="page-stack narrow"><section className="section-heading page-title"><div><span className="kicker"><ArrowDownToLine size={12}/> CASHOUT</span><h1>Request a payout</h1><p>Use a destination you control. Requests reserve points immediately and remain pending until reviewed.</p></div></section><div className="withdraw-layout"><form className="form-card" onSubmit={submit}><div className="form-balance"><span>Available</span><strong>{points(wallet.availablePoints)} pts</strong></div><label>Asset & network<select value={assetIndex} onChange={e=>setAssetIndex(Number(e.target.value))}>{config.supportedPayouts.map((x,i)=><option key={`${x.asset}-${x.network}`} value={i}>{x.asset} · {x.network}</option>)}</select></label><label>Amount<div className="input-with-suffix"><input value={amount} onChange={e=>setAmount(e.target.value)} inputMode="decimal" placeholder={`${config.withdrawalMinPoints}`}/><span>pts</span></div></label><div className="quick-amounts">{[.25,.5,1].map(p=><button type="button" key={p} onClick={()=>setAmount(String(Math.floor(wallet.availablePoints*p)))}>{Math.round(p*100)}%</button>)}</div><label>Destination address<input value={destination} onChange={e=>setDestination(e.target.value)} placeholder={selected.network==='Base'?'0x…':selected.network==='Solana'?'Solana address':`${selected.network} address`} autoComplete="off"/></label><div className="withdraw-security"><ShieldCheck size={18}/><div><strong>Review before sending</strong><span>Wallet networks are not interchangeable. Kivora will not reverse a blockchain payment sent to an incorrect destination.</span></div></div>{status&&<div className={`notice ${status.includes('submitted')?'success':'error'}`}>{status.includes('submitted')?<CheckCircle2 size={16}/>:<AlertTriangle size={16}/>}<span>{status}</span></div>}<div className="form-actions"><button type="button" className="secondary-button" onClick={()=>onNavigate('/wallet')}>Cancel</button><button className="primary-button" disabled={!can||busy}>{busy?'Submitting…':`Request ${points(Number(amount)||0)} pts`}</button></div></form><aside className="withdraw-side"><div><span className="kicker">HOW IT MOVES</span><h3>Three gates before a payout leaves Kivora.</h3></div><div className="flow-step"><b>01</b><div><strong>Reserve</strong><span>Your points move from available to pending.</span></div></div><div className="flow-step"><b>02</b><div><strong>Review</strong><span>An admin verifies amount, destination and account history.</span></div></div><div className="flow-step"><b>03</b><div><strong>Broadcast</strong><span>The manual crypto transfer is recorded with its transaction hash.</span></div></div></aside></div></div>;
}
