import { requireSupabase, getSession } from './supabase';
import { withMutationGate } from './mutationGate';
import { assertBattleResult, assertOpenedCards } from '../core/runtimeGuards';
import type { BattleResult, CardRecord, DeckSlot, DeckValidation, DepositRecord, FormationSnapshot, MarketListing, MissionRecord, OpenedCard, Pack, PvpOpponent, ProfileRecord, PlayerCardRecord, PlayerProgressRecord, RaidRun, SocialActionResult, SocialClanData, SocialConversationData, SocialFriendData, SocialMessageData, SocialSearchData, ShopItem, ShopOrder, SeasonPass, SeasonProgress, SeasonRanking, TreasuryWallet, WalletRecord, WithdrawalRequest, WorldBoss, BossEncounter, LoreEntry, SeasonTier } from '../types/api';

const clean = <T>(value: T): T => value;
let referenceCounter = 0;
const ref = (prefix:string) => `mobile-${prefix}-${Date.now()}-${++referenceCounter}`;

export class VexforgeRepository {
  private client() { return requireSupabase(); }
  private async playerId() {
    const session = await getSession();
    if (!session) throw new Error('Inicia sesión para acceder a los sistemas conectados.');
    const { data, error } = await this.client().from('players').select('id').eq('auth_user_id', session.user.id).maybeSingle();
    if (error) throw error;
    if (!data?.id) throw new Error('No existe un perfil VEXFORGE asociado a esta sesión.');
    return String(data.id);
  }
  async session() { return getSession(); }
  async signIn(email:string,password:string) { const { data, error } = await this.client().auth.signInWithPassword({email,password}); if(error) throw error; return data; }
  async signUp(email:string,password:string) { const { data, error } = await this.client().auth.signUp({email,password}); if(error) throw error; return data; }
  async signOut() { const { error } = await this.client().auth.signOut(); if(error) throw error; }
  async profile():Promise<ProfileRecord|null>{ const id=await this.playerId(); const {data,error}=await this.client().from('players').select('*').eq('id',id).maybeSingle(); if(error) throw error; return data as ProfileRecord|null; }
  async progress():Promise<PlayerProgressRecord|null>{ const id=await this.playerId(); await this.rpc('sync_player_energy',{}).catch(()=>null); const {data,error}=await this.client().from('player_progress').select('level,xp,xp_to_next,energy,max_energy,tutorial_step,starter_region,updated_at').eq('player_id',id).maybeSingle(); if(error) throw error; return data as PlayerProgressRecord|null; }
  async wallet():Promise<WalletRecord|null>{ const id=await this.playerId(); const {data,error}=await this.client().from('player_wallet').select('vex_ingame,vex_tradeable,reserved_ingame,reserved_tradeable').eq('player_id',id).maybeSingle(); if(error) throw error; return data as WalletRecord|null; }
  async stats(){ const id=await this.playerId(); return this.rpc('get_player_stats',{p_player_id:id}); }
  async rank(){ const id=await this.playerId(); return this.rpc('get_player_rank',{p_player_id:id}); }
  async cards(limit=48,offset=0):Promise<CardRecord[]>{ const end=offset+Math.max(1,Math.min(limit,64))-1; const {data,error}=await this.client().from('cards').select('*').eq('active',true).order('code',{ascending:true}).range(offset,end); if(error) throw error; return (data??[]) as CardRecord[]; }
  async collection(limit=128):Promise<PlayerCardRecord[]>{ const id=await this.playerId(); const {data,error}=await this.client().from('player_cards').select('id,card_id,quantity,locked,listed,source_tracking,created_at,cards(*)').eq('player_id',id).order('created_at',{ascending:true}).limit(limit); if(error) throw error; return (data??[]).map((row:any)=>({...row,card:row.cards ?? null})) as PlayerCardRecord[]; }
  async deck():Promise<DeckSlot[]>{ const id=await this.playerId(); const {data,error}=await this.client().from('player_deck').select('slot_number,card_id,is_champion,cards!inner(code,name,rarity,faction,power,image_url)').eq('player_id',id).order('slot_number',{ascending:true}); if(error) throw error; return (data??[]).map((row:any)=>{const c=Array.isArray(row.cards)?row.cards[0]:row.cards; return {slot_number:Number(row.slot_number),card_id:String(row.card_id??c?.id??''),is_champion:Boolean(row.is_champion),code:c?.code,name:c?.name,rarity:c?.rarity,faction:c?.faction,power:Number(c?.power??0),image_url:c?.image_url??null};}).filter(x=>x.card_id) as DeckSlot[]; }
  async validateDeck(cardIds:string[]):Promise<DeckValidation>{ return this.rpc('validate_deck',{p_card_ids:cardIds}); }
  async saveDeck(cardIds:string[]){ return withMutationGate(`deck:save:${cardIds.join(',')}`, async()=>this.rpc('save_deck',{p_card_ids:cardIds})); }
  async storeFormation(matchId:string,formation:FormationSnapshot){ return withMutationGate(`formation:${matchId}`, async()=>this.rpc('vexforge_pvp_store_formation',{p_match_id:matchId,p_formation:formation})); }
  async pvpOpponents(limit=8):Promise<PvpOpponent[]>{ const rows=await this.rpc('get_pvp_opponents',{p_limit:Math.max(1,Math.min(limit,16))}); return (rows??[]) as PvpOpponent[]; }
  async resolveBattle(opponentId:string,idempotencyKey:string):Promise<BattleResult>{ return withMutationGate(`battle:resolve:${opponentId}:${idempotencyKey}`, async()=>{ const id=await this.playerId(); const result=await this.rpc('vexforge_battle_resolve',{p_challenger_id:id,p_opponent_id:opponentId,p_idempotency_key:idempotencyKey}); return assertBattleResult(result); }); }
  async forfeitBattle(opponentId:string,idempotencyKey:string){ return withMutationGate(`battle:forfeit:${opponentId}:${idempotencyKey}`, async()=>this.rpc('vexforge_pvp_forfeit',{p_opponent_id:opponentId,p_idempotency_key:idempotencyKey})); }
  async missions():Promise<MissionRecord[]>{ const {data,error}=await this.client().from('missions').select('*').eq('active',true).eq('system_locked',false).eq('production_ready',true).order('mission_order',{ascending:true}); if(error) throw error; return (data??[]) as MissionRecord[]; }
  async executeMission(missionId:string){ return withMutationGate(`mission:${missionId}`, async()=>{ const id=await this.playerId(); const run=await this.rpc('execute_mission',{p_player:id,p_mission:missionId}); if((run as any)?.success===false) throw new Error((run as any)?.reason??'Misión rechazada.'); if((run as any)?.run_id){ const claim=await this.rpc('claim_mission_reward',{p_mission_run_id:(run as any).run_id,p_player_id:id,p_reference_id:`mission:${(run as any).run_id}`}); if((claim as any)?.success===false && (claim as any)?.ok===false) throw new Error((claim as any)?.reason??'No se pudo liquidar la recompensa.'); } return run; }); }
  async dailyQuests(){ const id=await this.playerId(); const {data,error}=await this.client().from('player_daily_quests').select('id,quest_id,assigned_date,status,progress,completed_at,claimed_at,daily_quests(id,quest_key,title,description,quest_type,target_count,reward_vex_ingame,reward_xp)').eq('player_id',id).order('assigned_date',{ascending:false}); if(error) throw error; return data??[]; }
  async claimDailyQuest(assignmentId:string){ return withMutationGate(`daily:claim:${assignmentId}`, async()=>this.rpc('claim_daily_quest',{p_quest_assignment_id:assignmentId})); }
  async world():Promise<WorldSnapshotShape>{
    const [bossesR,raidsR,loreR,seasonsR] = await Promise.all([
      this.client().from('world_bosses').select('id,boss_code,name,region_id,tier,power_level,hp,reward_pool,active,metadata,created_at,image_url').eq('active',true).order('tier',{ascending:true}).limit(50),
      this.client().from('raid_runs').select('id,raid_code,region_id,status,started_at,ended_at,metadata,created_at').in('status',['pending','active']).order('created_at',{ascending:false}).limit(50),
      this.client().from('lore_codex').select('id,entry_code,title,content,category,related_entity,metadata,created_at').order('category',{ascending:true}).order('title',{ascending:true}).limit(100),
      this.client().from('season_passes').select('id,name,season_number,start_at,end_at,active,metadata').eq('active',true).order('season_number',{ascending:false}).limit(1),
    ]);
    if(bossesR.error) throw bossesR.error; if(raidsR.error) throw raidsR.error; if(loreR.error) throw loreR.error; if(seasonsR.error) throw seasonsR.error;
    const season=(seasonsR.data??[])[0] as SeasonPass|undefined; const id=await this.playerId().catch(()=>null);
    const [tiers,encounters,progress,rankings,myRaid] = await Promise.all([
      season ? this.client().from('season_pass_tiers').select('tier_level,xp_required,is_premium,reward_json').eq('season_pass_id',season.id).order('tier_level',{ascending:true}).limit(200) : Promise.resolve({data:[],error:null}),
      id ? this.client().from('world_boss_encounters').select('id,world_boss_id,player_id,damage,reward_json,status,created_at').eq('player_id',id).order('created_at',{ascending:false}).limit(50) : Promise.resolve({data:[],error:null}),
      id ? this.rpc('get_season_progress',{p_player_id:id}).catch(()=>null) : Promise.resolve(null),
      season?.metadata && typeof season.metadata === 'object' && typeof (season.metadata as any).season_key === 'string' ? this.client().from('season_rankings').select('rank_position,mmr,wins,losses,draws,season_key,player_id').eq('season_key',(season.metadata as any).season_key).order('rank_position',{ascending:true}).limit(100) : Promise.resolve({data:[],error:null}),
      id ? this.client().from('raid_participants').select('raid_run_id').eq('player_id',id).limit(100) : Promise.resolve({data:[],error:null}),
    ]);
    if(rankings.error) throw rankings.error;
    const names = (rankings.data??[]).length ? await this.rpc('get_public_player_names',{p_player_ids:(rankings.data??[]).map((x:any)=>x.player_id)}).catch(()=>[]) : [];
    const map=new Map((names??[]).map((x:any)=>[x.id,x.display_name]));
    const seasonTiers=(tiers.data??[]).map((row:any)=>({tier:Number(row.tier_level??0),xp_required:Number(row.xp_required??0),is_premium:Boolean(row.is_premium),reward:(row.reward_json??{}),unlocked:false,claimed:false})) as SeasonTier[];
    return {bosses:(bossesR.data??[]) as WorldBoss[],raids:(raidsR.data??[]) as RaidRun[],lore:(loreR.data??[]) as LoreEntry[],season:season??null,tiers:seasonTiers,encounters:(encounters.data??[]) as BossEncounter[],seasonProgress:progress as SeasonProgress|null,rankings:(rankings.data??[]).map((x:any)=>({...x,display_name:map.get(x.player_id)??x.player_id?.slice(0,8)})) as SeasonRanking[],myRaidIds:(myRaid.data??[]).map((x:any)=>String(x.raid_run_id))};
  }
  async joinRaid(raidId:string){ if(!raidId.trim()) throw new Error('Raid inválido.'); return withMutationGate(`raid:join:${raidId}`, async()=>this.rpc('vexforge_join_raid',{p_raid_run_id:raidId})); }
  async contributeRaid(_raidId:string,_contribution:number){ throw new Error('La contribución directa de raid está bloqueada en producción. VEXFORGE requiere un Battle Run v6 validado y su settlement autoritativo; este cliente no inventa daño ni progreso.'); }
  async claimSeasonTier(tier:number){ if(!Number.isInteger(tier)||tier<0||tier>1000) throw new Error('Tier de temporada inválido.'); return withMutationGate(`season:claim:${tier}`, async()=>{ const id=await this.playerId(); return this.rpc('claim_season_pass_reward',{p_player_id:id,p_tier:tier}); }); }
  async economyStats(){ return this.rpc('vexforge_get_my_economy_stats',{}); }
  async market():Promise<MarketListing[]>{ const {data,error}=await this.client().from('market_listings').select('id,reference_id,player_id,player_card_id,price,fee,status,expires_at,locked,player_cards(card_id,cards(name,rarity,image_url))').eq('status','active').order('created_at',{ascending:false}).limit(80); if(error) throw error; return (data??[]).map((row:any)=>{const pc=Array.isArray(row.player_cards)?row.player_cards[0]:row.player_cards; const c=pc?.cards; const card=Array.isArray(c)?c[0]:c; return {...row,card_id:pc?.card_id??null,card_name:card?.name??null,card_rarity:card?.rarity??null,image_url:card?.image_url??null};}); }
  async marketOwned():Promise<PlayerCardRecord[]>{ return this.collection(128); }
  async createListing(playerCardId:string,price:number){ return withMutationGate(`listing:create:${playerCardId}`, async()=>{ const id=await this.playerId(); if(!Number.isFinite(price)||price<=0) throw new Error('El precio debe ser mayor que 0.'); return this.rpc('create_listing',{p_player_id:id,p_player_card_id:playerCardId,p_price:price,p_reference_id:ref('listing'),p_fee:0,p_expires_at:null,p_metadata:{source:'mobile'} }); }); }
  async buyListing(listingId:string){ if(!listingId.trim()) throw new Error('Listado inválido.'); return withMutationGate(`listing:buy:${listingId}`, async()=>{ const id=await this.playerId(); return this.rpc('buy_listing',{p_buyer_id:id,p_listing_id:listingId,p_reference_id:ref('buy'),p_metadata:{source:'mobile'}}); }); }
  async cancelListing(listingId:string){ if(!listingId.trim()) throw new Error('Listado inválido.'); return withMutationGate(`listing:cancel:${listingId}`, async()=>{ const id=await this.playerId(); return this.rpc('cancel_listing',{p_player_id:id,p_listing_id:listingId,p_reference_id:ref('cancel'),p_metadata:{source:'mobile'}}); }); }
  async treasury():Promise<TreasuryWallet[]>{ const {data,error}=await this.client().from('vexforge_treasury').select('chain,token_symbol,wallet_address,token_standard').eq('active',true).eq('purpose','project_treasury').order('chain',{ascending:true}); if(error) throw error; return (data??[]) as TreasuryWallet[]; }
  async deposits():Promise<DepositRecord[]>{ const rows=await this.rpc('vexforge_get_my_deposits',{}); return Array.isArray(rows)?rows as DepositRecord[]:[]; }
  async submitDeposit(amountUsdt:number,chain:string,tokenSymbol:string,txHash:string,payerWalletAddress:string){ if(!Number.isFinite(amountUsdt)||amountUsdt<=0||!chain.trim()||!tokenSymbol.trim()||!txHash.trim()||!payerWalletAddress.trim()) throw new Error('Datos de depósito inválidos.'); return withMutationGate(`deposit:${txHash.trim().toLowerCase()}`, async()=>this.rpc('vexforge_submit_deposit',{p_amount_usdt:amountUsdt,p_chain:chain,p_token_symbol:tokenSymbol,p_tx_hash:txHash.trim(),p_payer_wallet_address:payerWalletAddress.trim()})); }
  async withdrawals():Promise<WithdrawalRequest[]>{ const id=await this.playerId(); const {data,error}=await this.client().from('vexforge_withdrawal_requests_official').select('id,player_id,tradeable_amount,usdt_gross,fee_usdt,usdt_net,status,rejected_reason,payout_tx_hash,created_at,processed_at').eq('player_id',id).order('created_at',{ascending:false}); if(error) throw error; return (data??[]) as WithdrawalRequest[]; }
  async requestWithdrawal(amount:number){ if(!Number.isFinite(amount)||amount<=0) throw new Error('Cantidad de retiro inválida.'); return withMutationGate(`withdrawal:${amount}`, async()=>{ const id=await this.playerId(); return this.rpc('vexforge_request_withdrawal',{p_player_id:id,p_tradeable_amount:amount}); }); }
  async referralSummary(){ const id=await this.playerId(); const me=await this.profile(); const {data,error}=await this.client().from('vexforge_referrals').select('id,referred_display_name,status,reward_granted,first_pack_rewarded,created_at').eq('referrer_auth_id',(await getSession())!.user.id).order('created_at',{ascending:false}).limit(50); if(error) throw error; return {code:(me as any)?.referral_code??null,referrals:data??[]}; }
  async packs():Promise<Pack[]>{ const {data,error}=await this.client().from('vexforge_pack_catalog').select('pack_key,pack_name,price_vex,price_usdt,card_count,notes,metadata').eq('active',true).order('price_vex',{ascending:true}); if(error) throw error; return (data??[]).map((x:any)=>({...x,price_vex:Number(x.price_vex??0),price_usdt:Number(x.price_usdt??0),card_count:Number(x.card_count??0),rarity_weights:x.metadata?.rarity_weights??null})); }
  async packBalance(){ const id=await this.playerId(); const {data,error}=await this.client().from('player_wallet').select('vex_tradeable').eq('player_id',id).maybeSingle(); if(error) throw error; return Number(data?.vex_tradeable??0); }
  async buyPack(packKey:string){ if(!packKey.trim()) throw new Error('Pack inválido.'); return withMutationGate(`pack:buy:${packKey}`, async()=>this.rpc('vexforge_buy_pack_with_vex',{p_pack_key:packKey})); }
  async openPack(orderId:string):Promise<{ok:boolean;cards?:OpenedCard[];reason?:string}>{ return withMutationGate(`pack:open:${orderId}`, async()=>{ const result=await this.rpc('vexforge_open_pack',{p_order_id:orderId}); const cards=Array.isArray((result as any)?.cards)?assertOpenedCards((result as any).cards):undefined; return {ok:Boolean((result as any)?.ok),cards,reason:(result as any)?.reason}; }); }
  async packHistory(){ const id=await this.playerId(); const {data,error}=await this.client().from('vexforge_pack_orders').select('id,pack_key,price_usdt,status,payment_method,metadata,created_at').eq('player_id',id).order('created_at',{ascending:false}).limit(20); if(error) throw error; return data??[]; }
  async shop():Promise<ShopItem[]>{ const {data,error}=await this.client().from('vexforge_shop_catalog').select('id,item_key,name,description,category,price_usdt,price_vex,active,icon').eq('active',true).order('sort_order',{ascending:true}).order('price_usdt',{ascending:true}); if(error) throw error; return (data??[]) as ShopItem[]; }
  async shopOrders():Promise<ShopOrder[]>{ const rows=await this.rpc('vexforge_get_my_shop_orders',{p_limit:10}); return Array.isArray(rows)?rows as ShopOrder[]:[]; }
  async createShopOrder(itemKey:string){ if(!itemKey.trim()) throw new Error('Artículo inválido.'); return withMutationGate(`shop:create:${itemKey}`, async()=>this.rpc('vexforge_create_shop_order',{p_item_key:itemKey,p_client_reference:ref(`shop-${itemKey}`),p_payment_reference:null,p_tx_hash:null,p_payer_wallet_address:null})); }
  async submitShopPayment(orderId:string,txHash:string,payerWalletAddress:string){ if(!orderId.trim()||!txHash.trim()||!payerWalletAddress.trim()) throw new Error('Datos de pago inválidos.'); return withMutationGate(`shop:pay:${orderId}`, async()=>this.rpc('vexforge_submit_shop_order_payment',{p_order_id:orderId,p_tx_hash:txHash,p_payer_wallet_address:payerWalletAddress,p_payment_reference:null})); }
  async fusableCards(){ const id=await this.playerId(); const {data,error}=await this.client().from('player_cards').select('id,card_id,quantity,locked,listed,cards(name,rarity,fusion_enabled)').eq('player_id',id).eq('locked',false).eq('listed',false).gt('quantity',0); if(error) throw error; return data??[]; }
  async fusionPolicy(rarity:string){ const rows=await this.rpc('vexforge_fusion_policy',{p_source_rarity:rarity}); return Array.isArray(rows)?rows[0]??null:rows; }
  async fusion(sourceCardId:string,targetCardId:string){ if(!sourceCardId.trim()||!targetCardId.trim()||sourceCardId===targetCardId) throw new Error('Fuentes de fusión inválidas.'); return withMutationGate(`fusion:${sourceCardId}:${targetCardId}`, async()=>{ const id=await this.playerId(); return this.rpc('vexforge_apply_fusion',{p_player_id:id,p_source_card_id:sourceCardId,p_target_card_id:targetCardId}); }); }
  async evolve(cardId:string){ if(!cardId.trim()) throw new Error('Carta inválida.'); return withMutationGate(`evolve:${cardId}`, async()=>{ const id=await this.playerId(); return this.rpc('vexforge_evolve_card',{p_card_id:cardId,p_player_id:id}); }); }
  async socialFriends():Promise<SocialFriendData>{return this.rpc('social_list_friend_data',{});}
  async socialSearch(q:string,limit=20):Promise<SocialSearchData>{return this.rpc('social_search_players',{p_query:q,p_limit:limit});}
  async socialFriendRequest(id:string){return withMutationGate(`social:friend-request:${id}`, async()=>this.rpc('social_send_friend_request',{p_target_player_id:id})) as Promise<SocialActionResult>;}
  async socialRespond(id:string,accept:boolean){return withMutationGate(`social:friend-response:${id}:${accept?'accept':'reject'}`, async()=>this.rpc('social_respond_friend_request',{p_request_id:id,p_accept:accept})) as Promise<SocialActionResult>;}
  async socialConversations():Promise<SocialConversationData>{return this.rpc('social_list_private_conversations',{});}
  async socialMessages(id:string,limit=60):Promise<SocialMessageData>{return this.rpc('social_list_private_messages',{p_conversation_id:id,p_limit:limit});}
  async socialSendMessage(id:string,body:string){return withMutationGate(`social:private-send:${id}`, async()=>this.rpc('social_send_private_message',{p_conversation_id:id,p_body:body})) as Promise<SocialActionResult>;}
  async socialMarkRead(id:string){return withMutationGate(`social:private-read:${id}`, async()=>this.rpc('social_mark_private_read',{p_conversation_id:id})) as Promise<SocialActionResult>;}
  async socialGlobalMessages(limit=50):Promise<SocialMessageData>{return this.rpc('social_list_global_messages',{p_limit:limit});}
  async socialSendGlobal(body:string){return withMutationGate('social:global-send', async()=>this.rpc('social_send_global_message',{p_body:body})) as Promise<SocialActionResult>;}
  async socialClan():Promise<SocialClanData>{return this.rpc('social_get_clan_hall',{});}
  async socialCreateClan(name:string,description:string){return withMutationGate(`social:clan-create:${name.trim().toLowerCase()}`, async()=>this.rpc('social_create_clan',{p_name:name,p_description:description})) as Promise<SocialActionResult>;}
  async socialJoinClan(id:string){return withMutationGate(`social:clan-join:${id}`, async()=>this.rpc('social_join_clan',{p_clan_id:id})) as Promise<SocialActionResult>;}
  async socialClanMessages(limit=50):Promise<SocialMessageData>{return this.rpc('social_list_clan_messages',{p_limit:limit});}
  async socialSendClan(body:string){return withMutationGate('social:clan-send', async()=>this.rpc('social_send_clan_message',{p_body:body})) as Promise<SocialActionResult>;}
  async socialPresence(){return withMutationGate('social:presence', async()=>this.rpc('social_touch_presence',{})) as Promise<SocialActionResult>;}
  async updateSettings(patch:Record<string,unknown>){ const id=await this.playerId(); return withMutationGate(`settings:${id}`, async()=>{ const {data,error}=await this.client().from('player_settings').update(patch).eq('player_id',id).select().maybeSingle(); if(error) throw error; return data; }); }
  async tutorialStep(step:number){ const id=await this.playerId(); const target=Math.max(0,Math.min(19,Math.floor(step))); return withMutationGate(`tutorial-step:${id}:${target}`, async()=>{ const {error}=await this.client().from('player_progress').update({tutorial_step:target,updated_at:new Date().toISOString()}).eq('player_id',id).lt('tutorial_step',target); if(error) throw error; return true; }); }
  async rpc(name:string,args:Record<string,unknown>){ const {data,error}=await this.client().rpc(name,args); if(error) throw error; return clean(data); }
}
export interface WorldSnapshotShape { bosses:WorldBoss[]; raids:RaidRun[]; lore:LoreEntry[]; season:SeasonPass|null; tiers:SeasonTier[]; encounters:BossEncounter[]; seasonProgress:SeasonProgress|null; rankings:SeasonRanking[]; myRaidIds:string[]; }
export const repository = new VexforgeRepository();
