import React from 'react';
import { ScrollView, StyleSheet, Text, View } from 'react-native';
import { useRouter } from 'expo-router';
import { useQuery } from '@tanstack/react-query';
import { WorldBackdrop } from '../../src/render/WorldBackdrop';
import { RuntimeHeader } from '../../src/app/RuntimeHeader';
import { useGame } from '../../src/app/GameProvider';
import { repository } from '../../src/services/repository';
import { SUPABASE_CONFIGURED } from '../../src/services/supabase';
import { COLORS } from '../../src/core/constants';
import { RuneButton, SectionTitle, StatSeal, StatusPill, WorldObject, WorldTitle } from '../../src/render/Diegetic';
export default function Nexus(){const router=useRouter();const{quality}=useGame();const q=useQuery({queryKey:['nexus'],queryFn:async()=>{if(!SUPABASE_CONFIGURED)return null;const [p,pr,w,missions]=await Promise.all([repository.profile(),repository.progress(),repository.wallet(),repository.missions()]);return{p,pr,w,missions};},staleTime:15000});const data=q.data;return <View style={styles.root}><WorldBackdrop variant="nexus" tier={quality}/><RuntimeHeader/><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><WorldTitle kicker="FOJA · NEXUS" title="LA CITADELA ESTÁ DESPIERTA" subtitle="Aquí el juego no se detiene: tu colección alimenta la forja, la forja abre la arena, la arena empuja la progresión y el progreso vuelve al mundo."/>
<View style={styles.identity}><View style={styles.identityMain}><StatusPill label={data?'SINCRONIZADO':'MODO LAB'} accent={data?COLORS.mint:COLORS.gold}/><Text style={styles.player}>{data?.p?.display_name??'FORJADOR'}</Text><Text style={styles.meta}>NIVEL {data?.pr?.level??'—'} · {data?.p?.faction??'FACTOR NO REPORTADO'}</Text></View><View style={styles.seals}><StatSeal label="VEX" value={data?.w?.vex_ingame??'—'} accent={COLORS.goldBright}/><StatSeal label="ENERGÍA" value={`${data?.pr?.energy??'—'}/${data?.pr?.max_energy??'—'}`} accent={COLORS.mint}/></View></View>
<SectionTitle kicker="PUERTAS DEL NEXUS" title="LOS SISTEMAS ESTÁN CONECTADOS"/>
<View style={styles.grid}>{[['ARENA','COMBATE','/arena','⚔',COLORS.crimson],['ARCHIVO','CARTAS','/archive','◈',COLORS.gold],['FORJA','MAZOS','/forge','⌘','#B86A35'],['MISIONES','PVE','/missions','✦',COLORS.mint],['MUNDO','BOSS / RAID','/world','⬡','#6B8F9A'],['TESORO','ECONOMÍA','/economy','◉','#5E9FC3'],['SALÓN','SOCIAL','/social','☽','#986F86'],['RELIQUIAS','TIENDA','/store','▣','#C2934D']].map(([k,t,r,g,a])=><WorldObject key={r} accent={String(a)} onPress={()=>router.push(String(r) as never)} style={styles.portal}><Text style={[styles.portalGlyph,{color:String(a)}]}>{g}</Text><Text style={styles.portalK}>{k}</Text><Text style={styles.portalT}>{t}</Text><Text style={styles.portalArrow}>›</Text></WorldObject>)}</View>
<SectionTitle kicker="ORDEN DEL DÍA" title="EL MUNDO TE ESPERA" right={<RuneButton label="VER MISIONES" accent={COLORS.mint} onPress={()=>router.push('/missions')}/>}/>
{data?.missions?.slice(0,3).map(m=><WorldObject key={m.id} accent={String(m.difficulty??'').toLowerCase()==='elite'?COLORS.crimson:COLORS.gold} style={styles.mission}><View style={{flex:1}}><Text style={styles.missionK}>{String(m.difficulty??'NORMAL').toUpperCase()} · {m.energy_cost??0} ENERGÍA</Text><Text style={styles.missionT}>{m.name??m.code??'Misión'}</Text><Text style={styles.missionB}>XP {m.reward_xp??0} · VEX {m.reward_vex_ingame??0}</Text></View><Text style={styles.missionMark}>◆</Text></WorldObject>)}
<WorldObject accent={COLORS.arcaneBright} style={styles.lore}><Text style={styles.loreK}>PRINCIPIO DEL NEXUS</Text><Text style={styles.loreT}>“Nada existe por casualidad.”</Text><Text style={styles.loreB}>Las cartas, las facciones, los bosses, los clanes, el mercado, las temporadas y la economía pertenecen al mismo mundo. La interfaz solo revela lo que el mundo ya contiene.</Text></WorldObject>
<WorldObject accent={COLORS.gold} style={styles.actions}><RuneButton label="TUTORIAL VIVO" onPress={()=>router.push('/tutorial')} accent={COLORS.arcaneBright}/><RuneButton label="CONTROL DEL RUNTIME" onPress={()=>router.push('/meta')} accent={COLORS.gold}/></WorldObject>
</ScrollView></View>}
const styles=StyleSheet.create({root:{flex:1,backgroundColor:COLORS.void},content:{padding:15,paddingBottom:130,gap:14},identity:{borderRadius:22,borderWidth:1,borderColor:`${COLORS.gold}35`,backgroundColor:'rgba(4,4,7,.76)',padding:13,flexDirection:'row',gap:12},identityMain:{flex:1},player:{fontFamily:'Cinzel_900Black',color:COLORS.white,fontSize:22,marginTop:8},meta:{fontFamily:'Rajdhani_600SemiBold',color:COLORS.ash,fontSize:8,letterSpacing:1.1,marginTop:3},seals:{gap:6,justifyContent:'center'},grid:{gap:8},portal:{minHeight:92,position:'relative'},portalGlyph:{fontSize:22,fontWeight:'900'},portalK:{color:COLORS.goldDim,fontSize:5.5,fontWeight:'900',letterSpacing:1.6,marginTop:5},portalT:{color:COLORS.white,fontSize:13,fontWeight:'900',marginTop:2},portalArrow:{position:'absolute',right:13,top:30,color:COLORS.goldBright,fontSize:23},mission:{flexDirection:'row',alignItems:'center'},missionK:{color:COLORS.gold,fontSize:5.5,fontWeight:'900',letterSpacing:1.4},missionT:{color:COLORS.white,fontSize:12,fontWeight:'900',marginTop:3},missionB:{color:COLORS.parchment,fontSize:7,marginTop:2},missionMark:{color:COLORS.goldBright,fontSize:20},lore:{paddingVertical:20},loreK:{color:COLORS.arcaneBright,fontSize:6,fontWeight:'900',letterSpacing:1.8},loreT:{fontFamily:'Cinzel_700Bold',color:COLORS.white,fontSize:15,marginTop:7},loreB:{color:COLORS.parchment,fontSize:9,lineHeight:14,marginTop:7},actions:{gap:8}});
