import { useState } from 'react';
    import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
    import { useColors } from '@/hooks/useColors';
    import { useGame } from '@/context/GameContext';

    export default function ProfileScreen() {
    const colors = useColors();
    const { session, player, wallet, stats, syncState, authLoading, authError, signIn, signUp, signOut } = useGame();
    const [register, setRegister] = useState(false);
    const [email, setEmail] = useState('');
    const [password, setPassword] = useState('');
    const [message, setMessage] = useState<string | null>(null);
    const submit = async () => { setMessage(null); if (register) { const created = await signUp(email, password); setMessage(created ? 'Cuenta creada y sesión iniciada.' : 'Revisa tu correo para confirmar la cuenta.'); } else await signIn(email, password); };
    if (!session) return <ScrollView contentContainerStyle={[styles.auth, { backgroundColor: colors.background }]}><Text style={[styles.eyebrow, { color: colors.primary }]}>VEXFORGE / CUENTA</Text><Text style={[styles.title, { color: colors.foreground }]}>{register ? 'Crear cuenta' : 'Iniciar sesión'}</Text><Text style={[styles.copy, { color: colors.mutedForeground }]}>La cuenta se valida con Supabase. No se guarda una contraseña local.</Text><TextInput autoCapitalize="none" keyboardType="email-address" value={email} onChangeText={setEmail} placeholder="Correo electrónico" placeholderTextColor={colors.mutedForeground} style={[styles.input, { color: colors.foreground, borderColor: colors.border, backgroundColor: colors.panel }]} /><TextInput secureTextEntry value={password} onChangeText={setPassword} placeholder="Contraseña" placeholderTextColor={colors.mutedForeground} style={[styles.input, { color: colors.foreground, borderColor: colors.border, backgroundColor: colors.panel }]} /><Pressable onPress={submit} disabled={authLoading} style={[styles.button, { backgroundColor: colors.primary }]}>{authLoading ? <ActivityIndicator color={colors.background} /> : <Text style={[styles.buttonText, { color: colors.background }]}>{register ? 'CREAR CUENTA' : 'ENTRAR'}</Text>}</Pressable>{authError ? <Text style={[styles.error, { color: colors.destructive }]}>{authError}</Text> : null}{message ? <Text style={[styles.message, { color: colors.success }]}>{message}</Text> : null}<Pressable onPress={() => { setRegister(!register); setMessage(null); }}><Text style={[styles.link, { color: colors.primary }]}>{register ? 'Ya tengo una cuenta' : 'Crear una cuenta nueva'}</Text></Pressable></ScrollView>;
    return <ScrollView contentContainerStyle={[styles.screen, { backgroundColor: colors.background }]}><Text style={[styles.eyebrow, { color: colors.primary }]}>VEXFORGE / PERFIL</Text><Text style={[styles.title, { color: colors.foreground }]}>{player?.display_name ?? session.user.email ?? 'Forjador'}</Text><Text style={[styles.status, { color: colors.success }]}>● {syncState === 'connected' ? 'SINCRONIZADO CON SUPABASE' : 'ACTUALIZANDO'}</Text><View style={[styles.panel, { backgroundColor: colors.panel, borderColor: colors.border }]}><Text style={[styles.panelTitle, { color: colors.foreground }]}>Cartera real</Text><Text style={[styles.balance, { color: colors.primary }]}>{wallet?.vex_ingame ?? 0} VEX</Text><Text style={[styles.copy, { color: colors.mutedForeground }]}>Tradeable: {wallet?.vex_tradeable ?? 0} · Victorias PvP: {stats?.pvp_wins ?? 0}</Text></View><View style={[styles.panel, { backgroundColor: colors.panel, borderColor: colors.border }]}><Text style={[styles.panelTitle, { color: colors.foreground }]}>Cuenta Supabase</Text><Text style={[styles.copy, { color: colors.mutedForeground }]}>{session.user.email}</Text><Text style={[styles.copy, { color: colors.mutedForeground }]}>ID: {session.user.id.slice(0, 8)}…</Text></View><Pressable onPress={signOut} style={[styles.button, { backgroundColor: colors.panelStrong, borderColor: colors.border }]}><Text style={[styles.buttonText, { color: colors.foreground }]}>CERRAR SESIÓN</Text></Pressable></ScrollView>;
    }
    const styles = StyleSheet.create({ auth: { flexGrow: 1, padding: 24, justifyContent: 'center' }, screen: { flexGrow: 1, padding: 24, paddingTop: 54 }, eyebrow: { fontSize: 11, fontWeight: '800', letterSpacing: 2 }, title: { fontSize: 29, fontWeight: '800', marginTop: 14, marginBottom: 10 }, copy: { fontSize: 13, lineHeight: 20, marginBottom: 18 }, input: { borderWidth: 1, borderRadius: 12, padding: 14, fontSize: 15, marginTop: 12 }, button: { minHeight: 50, borderRadius: 12, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 18, marginTop: 18, borderWidth: 1 }, buttonText: { fontSize: 12, fontWeight: '800', letterSpacing: 1 }, link: { textAlign: 'center', marginTop: 20, fontWeight: '700' }, error: { marginTop: 16, lineHeight: 20 }, message: { marginTop: 16, lineHeight: 20 }, status: { fontSize: 11, fontWeight: '800', letterSpacing: 1.2, marginBottom: 24 }, panel: { borderWidth: 1, borderRadius: 18, padding: 18, marginBottom: 14 }, panelTitle: { fontSize: 15, fontWeight: '800', marginBottom: 14 }, balance: { fontSize: 32, fontWeight: '900', marginBottom: 8 } });
    