import type { EarnCategory, EarnItem } from './types';
declare global { interface Window { BitcoTasksOfferwall?: any } }
const CATEGORIES:Exclude<EarnCategory,'all'>[]=['surveys','offers','ptc','video','faucet','shortlinks','tasks','article'];
let wallPromise:Promise<any>|null=null;
async function publicConfig(){const r=await fetch('/api/public-config',{credentials:'include',cache:'no-store'});if(!r.ok)throw new Error('Provider configuration unavailable');return await r.json() as {apiKey:string;subId:string};}
function loadScript(){if(window.BitcoTasksOfferwall)return Promise.resolve();if(document.querySelector('script[data-kivora-bitcotasks-sdk]'))return wallPromise??Promise.resolve();if(wallPromise)return wallPromise;wallPromise=new Promise<void>((resolve,reject)=>{const s=document.createElement('script');s.src='https://bitcotasks.com/sdk/bitcotasks-offerwall-sdk-v1.js';s.async=true;s.dataset.kivoraBitcotasksSdk='true';s.onload=()=>resolve();s.onerror=()=>reject(new Error('BitcoTasks SDK could not be loaded'));document.head.appendChild(s)});return wallPromise;}
export async function getBitcoTasksWall(){const cfg=await publicConfig();await loadScript();if(!window.BitcoTasksOfferwall)throw new Error('BitcoTasks SDK unavailable');const wall=new window.BitcoTasksOfferwall({apiKey:cfg.apiKey,subId:cfg.subId,pagination:{enabled:true,pageSize:12}});return wrap(wall)}
function normalize(item:any,category:Exclude<EarnCategory,'all'>):EarnItem{return {id:String(item.id??crypto.randomUUID()),category,title:String(item.title??item.name??'Opportunity'),description:String(item.description??item.instructions??''),image:item.image?String(item.image):undefined,reward:Number(item.reward??0),currencyName:String(item.reward_name??item.currency_name??'Kivora Points'),url:String(item.link??item.url??''),source:'BitcoTasks',durationSeconds:item.duration?Number(item.duration):undefined,boosted:Boolean(item.boosted_campaign),requirements:item.requirements?String(item.requirements):item.requirement?String(item.requirement):undefined,available:item.available?Number(item.available):undefined,earnUpTo:item.earn_up_to?Number(item.earn_up_to):undefined,claimed:item.claimed!==undefined?Number(item.claimed):undefined,limit:item.limit!==undefined?Number(item.limit):undefined,waitSeconds:item.wait!==undefined?Number(item.wait):undefined,goals:Array.isArray(item.goals)?item.goals.map((g:any)=>({name:String(g.name??''),description:g.description?String(g.description):undefined,virtualCurrencyValue:g.virtual_currency_value?Number(g.virtual_currency_value):undefined})):undefined,raw:item};}
function wrap(wall:any){return {getOffers:async(type:Exclude<EarnCategory,'all'>,opts?:any)=>{const r=await wall.getOffers(type,opts);return (r?.items??r?.data??[]).map((x:any)=>normalize(x,type))},openOffer:(i:EarnItem)=>wall.openOffer(i.raw??i),openArticle:(i:EarnItem)=>wall.openArticle(i.raw??i),claimFaucet:(i:EarnItem)=>wall.claimFaucet(i.raw??i),openShortlink:(i:EarnItem)=>wall.openShortlink(i.raw??i),startPTC:(i:EarnItem)=>wall.startPTC(i.raw??i),startVideo:(i:EarnItem)=>wall.startVideo(i.raw??i),completeVideo:(i:EarnItem)=>wall.completeVideo(i.raw??i),submitTask:(i:EarnItem,d:any)=>wall.submitTask(i.raw??i,d)}};
export const categories=CATEGORIES;
