import fs from 'node:fs';
import path from 'node:path';
const root=process.cwd();
const failures=[];
const pkg=JSON.parse(fs.readFileSync(path.join(root,'package.json'),'utf8'));
const app=JSON.parse(fs.readFileSync(path.join(root,'app.json'),'utf8'));
const eas=JSON.parse(fs.readFileSync(path.join(root,'eas.json'),'utf8'));
if(pkg.version!=='1.10.0') failures.push(`package-version:${pkg.version}`);
if(app.expo?.version!=='1.10.0') failures.push(`app-version:${app.expo?.version}`);
if(app.expo?.runtimeVersion?.policy!=='appVersion') failures.push('runtime-version-policy-not-appVersion');
if(eas.build?.development?.channel!=='development') failures.push('development-channel');
if(eas.build?.preview?.channel!=='internal') failures.push('preview-channel');
if(eas.build?.production?.channel!=='production') failures.push('production-channel');
if(eas.build?.preview?.android?.buildType!=='apk') failures.push('preview-not-apk');
if(eas.build?.production?.android?.buildType!=='app-bundle') failures.push('production-not-aab');
const requiredDeps=['@expo-google-fonts/inter','expo-image','@shopify/react-native-skia','expo-updates'];
for(const dep of requiredDeps) if(!pkg.dependencies?.[dep]) failures.push(`runtime-dependency-not-in-dependencies:${dep}`);
const updatesText=fs.readFileSync(path.join(root,'app.json'),'utf8');
if(!updatesText.includes('vexforge-updates')) failures.push('custom-update-url-missing');
console.log(JSON.stringify({ok:!failures.length,release:pkg.version,runtimePolicy:app.expo.runtimeVersion,channels:{development:eas.build.development.channel,preview:eas.build.preview.channel,production:eas.build.production.channel},failures},null,2));
process.exitCode=failures.length?1:0;
