import fs from 'node:fs';
import path from 'node:path';
const root=process.cwd();
const failures=[];
const required=['package.json','app.json','eas.json','BUILD_MANIFEST.json','SHA256SUMS.txt','docs/ACTIVE_DOCUMENTS_1.10.md','docs/RELEASE_NOTES_1.10.0.md'];
for(const f of required) if(!fs.existsSync(path.join(root,f))) failures.push(`missing:${f}`);
const pkg=JSON.parse(fs.readFileSync(path.join(root,'package.json'),'utf8'));
const app=JSON.parse(fs.readFileSync(path.join(root,'app.json'),'utf8'));
const eas=JSON.parse(fs.readFileSync(path.join(root,'eas.json'),'utf8'));
const manifest=JSON.parse(fs.readFileSync(path.join(root,'BUILD_MANIFEST.json'),'utf8'));
if(pkg.version!=='1.10.0') failures.push('package-version');
if(app.expo?.version!=='1.10.0') failures.push('app-version');
if(app.expo?.android?.versionCode!==11) failures.push('android-version-code');
if(app.expo?.runtimeVersion?.policy!=='appVersion') failures.push('runtime-policy');
if(eas.build?.preview?.android?.buildType!=='apk') failures.push('preview-apk');
if(eas.build?.production?.android?.buildType!=='app-bundle') failures.push('production-aab');
if(manifest.release!=='1.10.0'||manifest.runtime_version_policy!=='appVersion') failures.push('manifest-release');
const sums=fs.readFileSync(path.join(root,'SHA256SUMS.txt'),'utf8').trim().split(/\r?\n/).filter(Boolean);
if(sums.length<300) failures.push(`checksum-count:${sums.length}`);
console.log(JSON.stringify({ok:!failures.length,release:pkg.version,checksumEntries:sums.length,failures},null,2));
process.exitCode=failures.length?1:0;
