-- VE-DOC-4-COLUMN-COMMENTS
-- Higiene documental de columnas del runtime de cliente (tablas leidas desde src/ via from("<tabla>")).
-- Solo metadatos: sin cambios de esquema, datos, RLS, grants, RPCs, economia autoritativa, Storage ni arte.
-- Cada descripcion se genera desde evidencia real del catalogo vivo: tipo, clave primaria,
-- referencia foranea, obligatoriedad y valor por defecto.

comment on column public.achievements.id is 'Identificador primario de la fila. tipo uuid, clave primaria, obligatoria, por defecto gen_random_uuid().';
comment on column public.achievements.code is 'Codigo estable usado como clave de negocio legible. tipo text, obligatoria.';
comment on column public.achievements.title is 'Nombre visible en la interfaz. tipo text, obligatoria.';
comment on column public.achievements.description is 'Texto descriptivo mostrado al jugador. tipo text, obligatoria.';
comment on column public.achievements.category is 'Clasificacion taxonomica del registro. tipo text, obligatoria, por defecto ''general''::text.';
comment on column public.achievements.points is 'Contador acumulado. tipo integer, obligatoria, por defecto 10.';
comment on column public.achievements.reward_vex_ingame is 'Atributo de dominio de la tabla. tipo integer, obligatoria, por defecto 0.';
comment on column public.achievements.reward_xp is 'Atributo de dominio de la tabla. tipo integer, obligatoria, por defecto 0.';
comment on column public.achievements.icon is 'Referencia de icono de identidad visual. tipo text, obligatoria, por defecto ''🏆''::text.';
comment on column public.achievements.hidden is 'Atributo de dominio de la tabla. tipo boolean, obligatoria, por defecto false.';
comment on column public.achievements.metadata is 'Datos auxiliares en JSON no consultados por clave. tipo jsonb, obligatoria, por defecto ''{}''::jsonb.';
comment on column public.achievements.created_at is 'Marca temporal de creacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.battle_runs.id is 'Identificador primario de la fila. tipo uuid, clave primaria, obligatoria, por defecto gen_random_uuid().';
comment on column public.battle_runs.player_id is 'Jugador propietario de la fila. tipo uuid, referencia a public.players.id, obligatoria.';
comment on column public.battle_runs.mission_run_id is 'Referencia a otra entidad del dominio. tipo uuid, referencia a public.mission_runs.id, obligatoria.';
comment on column public.battle_runs.mission_id is 'Referencia a otra entidad del dominio. tipo uuid, referencia a public.missions.id, obligatoria.';
comment on column public.battle_runs.idempotency_key is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.battle_runs.mode is 'Atributo de dominio de la tabla. tipo text, obligatoria, por defecto ''mission''::text.';
comment on column public.battle_runs.rules_version is 'Atributo de dominio de la tabla. tipo text, obligatoria, por defecto ''forge_formation_t2''::text.';
comment on column public.battle_runs.seed is 'Atributo de dominio de la tabla. tipo bigint, obligatoria.';
comment on column public.battle_runs.status is 'Estado del ciclo de vida de la fila. tipo text, obligatoria, por defecto ''started''::text.';
comment on column public.battle_runs.outcome is 'Atributo de dominio de la tabla. tipo boolean, obligatoria.';
comment on column public.battle_runs.formation_snapshot is 'Atributo de dominio de la tabla. tipo jsonb, obligatoria, por defecto ''{}''::jsonb.';
comment on column public.battle_runs.result_snapshot is 'Atributo de dominio de la tabla. tipo jsonb, obligatoria, por defecto ''{}''::jsonb.';
comment on column public.battle_runs.started_at is 'Marca temporal del evento indicado por el nombre. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.battle_runs.completed_at is 'Marca temporal del evento indicado por el nombre. tipo timestamp with time zone, obligatoria.';
comment on column public.battle_runs.created_at is 'Marca temporal de creacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.battle_runs.updated_at is 'Marca temporal de la ultima actualizacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.battle_runs.world_boss_id is 'Referencia a otra entidad del dominio. tipo uuid, referencia a public.world_bosses.id, obligatoria.';
comment on column public.battle_runs.raid_run_id is 'Referencia a otra entidad del dominio. tipo uuid, referencia a public.raid_runs.id, obligatoria.';
comment on column public.card_evolution_paths.id is 'Identificador primario de la fila. tipo uuid, clave primaria, obligatoria, por defecto gen_random_uuid().';
comment on column public.card_evolution_paths.card_id is 'Referencia a otra entidad del dominio. tipo uuid, referencia a public.cards.id, obligatoria.';
comment on column public.card_evolution_paths.evolves_to_card_id is 'Referencia a otra entidad del dominio. tipo uuid, referencia a public.cards.id, obligatoria.';
comment on column public.card_evolution_paths.cost_json is 'Magnitud economica en la unidad definida por el diseno. tipo jsonb, obligatoria, por defecto ''{}''::jsonb.';
comment on column public.card_evolution_paths.requirements_json is 'Atributo de dominio de la tabla. tipo jsonb, obligatoria, por defecto ''{}''::jsonb.';
comment on column public.card_evolution_paths.created_at is 'Marca temporal de creacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.cards.id is 'Identificador primario de la fila. tipo uuid, clave primaria, obligatoria, por defecto gen_random_uuid().';
comment on column public.cards.code is 'Codigo estable usado como clave de negocio legible. tipo text, obligatoria.';
comment on column public.cards.name is 'Nombre visible en la interfaz. tipo text, obligatoria.';
comment on column public.cards.rarity is 'Clasificacion taxonomica del registro. tipo card_rarity, obligatoria.';
comment on column public.cards.faction is 'Clasificacion taxonomica del registro. tipo card_faction, obligatoria.';
comment on column public.cards.specialization is 'Atributo de dominio de la tabla. tipo text, obligatoria, por defecto ''Base''::text.';
comment on column public.cards.power is 'Atributo de dominio de la tabla. tipo integer, obligatoria.';
comment on column public.cards.affinity is 'Atributo de dominio de la tabla. tipo integer, obligatoria.';
comment on column public.cards.prestige is 'Atributo de dominio de la tabla. tipo integer, obligatoria.';
comment on column public.cards.charge is 'Atributo de dominio de la tabla. tipo integer, obligatoria.';
comment on column public.cards.lore is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.cards.prompt is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.cards.image_url is 'Ruta o URL del arte asociado. tipo text, obligatoria.';
comment on column public.cards.region_id is 'Referencia a otra entidad del dominio. tipo text, obligatoria.';
comment on column public.cards.active is 'Bandera booleana de control. tipo boolean, obligatoria, por defecto true.';
comment on column public.cards.supply is 'Atributo de dominio de la tabla. tipo integer, obligatoria, por defecto 0.';
comment on column public.cards.minted is 'Atributo de dominio de la tabla. tipo integer, obligatoria, por defecto 0.';
comment on column public.cards.is_founder is 'Bandera booleana de control. tipo boolean, obligatoria, por defecto false.';
comment on column public.cards.is_legendary is 'Bandera booleana de control. tipo boolean, obligatoria, por defecto false.';
comment on column public.cards.created_at is 'Marca temporal de creacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.cards.updated_at is 'Marca temporal de la ultima actualizacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.cards.card_tier is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.cards.card_tags is 'Atributo de dominio de la tabla. tipo jsonb, obligatoria, por defecto ''[]''::jsonb.';
comment on column public.cards.synergy_json is 'Atributo de dominio de la tabla. tipo jsonb, obligatoria, por defecto ''{}''::jsonb.';
comment on column public.cards.evolution_json is 'Atributo de dominio de la tabla. tipo jsonb, obligatoria, por defecto ''{}''::jsonb.';
comment on column public.cards.card_domain is 'Atributo de dominio de la tabla. tipo text, obligatoria, por defecto ''canonical''::text.';
comment on column public.cards.marketable is 'Atributo de dominio de la tabla. tipo boolean, obligatoria, por defecto true.';
comment on column public.cards.fusion_enabled is 'Atributo de dominio de la tabla. tipo boolean, obligatoria, por defecto true.';
comment on column public.cards.release_status is 'Atributo de dominio de la tabla. tipo text, obligatoria, por defecto ''reserve''::text.';
comment on column public.cards.supply_locked is 'Atributo de dominio de la tabla. tipo boolean, obligatoria, por defecto false.';
comment on column public.cards.market_fee_override is 'Atributo de dominio de la tabla. tipo numeric, obligatoria.';
comment on column public.cards.market_lock is 'Atributo de dominio de la tabla. tipo boolean, obligatoria, por defecto false.';
comment on column public.clan_members.id is 'Identificador primario de la fila. tipo uuid, clave primaria, obligatoria, por defecto gen_random_uuid().';
comment on column public.clan_members.clan_id is 'Referencia a otra entidad del dominio. tipo uuid, referencia a public.clans.id, obligatoria.';
comment on column public.clan_members.player_id is 'Jugador propietario de la fila. tipo uuid, referencia a public.players.id, obligatoria.';
comment on column public.clan_members.role is 'Atributo de dominio de la tabla. tipo clan_role, obligatoria, por defecto ''member''::clan_role.';
comment on column public.clan_members.joined_at is 'Marca temporal del evento indicado por el nombre. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.clan_members.contribution_accumulated is 'Atributo de dominio de la tabla. tipo bigint, obligatoria, por defecto 0.';
comment on column public.clan_members.metadata is 'Datos auxiliares en JSON no consultados por clave. tipo jsonb, obligatoria, por defecto ''{}''::jsonb.';
comment on column public.clan_members.created_at is 'Marca temporal de creacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.clan_members.updated_at is 'Marca temporal de la ultima actualizacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.clan_wars.id is 'Identificador primario de la fila. tipo uuid, clave primaria, obligatoria, por defecto gen_random_uuid().';
comment on column public.clan_wars.reference_id is 'Referencia a otra entidad del dominio. tipo text, obligatoria.';
comment on column public.clan_wars.clan_a_id is 'Referencia a otra entidad del dominio. tipo uuid, referencia a public.clans.id, obligatoria.';
comment on column public.clan_wars.clan_b_id is 'Referencia a otra entidad del dominio. tipo uuid, referencia a public.clans.id, obligatoria.';
comment on column public.clan_wars.status is 'Estado del ciclo de vida de la fila. tipo text, obligatoria, por defecto ''pending''::text.';
comment on column public.clan_wars.rewards_json is 'Atributo de dominio de la tabla. tipo jsonb, obligatoria, por defecto ''{}''::jsonb.';
comment on column public.clan_wars.metadata is 'Datos auxiliares en JSON no consultados por clave. tipo jsonb, obligatoria, por defecto ''{}''::jsonb.';
comment on column public.clan_wars.created_at is 'Marca temporal de creacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.clan_wars.resolved_at is 'Marca temporal del evento indicado por el nombre. tipo timestamp with time zone, obligatoria.';
comment on column public.clan_wars.updated_at is 'Marca temporal de la ultima actualizacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.clans.id is 'Identificador primario de la fila. tipo uuid, clave primaria, obligatoria, por defecto gen_random_uuid().';
comment on column public.clans.code is 'Codigo estable usado como clave de negocio legible. tipo text, obligatoria.';
comment on column public.clans.name is 'Nombre visible en la interfaz. tipo text, obligatoria.';
comment on column public.clans.leader_player_id is 'Referencia a otra entidad del dominio. tipo uuid, referencia a public.players.id, obligatoria.';
comment on column public.clans.prestige is 'Atributo de dominio de la tabla. tipo bigint, obligatoria, por defecto 0.';
comment on column public.clans.contribution_total is 'Atributo de dominio de la tabla. tipo bigint, obligatoria, por defecto 0.';
comment on column public.clans.metadata is 'Datos auxiliares en JSON no consultados por clave. tipo jsonb, obligatoria, por defecto ''{}''::jsonb.';
comment on column public.clans.created_at is 'Marca temporal de creacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.clans.updated_at is 'Marca temporal de la ultima actualizacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.cosmetics.id is 'Identificador primario de la fila. tipo uuid, clave primaria, obligatoria, por defecto gen_random_uuid().';
comment on column public.cosmetics.code is 'Codigo estable usado como clave de negocio legible. tipo text, obligatoria.';
comment on column public.cosmetics.name is 'Nombre visible en la interfaz. tipo text, obligatoria.';
comment on column public.cosmetics.cosmetic_type is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.cosmetics.description is 'Texto descriptivo mostrado al jugador. tipo text, obligatoria.';
comment on column public.cosmetics.rarity is 'Clasificacion taxonomica del registro. tipo text, obligatoria, por defecto ''Common''::text.';
comment on column public.cosmetics.preview_url is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.cosmetics.obtainable_via is 'Atributo de dominio de la tabla. tipo text[], obligatoria, por defecto ''{}''::text[].';
comment on column public.cosmetics.active is 'Bandera booleana de control. tipo boolean, obligatoria, por defecto true.';
comment on column public.cosmetics.metadata is 'Datos auxiliares en JSON no consultados por clave. tipo jsonb, obligatoria, por defecto ''{}''::jsonb.';
comment on column public.cosmetics.created_at is 'Marca temporal de creacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.direct_challenges.id is 'Identificador primario de la fila. tipo uuid, clave primaria, obligatoria, por defecto gen_random_uuid().';
comment on column public.direct_challenges.challenger_id is 'Referencia a otra entidad del dominio. tipo uuid, referencia a public.players.id, obligatoria.';
comment on column public.direct_challenges.challenged_id is 'Referencia a otra entidad del dominio. tipo uuid, referencia a public.players.id, obligatoria.';
comment on column public.direct_challenges.challenger_deck_id is 'Referencia a otra entidad del dominio. tipo uuid, obligatoria.';
comment on column public.direct_challenges.status is 'Estado del ciclo de vida de la fila. tipo text, obligatoria, por defecto ''pending''::text.';
comment on column public.direct_challenges.session_id is 'Referencia a otra entidad del dominio. tipo uuid, obligatoria.';
comment on column public.direct_challenges.created_at is 'Marca temporal de creacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.direct_challenges.updated_at is 'Marca temporal de la ultima actualizacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.economy_ledger.id is 'Identificador primario de la fila. tipo uuid, clave primaria, obligatoria, por defecto gen_random_uuid().';
comment on column public.economy_ledger.reference_id is 'Referencia a otra entidad del dominio. tipo text, obligatoria.';
comment on column public.economy_ledger.player_id is 'Jugador propietario de la fila. tipo uuid, referencia a public.players.id, obligatoria.';
comment on column public.economy_ledger.entry_type is 'Atributo de dominio de la tabla. tipo ledger_entry_type, obligatoria.';
comment on column public.economy_ledger.currency is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.economy_ledger.amount is 'Magnitud economica en la unidad definida por el diseno. tipo numeric(38,12), obligatoria.';
comment on column public.economy_ledger.balance_before is 'Magnitud economica en la unidad definida por el diseno. tipo numeric(38,12), obligatoria.';
comment on column public.economy_ledger.balance_after is 'Magnitud economica en la unidad definida por el diseno. tipo numeric(38,12), obligatoria.';
comment on column public.economy_ledger.source_table is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.economy_ledger.source_id is 'Referencia a otra entidad del dominio. tipo text, obligatoria.';
comment on column public.economy_ledger.metadata is 'Datos auxiliares en JSON no consultados por clave. tipo jsonb, obligatoria, por defecto ''{}''::jsonb.';
comment on column public.economy_ledger.created_at is 'Marca temporal de creacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.economy_ledger.is_final is 'Bandera booleana de control. tipo boolean, obligatoria, por defecto true.';
comment on column public.economy_ledger.row_hash is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.economy_ledger.prev_hash is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.equipped_cosmetics.id is 'Identificador primario de la fila. tipo uuid, clave primaria, obligatoria, por defecto gen_random_uuid().';
comment on column public.equipped_cosmetics.player_id is 'Jugador propietario de la fila. tipo uuid, referencia a public.players.id, obligatoria.';
comment on column public.equipped_cosmetics.slot is 'Valor ordinal o de posicion. tipo text, obligatoria.';
comment on column public.equipped_cosmetics.cosmetic_id is 'Referencia a otra entidad del dominio. tipo uuid, referencia a public.cosmetics.id, obligatoria.';
comment on column public.equipped_cosmetics.equipped_at is 'Marca temporal del evento indicado por el nombre. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.friendships.id is 'Identificador primario de la fila. tipo uuid, clave primaria, obligatoria, por defecto gen_random_uuid().';
comment on column public.friendships.player_a_id is 'Referencia a otra entidad del dominio. tipo uuid, referencia a public.players.id, obligatoria.';
comment on column public.friendships.player_b_id is 'Referencia a otra entidad del dominio. tipo uuid, referencia a public.players.id, obligatoria.';
comment on column public.friendships.status is 'Estado del ciclo de vida de la fila. tipo text, obligatoria, por defecto ''pending''::text.';
comment on column public.friendships.initiated_by is 'Atributo de dominio de la tabla. tipo uuid, referencia a public.players.id, obligatoria.';
comment on column public.friendships.created_at is 'Marca temporal de creacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.friendships.updated_at is 'Marca temporal de la ultima actualizacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.lore_codex.id is 'Identificador primario de la fila. tipo uuid, clave primaria, obligatoria, por defecto gen_random_uuid().';
comment on column public.lore_codex.entry_code is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.lore_codex.title is 'Nombre visible en la interfaz. tipo text, obligatoria.';
comment on column public.lore_codex.content is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.lore_codex.category is 'Clasificacion taxonomica del registro. tipo text, obligatoria.';
comment on column public.lore_codex.related_entity is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.lore_codex.metadata is 'Datos auxiliares en JSON no consultados por clave. tipo jsonb, obligatoria, por defecto ''{}''::jsonb.';
comment on column public.lore_codex.created_at is 'Marca temporal de creacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.market_listings.id is 'Identificador primario de la fila. tipo uuid, clave primaria, obligatoria, por defecto gen_random_uuid().';
comment on column public.market_listings.reference_id is 'Referencia a otra entidad del dominio. tipo text, obligatoria.';
comment on column public.market_listings.player_id is 'Jugador propietario de la fila. tipo uuid, referencia a public.players.id, obligatoria.';
comment on column public.market_listings.player_card_id is 'Referencia a otra entidad del dominio. tipo uuid, referencia a public.player_cards.id, obligatoria.';
comment on column public.market_listings.price is 'Magnitud economica en la unidad definida por el diseno. tipo numeric(38,12), obligatoria.';
comment on column public.market_listings.fee is 'Magnitud economica en la unidad definida por el diseno. tipo numeric(38,12), obligatoria, por defecto 0.';
comment on column public.market_listings.status is 'Estado del ciclo de vida de la fila. tipo listing_status, obligatoria, por defecto ''active''::listing_status.';
comment on column public.market_listings.expires_at is 'Marca temporal del evento indicado por el nombre. tipo timestamp with time zone, obligatoria.';
comment on column public.market_listings.locked is 'Atributo de dominio de la tabla. tipo boolean, obligatoria, por defecto true.';
comment on column public.market_listings.metadata is 'Datos auxiliares en JSON no consultados por clave. tipo jsonb, obligatoria, por defecto ''{}''::jsonb.';
comment on column public.market_listings.created_at is 'Marca temporal de creacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.market_listings.updated_at is 'Marca temporal de la ultima actualizacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.mission_runs.id is 'Identificador primario de la fila. tipo uuid, clave primaria, obligatoria, por defecto gen_random_uuid().';
comment on column public.mission_runs.mission_id is 'Referencia a otra entidad del dominio. tipo uuid, referencia a public.missions.id, obligatoria.';
comment on column public.mission_runs.player_id is 'Jugador propietario de la fila. tipo uuid, referencia a public.players.id, obligatoria.';
comment on column public.mission_runs.idempotency_key is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.mission_runs.reward_reference_id is 'Referencia a otra entidad del dominio. tipo text, obligatoria.';
comment on column public.mission_runs.status is 'Estado del ciclo de vida de la fila. tipo run_status, obligatoria, por defecto ''pending''::run_status.';
comment on column public.mission_runs.energy_spent is 'Atributo de dominio de la tabla. tipo integer, obligatoria, por defecto 0.';
comment on column public.mission_runs.xp_reward is 'Contador acumulado. tipo bigint, obligatoria, por defecto 0.';
comment on column public.mission_runs.ingame_reward is 'Atributo de dominio de la tabla. tipo numeric(38,12), obligatoria, por defecto 0.';
comment on column public.mission_runs.tradeable_reward is 'Atributo de dominio de la tabla. tipo numeric(38,12), obligatoria, por defecto 0.';
comment on column public.mission_runs.metadata is 'Datos auxiliares en JSON no consultados por clave. tipo jsonb, obligatoria, por defecto ''{}''::jsonb.';
comment on column public.mission_runs.started_at is 'Marca temporal del evento indicado por el nombre. tipo timestamp with time zone, obligatoria.';
comment on column public.mission_runs.completed_at is 'Marca temporal del evento indicado por el nombre. tipo timestamp with time zone, obligatoria.';
comment on column public.mission_runs.created_at is 'Marca temporal de creacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.mission_runs.updated_at is 'Marca temporal de la ultima actualizacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.mission_runs.claimed_at is 'Marca temporal del evento indicado por el nombre. tipo timestamp with time zone, obligatoria.';
comment on column public.missions.id is 'Identificador primario de la fila. tipo uuid, clave primaria, obligatoria, por defecto gen_random_uuid().';
comment on column public.missions.code is 'Codigo estable usado como clave de negocio legible. tipo text, obligatoria.';
comment on column public.missions.name is 'Nombre visible en la interfaz. tipo text, obligatoria.';
comment on column public.missions.region_id is 'Referencia a otra entidad del dominio. tipo text, obligatoria.';
comment on column public.missions.mission_type is 'Atributo de dominio de la tabla. tipo mission_type, obligatoria.';
comment on column public.missions.energy_cost is 'Atributo de dominio de la tabla. tipo integer, obligatoria.';
comment on column public.missions.reward_xp is 'Atributo de dominio de la tabla. tipo bigint, obligatoria, por defecto 0.';
comment on column public.missions.reward_vex_ingame is 'Atributo de dominio de la tabla. tipo numeric(38,12), obligatoria, por defecto 0.';
comment on column public.missions.reward_vex_tradeable is 'Atributo de dominio de la tabla. tipo numeric(38,12), obligatoria, por defecto 0.';
comment on column public.missions.cooldown_seconds is 'Atributo de dominio de la tabla. tipo integer, obligatoria, por defecto 0.';
comment on column public.missions.rules_json is 'Atributo de dominio de la tabla. tipo jsonb, obligatoria, por defecto ''{}''::jsonb.';
comment on column public.missions.active is 'Bandera booleana de control. tipo boolean, obligatoria, por defecto true.';
comment on column public.missions.created_at is 'Marca temporal de creacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.missions.updated_at is 'Marca temporal de la ultima actualizacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.missions.base_reward_factor is 'Atributo de dominio de la tabla. tipo numeric, obligatoria, por defecto 1.';
comment on column public.missions.mission_order is 'Atributo de dominio de la tabla. tipo integer, obligatoria, por defecto 0.';
comment on column public.missions.difficulty is 'Atributo de dominio de la tabla. tipo text, obligatoria, por defecto ''normal''::text.';
comment on column public.missions.mission_group is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.missions.requirements_json is 'Atributo de dominio de la tabla. tipo jsonb, obligatoria, por defecto ''{}''::jsonb.';
comment on column public.missions.rewards_json is 'Atributo de dominio de la tabla. tipo jsonb, obligatoria, por defecto ''{}''::jsonb.';
comment on column public.missions.system_locked is 'Atributo de dominio de la tabla. tipo boolean, obligatoria, por defecto true.';
comment on column public.missions.health_status is 'Atributo de dominio de la tabla. tipo text, obligatoria, por defecto ''OK''::text.';
comment on column public.missions.production_ready is 'Atributo de dominio de la tabla. tipo boolean, obligatoria, por defecto true.';
comment on column public.player_achievements.id is 'Identificador primario de la fila. tipo uuid, clave primaria, obligatoria, por defecto gen_random_uuid().';
comment on column public.player_achievements.player_id is 'Jugador propietario de la fila. tipo uuid, referencia a public.players.id, obligatoria.';
comment on column public.player_achievements.achievement_id is 'Referencia a otra entidad del dominio. tipo uuid, referencia a public.achievements.id, obligatoria.';
comment on column public.player_achievements.unlocked_at is 'Marca temporal del evento indicado por el nombre. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.player_active_boosts.id is 'Identificador primario de la fila. tipo uuid, clave primaria, obligatoria, por defecto gen_random_uuid().';
comment on column public.player_active_boosts.player_id is 'Jugador propietario de la fila. tipo uuid, referencia a public.players.id, obligatoria.';
comment on column public.player_active_boosts.boost_type is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.player_active_boosts.multiplier is 'Atributo de dominio de la tabla. tipo numeric, obligatoria, por defecto 1.5.';
comment on column public.player_active_boosts.expires_at is 'Marca temporal del evento indicado por el nombre. tipo timestamp with time zone, obligatoria.';
comment on column public.player_active_boosts.shop_order_id is 'Referencia a otra entidad del dominio. tipo uuid, referencia a public.vexforge_shop_orders.id, obligatoria.';
comment on column public.player_active_boosts.created_at is 'Marca temporal de creacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.player_cards.id is 'Identificador primario de la fila. tipo uuid, clave primaria, obligatoria, por defecto gen_random_uuid().';
comment on column public.player_cards.player_id is 'Jugador propietario de la fila. tipo uuid, referencia a public.players.id, obligatoria.';
comment on column public.player_cards.card_id is 'Referencia a otra entidad del dominio. tipo uuid, referencia a public.cards.id, obligatoria.';
comment on column public.player_cards.quantity is 'Contador acumulado. tipo integer, obligatoria, por defecto 1.';
comment on column public.player_cards.locked is 'Atributo de dominio de la tabla. tipo boolean, obligatoria, por defecto false.';
comment on column public.player_cards.listed is 'Atributo de dominio de la tabla. tipo boolean, obligatoria, por defecto false.';
comment on column public.player_cards.source_tracking is 'Atributo de dominio de la tabla. tipo jsonb, obligatoria, por defecto ''{}''::jsonb.';
comment on column public.player_cards.created_at is 'Marca temporal de creacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.player_cards.updated_at is 'Marca temporal de la ultima actualizacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.player_consumables.id is 'Identificador primario de la fila. tipo uuid, clave primaria, obligatoria, por defecto gen_random_uuid().';
comment on column public.player_consumables.player_id is 'Jugador propietario de la fila. tipo uuid, referencia a public.players.id, obligatoria.';
comment on column public.player_consumables.item_key is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.player_consumables.quantity is 'Contador acumulado. tipo integer, obligatoria, por defecto 1.';
comment on column public.player_consumables.shop_order_id is 'Referencia a otra entidad del dominio. tipo uuid, referencia a public.vexforge_shop_orders.id, obligatoria.';
comment on column public.player_consumables.created_at is 'Marca temporal de creacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.player_consumables.updated_at is 'Marca temporal de la ultima actualizacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.player_cosmetics.id is 'Identificador primario de la fila. tipo uuid, clave primaria, obligatoria, por defecto gen_random_uuid().';
comment on column public.player_cosmetics.player_id is 'Jugador propietario de la fila. tipo uuid, referencia a public.players.id, obligatoria.';
comment on column public.player_cosmetics.cosmetic_id is 'Referencia a otra entidad del dominio. tipo uuid, referencia a public.cosmetics.id, obligatoria.';
comment on column public.player_cosmetics.equipped is 'Atributo de dominio de la tabla. tipo boolean, obligatoria, por defecto false.';
comment on column public.player_cosmetics.obtained_via is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.player_cosmetics.obtained_at is 'Marca temporal del evento indicado por el nombre. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.player_daily_quests.id is 'Identificador primario de la fila. tipo uuid, clave primaria, obligatoria, por defecto gen_random_uuid().';
comment on column public.player_daily_quests.player_id is 'Jugador propietario de la fila. tipo uuid, referencia a public.players.id, obligatoria.';
comment on column public.player_daily_quests.quest_id is 'Referencia a otra entidad del dominio. tipo uuid, referencia a public.daily_quests.id, obligatoria.';
comment on column public.player_daily_quests.assigned_date is 'Atributo de dominio de la tabla. tipo date, obligatoria, por defecto CURRENT_DATE.';
comment on column public.player_daily_quests.status is 'Estado del ciclo de vida de la fila. tipo text, obligatoria, por defecto ''active''::text.';
comment on column public.player_daily_quests.progress is 'Contador acumulado. tipo integer, obligatoria, por defecto 0.';
comment on column public.player_daily_quests.completed_at is 'Marca temporal del evento indicado por el nombre. tipo timestamp with time zone, obligatoria.';
comment on column public.player_daily_quests.claimed_at is 'Marca temporal del evento indicado por el nombre. tipo timestamp with time zone, obligatoria.';
comment on column public.player_daily_quests.created_at is 'Marca temporal de creacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.player_deck.id is 'Identificador primario de la fila. tipo uuid, clave primaria, obligatoria, por defecto gen_random_uuid().';
comment on column public.player_deck.player_id is 'Jugador propietario de la fila. tipo uuid, referencia a public.players.id, obligatoria.';
comment on column public.player_deck.slot_number is 'Valor ordinal o de posicion. tipo integer, obligatoria.';
comment on column public.player_deck.card_id is 'Referencia a otra entidad del dominio. tipo uuid, referencia a public.cards.id, obligatoria.';
comment on column public.player_deck.created_at is 'Marca temporal de creacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.player_deck.updated_at is 'Marca temporal de la ultima actualizacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.player_deck.is_champion is 'Bandera booleana de control. tipo boolean, obligatoria, por defecto false.';
comment on column public.player_economy_state.player_id is 'Jugador propietario de la fila. tipo uuid, clave primaria, referencia a public.players.id, obligatoria.';
comment on column public.player_economy_state.vex_balance is 'Atributo de dominio de la tabla. tipo numeric, obligatoria, por defecto 0.';
comment on column public.player_economy_state.trade_balance is 'Atributo de dominio de la tabla. tipo numeric, obligatoria, por defecto 0.';
comment on column public.player_economy_state.energy is 'Atributo de dominio de la tabla. tipo integer, obligatoria, por defecto 100.';
comment on column public.player_economy_state.last_activity is 'Atributo de dominio de la tabla. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.player_economy_state.decision_energy is 'Atributo de dominio de la tabla. tipo numeric, obligatoria, por defecto 0.';
comment on column public.player_economy_state.participation_score is 'Atributo de dominio de la tabla. tipo numeric, obligatoria, por defecto 0.';
comment on column public.player_economy_state.updated_at is 'Marca temporal de la ultima actualizacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.player_economy_state.economic_elo is 'Atributo de dominio de la tabla. tipo integer, obligatoria, por defecto 1000.';
comment on column public.player_economy_state.liquidity_tier is 'Atributo de dominio de la tabla. tipo smallint, obligatoria, por defecto 0.';
comment on column public.player_economy_state.withdrawal_locked is 'Atributo de dominio de la tabla. tipo boolean, obligatoria, por defecto true.';
comment on column public.player_economy_state.total_usdt_deposited is 'Magnitud economica en la unidad definida por el diseno. tipo numeric, obligatoria, por defecto 0.';
comment on column public.player_economy_state.tradeable_locked_until is 'Atributo de dominio de la tabla. tipo timestamp with time zone, obligatoria.';
comment on column public.player_economy_state.trade_balance_locked is 'Atributo de dominio de la tabla. tipo numeric, obligatoria, por defecto 0.';
comment on column public.player_economy_state.withdrawal_pending is 'Atributo de dominio de la tabla. tipo boolean, obligatoria, por defecto false.';
comment on column public.player_economy_state.daily_ingame_minted is 'Atributo de dominio de la tabla. tipo numeric, obligatoria, por defecto 0.';
comment on column public.player_economy_state.daily_tradeable_minted is 'Atributo de dominio de la tabla. tipo numeric, obligatoria, por defecto 0.';
comment on column public.player_economy_state.daily_market_volume is 'Atributo de dominio de la tabla. tipo numeric, obligatoria, por defecto 0.';
comment on column public.player_economy_state.daily_fusion_burn is 'Atributo de dominio de la tabla. tipo numeric, obligatoria, por defecto 0.';
comment on column public.player_economy_state.economy_day_marker is 'Atributo de dominio de la tabla. tipo date, obligatoria, por defecto CURRENT_DATE.';
comment on column public.player_economy_state.mission_tradeable_lock is 'Atributo de dominio de la tabla. tipo boolean, obligatoria, por defecto true.';
comment on column public.player_notifications.id is 'Identificador primario de la fila. tipo uuid, clave primaria, obligatoria, por defecto gen_random_uuid().';
comment on column public.player_notifications.player_id is 'Jugador propietario de la fila. tipo uuid, obligatoria.';
comment on column public.player_notifications.type is 'Clasificacion taxonomica del registro. tipo text, obligatoria, por defecto ''system''::text.';
comment on column public.player_notifications.title is 'Nombre visible en la interfaz. tipo text, obligatoria.';
comment on column public.player_notifications.message is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.player_notifications.icon is 'Referencia de icono de identidad visual. tipo text, obligatoria, por defecto ''🔔''::text.';
comment on column public.player_notifications.link is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.player_notifications.read is 'Atributo de dominio de la tabla. tipo boolean, obligatoria, por defecto false.';
comment on column public.player_notifications.created_at is 'Marca temporal de creacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.player_progress.id is 'Identificador primario de la fila. tipo uuid, clave primaria, obligatoria, por defecto gen_random_uuid().';
comment on column public.player_progress.player_id is 'Jugador propietario de la fila. tipo uuid, referencia a public.players.id, obligatoria.';
comment on column public.player_progress.level is 'Valor ordinal o de posicion. tipo integer, obligatoria, por defecto 1.';
comment on column public.player_progress.xp is 'Contador acumulado. tipo bigint, obligatoria, por defecto 0.';
comment on column public.player_progress.xp_to_next is 'Contador acumulado. tipo bigint, obligatoria, por defecto 100.';
comment on column public.player_progress.energy is 'Atributo de dominio de la tabla. tipo integer, obligatoria, por defecto 100.';
comment on column public.player_progress.max_energy is 'Atributo de dominio de la tabla. tipo integer, obligatoria, por defecto 100.';
comment on column public.player_progress.tutorial_step is 'Atributo de dominio de la tabla. tipo integer, obligatoria, por defecto 1.';
comment on column public.player_progress.starter_region is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.player_progress.created_at is 'Marca temporal de creacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.player_progress.updated_at is 'Marca temporal de la ultima actualizacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.player_progress.energy_last_regen is 'Atributo de dominio de la tabla. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.player_relics.id is 'Identificador primario de la fila. tipo uuid, clave primaria, obligatoria, por defecto gen_random_uuid().';
comment on column public.player_relics.player_id is 'Jugador propietario de la fila. tipo uuid, referencia a public.players.id, obligatoria.';
comment on column public.player_relics.relic_id is 'Referencia a otra entidad del dominio. tipo uuid, referencia a public.relics.id, obligatoria.';
comment on column public.player_relics.quantity is 'Contador acumulado. tipo integer, obligatoria, por defecto 1.';
comment on column public.player_relics.is_equipped is 'Bandera booleana de control. tipo boolean, obligatoria, por defecto false.';
comment on column public.player_relics.equipped_slot is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.player_relics.acquired_from is 'Atributo de dominio de la tabla. tipo text, obligatoria, por defecto ''system''::text.';
comment on column public.player_relics.acquired_at is 'Marca temporal del evento indicado por el nombre. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.player_relics.updated_at is 'Marca temporal de la ultima actualizacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.player_settings.player_id is 'Jugador propietario de la fila. tipo uuid, clave primaria, referencia a public.players.id, obligatoria.';
comment on column public.player_settings.telegram_enabled is 'Atributo de dominio de la tabla. tipo boolean, obligatoria, por defecto true.';
comment on column public.player_settings.notifications_enabled is 'Atributo de dominio de la tabla. tipo boolean, obligatoria, por defecto true.';
comment on column public.player_settings.language is 'Atributo de dominio de la tabla. tipo text, obligatoria, por defecto ''es''::text.';
comment on column public.player_settings.timezone is 'Atributo de dominio de la tabla. tipo text, obligatoria, por defecto ''America/Los_Angeles''::text.';
comment on column public.player_settings.ui_mode is 'Atributo de dominio de la tabla. tipo text, obligatoria, por defecto ''default''::text.';
comment on column public.player_settings.created_at is 'Marca temporal de creacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.player_settings.updated_at is 'Marca temporal de la ultima actualizacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.player_wallet.id is 'Identificador primario de la fila. tipo uuid, clave primaria, obligatoria, por defecto gen_random_uuid().';
comment on column public.player_wallet.player_id is 'Jugador propietario de la fila. tipo uuid, referencia a public.players.id, obligatoria.';
comment on column public.player_wallet.vex_ingame is 'Atributo de dominio de la tabla. tipo numeric(38,12), obligatoria, por defecto 0.';
comment on column public.player_wallet.vex_tradeable is 'Atributo de dominio de la tabla. tipo numeric(38,12), obligatoria, por defecto 0.';
comment on column public.player_wallet.reserved_ingame is 'Atributo de dominio de la tabla. tipo numeric(38,12), obligatoria, por defecto 0.';
comment on column public.player_wallet.reserved_tradeable is 'Atributo de dominio de la tabla. tipo numeric(38,12), obligatoria, por defecto 0.';
comment on column public.player_wallet.created_at is 'Marca temporal de creacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.player_wallet.updated_at is 'Marca temporal de la ultima actualizacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.player_wallet.last_synced_from_ledger is 'Atributo de dominio de la tabla. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.players.id is 'Identificador primario de la fila. tipo uuid, clave primaria, obligatoria, por defecto gen_random_uuid().';
comment on column public.players.auth_user_id is 'Referencia a otra entidad del dominio. tipo uuid, obligatoria.';
comment on column public.players.email is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.players.display_name is 'Nombre visible en la interfaz. tipo text, obligatoria.';
comment on column public.players.role is 'Atributo de dominio de la tabla. tipo text, obligatoria, por defecto ''player''::text.';
comment on column public.players.status is 'Estado del ciclo de vida de la fila. tipo text, obligatoria, por defecto ''active''::text.';
comment on column public.players.created_at is 'Marca temporal de creacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.players.updated_at is 'Marca temporal de la ultima actualizacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.players.is_admin is 'Bandera booleana de control. tipo boolean, obligatoria, por defecto false.';
comment on column public.players.is_super_admin is 'Bandera booleana de control. tipo boolean, obligatoria, por defecto false.';
comment on column public.players.telegram_id is 'Referencia a otra entidad del dominio. tipo bigint, obligatoria.';
comment on column public.players.telegram_username is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.players.source_system is 'Atributo de dominio de la tabla. tipo text, obligatoria, por defecto ''web''::text.';
comment on column public.players.referral_code is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.players.champion_card_id is 'Referencia a otra entidad del dominio. tipo uuid, referencia a public.cards.id, obligatoria.';
comment on column public.players.is_qa is 'Bandera booleana de control. tipo boolean, obligatoria, por defecto false.';
comment on column public.pvp_matches.id is 'Identificador primario de la fila. tipo uuid, clave primaria, obligatoria, por defecto gen_random_uuid().';
comment on column public.pvp_matches.reference_id is 'Referencia a otra entidad del dominio. tipo text, obligatoria, por defecto (gen_random_uuid())::text.';
comment on column public.pvp_matches.player_a is 'Atributo de dominio de la tabla. tipo uuid, referencia a public.players.id, obligatoria.';
comment on column public.pvp_matches.player_b is 'Atributo de dominio de la tabla. tipo uuid, referencia a public.players.id, obligatoria.';
comment on column public.pvp_matches.winner is 'Atributo de dominio de la tabla. tipo uuid, referencia a public.players.id, obligatoria.';
comment on column public.pvp_matches.status is 'Estado del ciclo de vida de la fila. tipo match_status, obligatoria, por defecto ''pending''::match_status.';
comment on column public.pvp_matches.elo_change_a is 'Atributo de dominio de la tabla. tipo integer, obligatoria, por defecto 0.';
comment on column public.pvp_matches.elo_change_b is 'Atributo de dominio de la tabla. tipo integer, obligatoria, por defecto 0.';
comment on column public.pvp_matches.power_snapshot_a is 'Atributo de dominio de la tabla. tipo jsonb, obligatoria, por defecto ''{}''::jsonb.';
comment on column public.pvp_matches.power_snapshot_b is 'Atributo de dominio de la tabla. tipo jsonb, obligatoria, por defecto ''{}''::jsonb.';
comment on column public.pvp_matches.rewards_json is 'Atributo de dominio de la tabla. tipo jsonb, obligatoria, por defecto ''{}''::jsonb.';
comment on column public.pvp_matches.metadata is 'Datos auxiliares en JSON no consultados por clave. tipo jsonb, obligatoria, por defecto ''{}''::jsonb.';
comment on column public.pvp_matches.created_at is 'Marca temporal de creacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.pvp_matches.resolved_at is 'Marca temporal del evento indicado por el nombre. tipo timestamp with time zone, obligatoria.';
comment on column public.pvp_matches.updated_at is 'Marca temporal de la ultima actualizacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.pvp_matches.formation_snapshot_a is 'Atributo de dominio de la tabla. tipo jsonb, obligatoria.';
comment on column public.pvp_matches.formation_snapshot_b is 'Atributo de dominio de la tabla. tipo jsonb, obligatoria.';
comment on column public.pvp_matches.forfeit_by is 'Atributo de dominio de la tabla. tipo uuid, obligatoria.';
comment on column public.pvp_rankings.id is 'Identificador primario de la fila. tipo uuid, clave primaria, obligatoria, por defecto gen_random_uuid().';
comment on column public.pvp_rankings.season_id is 'Referencia a otra entidad del dominio. tipo uuid, referencia a public.pvp_seasons.id, obligatoria.';
comment on column public.pvp_rankings.player_id is 'Jugador propietario de la fila. tipo uuid, referencia a public.players.id, obligatoria.';
comment on column public.pvp_rankings.mmr is 'Atributo de dominio de la tabla. tipo integer, obligatoria, por defecto 1000.';
comment on column public.pvp_rankings.rank_position is 'Valor ordinal o de posicion. tipo integer, obligatoria.';
comment on column public.pvp_rankings.wins is 'Contador acumulado. tipo integer, obligatoria, por defecto 0.';
comment on column public.pvp_rankings.losses is 'Contador acumulado. tipo integer, obligatoria, por defecto 0.';
comment on column public.pvp_rankings.draws is 'Atributo de dominio de la tabla. tipo integer, obligatoria, por defecto 0.';
comment on column public.pvp_rankings.updated_at is 'Marca temporal de la ultima actualizacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.pvp_rankings.champion_card_id is 'Referencia a otra entidad del dominio. tipo uuid, referencia a public.cards.id, obligatoria.';
comment on column public.pvp_rankings.avg_dps_score is 'Atributo de dominio de la tabla. tipo integer, obligatoria, por defecto 0.';
comment on column public.pvp_seasons.id is 'Identificador primario de la fila. tipo uuid, clave primaria, obligatoria, por defecto gen_random_uuid().';
comment on column public.pvp_seasons.season_key is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.pvp_seasons.name is 'Nombre visible en la interfaz. tipo text, obligatoria.';
comment on column public.pvp_seasons.starts_at is 'Marca temporal del evento indicado por el nombre. tipo timestamp with time zone, obligatoria.';
comment on column public.pvp_seasons.ends_at is 'Marca temporal del evento indicado por el nombre. tipo timestamp with time zone, obligatoria.';
comment on column public.pvp_seasons.active is 'Bandera booleana de control. tipo boolean, obligatoria, por defecto true.';
comment on column public.pvp_seasons.reward_json is 'Atributo de dominio de la tabla. tipo jsonb, obligatoria, por defecto ''{}''::jsonb.';
comment on column public.pvp_seasons.created_at is 'Marca temporal de creacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.pvp_seasons.updated_at is 'Marca temporal de la ultima actualizacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.raid_participants.id is 'Identificador primario de la fila. tipo uuid, clave primaria, obligatoria, por defecto gen_random_uuid().';
comment on column public.raid_participants.raid_run_id is 'Referencia a otra entidad del dominio. tipo uuid, referencia a public.raid_runs.id, obligatoria.';
comment on column public.raid_participants.player_id is 'Jugador propietario de la fila. tipo uuid, referencia a public.players.id, obligatoria.';
comment on column public.raid_participants.contribution is 'Atributo de dominio de la tabla. tipo bigint, obligatoria, por defecto 0.';
comment on column public.raid_participants.status is 'Estado del ciclo de vida de la fila. tipo text, obligatoria, por defecto ''joined''::text.';
comment on column public.raid_participants.metadata is 'Datos auxiliares en JSON no consultados por clave. tipo jsonb, obligatoria, por defecto ''{}''::jsonb.';
comment on column public.raid_participants.created_at is 'Marca temporal de creacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.raid_participants.updated_at is 'Marca temporal de la ultima actualizacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.raid_runs.id is 'Identificador primario de la fila. tipo uuid, clave primaria, obligatoria, por defecto gen_random_uuid().';
comment on column public.raid_runs.raid_code is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.raid_runs.region_id is 'Referencia a otra entidad del dominio. tipo text, obligatoria.';
comment on column public.raid_runs.status is 'Estado del ciclo de vida de la fila. tipo text, obligatoria, por defecto ''pending''::text.';
comment on column public.raid_runs.created_by is 'Atributo de dominio de la tabla. tipo uuid, referencia a public.players.id, obligatoria.';
comment on column public.raid_runs.started_at is 'Marca temporal del evento indicado por el nombre. tipo timestamp with time zone, obligatoria.';
comment on column public.raid_runs.ended_at is 'Marca temporal del evento indicado por el nombre. tipo timestamp with time zone, obligatoria.';
comment on column public.raid_runs.metadata is 'Datos auxiliares en JSON no consultados por clave. tipo jsonb, obligatoria, por defecto ''{}''::jsonb.';
comment on column public.raid_runs.created_at is 'Marca temporal de creacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.raid_runs.updated_at is 'Marca temporal de la ultima actualizacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.relics.id is 'Identificador primario de la fila. tipo uuid, clave primaria, obligatoria, por defecto gen_random_uuid().';
comment on column public.relics.code is 'Codigo estable usado como clave de negocio legible. tipo text, obligatoria.';
comment on column public.relics.name is 'Nombre visible en la interfaz. tipo text, obligatoria.';
comment on column public.relics.effect_type is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.relics.effect_value is 'Atributo de dominio de la tabla. tipo numeric, obligatoria, por defecto 0.';
comment on column public.relics.metadata is 'Datos auxiliares en JSON no consultados por clave. tipo jsonb, obligatoria, por defecto ''{}''::jsonb.';
comment on column public.relics.created_at is 'Marca temporal de creacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.season_rankings.id is 'Identificador primario de la fila. tipo uuid, clave primaria, obligatoria, por defecto gen_random_uuid().';
comment on column public.season_rankings.season_key is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.season_rankings.player_id is 'Jugador propietario de la fila. tipo uuid, referencia a public.players.id, obligatoria.';
comment on column public.season_rankings.rank_position is 'Valor ordinal o de posicion. tipo integer, obligatoria, por defecto 0.';
comment on column public.season_rankings.mmr is 'Atributo de dominio de la tabla. tipo integer, obligatoria, por defecto 1000.';
comment on column public.season_rankings.wins is 'Contador acumulado. tipo integer, obligatoria, por defecto 0.';
comment on column public.season_rankings.losses is 'Contador acumulado. tipo integer, obligatoria, por defecto 0.';
comment on column public.season_rankings.draws is 'Atributo de dominio de la tabla. tipo integer, obligatoria, por defecto 0.';
comment on column public.season_rankings.metadata is 'Datos auxiliares en JSON no consultados por clave. tipo jsonb, obligatoria, por defecto ''{}''::jsonb.';
comment on column public.season_rankings.created_at is 'Marca temporal de creacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.season_rankings.updated_at is 'Marca temporal de la ultima actualizacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.vexforge_ad_views.id is 'Identificador primario de la fila. tipo uuid, clave primaria, obligatoria, por defecto gen_random_uuid().';
comment on column public.vexforge_ad_views.player_auth_id is 'Referencia a otra entidad del dominio. tipo uuid, obligatoria.';
comment on column public.vexforge_ad_views.ad_network is 'Atributo de dominio de la tabla. tipo text, obligatoria, por defecto ''organic''::text.';
comment on column public.vexforge_ad_views.completed is 'Atributo de dominio de la tabla. tipo boolean, obligatoria, por defecto false.';
comment on column public.vexforge_ad_views.watched_pct is 'Atributo de dominio de la tabla. tipo numeric, obligatoria, por defecto 0.';
comment on column public.vexforge_ad_views.vex_awarded is 'Atributo de dominio de la tabla. tipo numeric, obligatoria, por defecto 0.';
comment on column public.vexforge_ad_views.created_at is 'Marca temporal de creacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.vexforge_nft_contracts.id is 'Identificador primario de la fila. tipo uuid, clave primaria, obligatoria, por defecto gen_random_uuid().';
comment on column public.vexforge_nft_contracts.chain_id is 'Referencia a otra entidad del dominio. tipo integer, obligatoria, por defecto 137.';
comment on column public.vexforge_nft_contracts.contract_address is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.vexforge_nft_contracts.name is 'Nombre visible en la interfaz. tipo text, obligatoria, por defecto ''VexforgeCards''::text.';
comment on column public.vexforge_nft_contracts.symbol is 'Atributo de dominio de la tabla. tipo text, obligatoria, por defecto ''VFC''::text.';
comment on column public.vexforge_nft_contracts.max_supply is 'Atributo de dominio de la tabla. tipo integer, obligatoria, por defecto 999999.';
comment on column public.vexforge_nft_contracts.status is 'Estado del ciclo de vida de la fila. tipo text, obligatoria, por defecto ''pending''::text.';
comment on column public.vexforge_nft_contracts.deployed_at is 'Marca temporal del evento indicado por el nombre. tipo timestamp with time zone, obligatoria.';
comment on column public.vexforge_nft_contracts.created_at is 'Marca temporal de creacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.vexforge_nft_mint_queue.id is 'Identificador primario de la fila. tipo uuid, clave primaria, obligatoria, por defecto gen_random_uuid().';
comment on column public.vexforge_nft_mint_queue.player_id is 'Jugador propietario de la fila. tipo uuid, referencia a public.players.id, obligatoria.';
comment on column public.vexforge_nft_mint_queue.card_id is 'Referencia a otra entidad del dominio. tipo uuid, referencia a public.cards.id, obligatoria.';
comment on column public.vexforge_nft_mint_queue.wallet_address is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.vexforge_nft_mint_queue.status is 'Estado del ciclo de vida de la fila. tipo text, obligatoria, por defecto ''pending''::text.';
comment on column public.vexforge_nft_mint_queue.tx_hash is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.vexforge_nft_mint_queue.token_id is 'Referencia a otra entidad del dominio. tipo integer, obligatoria.';
comment on column public.vexforge_nft_mint_queue.error_message is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.vexforge_nft_mint_queue.requested_at is 'Marca temporal del evento indicado por el nombre. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.vexforge_nft_mint_queue.processed_at is 'Marca temporal del evento indicado por el nombre. tipo timestamp with time zone, obligatoria.';
comment on column public.vexforge_nft_wallet_links.id is 'Identificador primario de la fila. tipo uuid, clave primaria, obligatoria, por defecto gen_random_uuid().';
comment on column public.vexforge_nft_wallet_links.player_id is 'Jugador propietario de la fila. tipo uuid, referencia a public.players.id, obligatoria.';
comment on column public.vexforge_nft_wallet_links.wallet_address is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.vexforge_nft_wallet_links.chain_id is 'Referencia a otra entidad del dominio. tipo integer, obligatoria, por defecto 137.';
comment on column public.vexforge_nft_wallet_links.verified is 'Atributo de dominio de la tabla. tipo boolean, obligatoria, por defecto false.';
comment on column public.vexforge_nft_wallet_links.linked_at is 'Marca temporal del evento indicado por el nombre. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.vexforge_pack_catalog.pack_key is 'Atributo de dominio de la tabla. tipo text, clave primaria, obligatoria.';
comment on column public.vexforge_pack_catalog.pack_name is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.vexforge_pack_catalog.price_usdt is 'Magnitud economica en la unidad definida por el diseno. tipo numeric, obligatoria.';
comment on column public.vexforge_pack_catalog.active is 'Bandera booleana de control. tipo boolean, obligatoria, por defecto true.';
comment on column public.vexforge_pack_catalog.notes is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.vexforge_pack_catalog.metadata is 'Datos auxiliares en JSON no consultados por clave. tipo jsonb, obligatoria, por defecto ''{}''::jsonb.';
comment on column public.vexforge_pack_catalog.created_at is 'Marca temporal de creacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.vexforge_pack_catalog.updated_at is 'Marca temporal de la ultima actualizacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.vexforge_pack_catalog.price_vex is 'Magnitud economica en la unidad definida por el diseno. tipo numeric, obligatoria, por defecto 0.';
comment on column public.vexforge_pack_catalog.card_count is 'Atributo de dominio de la tabla. tipo integer, obligatoria, por defecto 5.';
comment on column public.vexforge_pack_orders.id is 'Identificador primario de la fila. tipo uuid, clave primaria, obligatoria, por defecto gen_random_uuid().';
comment on column public.vexforge_pack_orders.player_id is 'Jugador propietario de la fila. tipo uuid, referencia a public.players.id, obligatoria.';
comment on column public.vexforge_pack_orders.pack_key is 'Atributo de dominio de la tabla. tipo text, referencia a public.vexforge_pack_catalog.pack_key, obligatoria.';
comment on column public.vexforge_pack_orders.price_usdt is 'Magnitud economica en la unidad definida por el diseno. tipo numeric, obligatoria.';
comment on column public.vexforge_pack_orders.status is 'Estado del ciclo de vida de la fila. tipo text, obligatoria, por defecto ''pending_payment''::text.';
comment on column public.vexforge_pack_orders.payment_reference is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.vexforge_pack_orders.tx_hash is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.vexforge_pack_orders.treasury_wallet_address is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.vexforge_pack_orders.metadata is 'Datos auxiliares en JSON no consultados por clave. tipo jsonb, obligatoria, por defecto ''{}''::jsonb.';
comment on column public.vexforge_pack_orders.created_at is 'Marca temporal de creacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.vexforge_pack_orders.updated_at is 'Marca temporal de la ultima actualizacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.vexforge_pack_orders.payment_method is 'Atributo de dominio de la tabla. tipo text, obligatoria, por defecto ''usdt_direct''::text.';
comment on column public.vexforge_player_shards.id is 'Identificador primario de la fila. tipo uuid, clave primaria, obligatoria, por defecto gen_random_uuid().';
comment on column public.vexforge_player_shards.player_id is 'Jugador propietario de la fila. tipo uuid, referencia a public.players.id, obligatoria.';
comment on column public.vexforge_player_shards.shard_rarity is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.vexforge_player_shards.quantity is 'Contador acumulado. tipo integer, obligatoria, por defecto 0.';
comment on column public.vexforge_player_shards.created_at is 'Marca temporal de creacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.vexforge_player_shards.updated_at is 'Marca temporal de la ultima actualizacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.vexforge_referrals.id is 'Identificador primario de la fila. tipo uuid, clave primaria, obligatoria, por defecto gen_random_uuid().';
comment on column public.vexforge_referrals.referrer_auth_id is 'Referencia a otra entidad del dominio. tipo uuid, obligatoria.';
comment on column public.vexforge_referrals.referred_auth_id is 'Referencia a otra entidad del dominio. tipo uuid, obligatoria.';
comment on column public.vexforge_referrals.referred_display_name is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.vexforge_referrals.status is 'Estado del ciclo de vida de la fila. tipo text, obligatoria, por defecto ''pending''::text.';
comment on column public.vexforge_referrals.reward_granted is 'Atributo de dominio de la tabla. tipo boolean, obligatoria, por defecto false.';
comment on column public.vexforge_referrals.first_pack_rewarded is 'Atributo de dominio de la tabla. tipo boolean, obligatoria, por defecto false.';
comment on column public.vexforge_referrals.created_at is 'Marca temporal de creacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.vexforge_referrals.updated_at is 'Marca temporal de la ultima actualizacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.vexforge_shop_catalog.id is 'Identificador primario de la fila. tipo uuid, clave primaria, obligatoria, por defecto gen_random_uuid().';
comment on column public.vexforge_shop_catalog.item_key is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.vexforge_shop_catalog.name is 'Nombre visible en la interfaz. tipo text, obligatoria.';
comment on column public.vexforge_shop_catalog.description is 'Texto descriptivo mostrado al jugador. tipo text, obligatoria.';
comment on column public.vexforge_shop_catalog.category is 'Clasificacion taxonomica del registro. tipo text, obligatoria.';
comment on column public.vexforge_shop_catalog.price_usdt is 'Magnitud economica en la unidad definida por el diseno. tipo numeric, obligatoria.';
comment on column public.vexforge_shop_catalog.price_vex is 'Magnitud economica en la unidad definida por el diseno. tipo numeric, obligatoria.';
comment on column public.vexforge_shop_catalog.icon is 'Referencia de icono de identidad visual. tipo text, obligatoria.';
comment on column public.vexforge_shop_catalog.active is 'Bandera booleana de control. tipo boolean, obligatoria, por defecto true.';
comment on column public.vexforge_shop_catalog.sort_order is 'Valor ordinal o de posicion. tipo integer, obligatoria, por defecto 0.';
comment on column public.vexforge_shop_catalog.created_at is 'Marca temporal de creacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.vexforge_shop_catalog.updated_at is 'Marca temporal de la ultima actualizacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.vexforge_treasury.id is 'Identificador primario de la fila. tipo uuid, clave primaria, obligatoria, por defecto gen_random_uuid().';
comment on column public.vexforge_treasury.chain is 'Atributo de dominio de la tabla. tipo text, obligatoria, por defecto ''BSC''::text.';
comment on column public.vexforge_treasury.token_symbol is 'Atributo de dominio de la tabla. tipo text, obligatoria, por defecto ''USDT''::text.';
comment on column public.vexforge_treasury.wallet_address is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.vexforge_treasury.purpose is 'Atributo de dominio de la tabla. tipo text, obligatoria, por defecto ''project_treasury''::text.';
comment on column public.vexforge_treasury.active is 'Bandera booleana de control. tipo boolean, obligatoria, por defecto true.';
comment on column public.vexforge_treasury.created_at is 'Marca temporal de creacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.vexforge_treasury.updated_at is 'Marca temporal de la ultima actualizacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.vexforge_treasury.token_standard is 'Atributo de dominio de la tabla. tipo text, obligatoria, por defecto ''BEP20''::text.';
comment on column public.vexforge_withdrawal_requests_official.id is 'Identificador primario de la fila. tipo uuid, clave primaria, obligatoria, por defecto gen_random_uuid().';
comment on column public.vexforge_withdrawal_requests_official.player_id is 'Jugador propietario de la fila. tipo uuid, referencia a public.players.id, obligatoria.';
comment on column public.vexforge_withdrawal_requests_official.tradeable_amount is 'Atributo de dominio de la tabla. tipo numeric, obligatoria.';
comment on column public.vexforge_withdrawal_requests_official.usdt_gross is 'Atributo de dominio de la tabla. tipo numeric, obligatoria.';
comment on column public.vexforge_withdrawal_requests_official.fee_usdt is 'Magnitud economica en la unidad definida por el diseno. tipo numeric, obligatoria.';
comment on column public.vexforge_withdrawal_requests_official.usdt_net is 'Atributo de dominio de la tabla. tipo numeric, obligatoria.';
comment on column public.vexforge_withdrawal_requests_official.treasury_wallet_address is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.vexforge_withdrawal_requests_official.status is 'Estado del ciclo de vida de la fila. tipo text, obligatoria, por defecto ''pending_review''::text.';
comment on column public.vexforge_withdrawal_requests_official.reviewed is 'Atributo de dominio de la tabla. tipo boolean, obligatoria, por defecto false.';
comment on column public.vexforge_withdrawal_requests_official.approved_by is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.vexforge_withdrawal_requests_official.rejected_reason is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.vexforge_withdrawal_requests_official.payout_tx_hash is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.vexforge_withdrawal_requests_official.metadata is 'Datos auxiliares en JSON no consultados por clave. tipo jsonb, obligatoria, por defecto ''{}''::jsonb.';
comment on column public.vexforge_withdrawal_requests_official.created_at is 'Marca temporal de creacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.vexforge_withdrawal_requests_official.updated_at is 'Marca temporal de la ultima actualizacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.vexforge_withdrawal_requests_official.processed_at is 'Marca temporal del evento indicado por el nombre. tipo timestamp with time zone, obligatoria.';
comment on column public.world_boss_encounters.id is 'Identificador primario de la fila. tipo uuid, clave primaria, obligatoria, por defecto gen_random_uuid().';
comment on column public.world_boss_encounters.world_boss_id is 'Referencia a otra entidad del dominio. tipo uuid, referencia a public.world_bosses.id, obligatoria.';
comment on column public.world_boss_encounters.player_id is 'Jugador propietario de la fila. tipo uuid, referencia a public.players.id, obligatoria.';
comment on column public.world_boss_encounters.damage is 'Atributo de dominio de la tabla. tipo bigint, obligatoria, por defecto 0.';
comment on column public.world_boss_encounters.reward_json is 'Atributo de dominio de la tabla. tipo jsonb, obligatoria, por defecto ''{}''::jsonb.';
comment on column public.world_boss_encounters.status is 'Estado del ciclo de vida de la fila. tipo text, obligatoria, por defecto ''pending''::text.';
comment on column public.world_boss_encounters.created_at is 'Marca temporal de creacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.world_boss_encounters.updated_at is 'Marca temporal de la ultima actualizacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.world_boss_encounters.battle_run_id is 'Referencia a otra entidad del dominio. tipo uuid, referencia a public.battle_runs.id, obligatoria.';
comment on column public.world_bosses.id is 'Identificador primario de la fila. tipo uuid, clave primaria, obligatoria, por defecto gen_random_uuid().';
comment on column public.world_bosses.boss_code is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.world_bosses.name is 'Nombre visible en la interfaz. tipo text, obligatoria.';
comment on column public.world_bosses.region_id is 'Referencia a otra entidad del dominio. tipo text, obligatoria.';
comment on column public.world_bosses.tier is 'Clasificacion taxonomica del registro. tipo text, obligatoria, por defecto ''standard''::text.';
comment on column public.world_bosses.power_level is 'Atributo de dominio de la tabla. tipo integer, obligatoria, por defecto 1.';
comment on column public.world_bosses.hp is 'Atributo de dominio de la tabla. tipo bigint, obligatoria, por defecto 1.';
comment on column public.world_bosses.reward_pool is 'Atributo de dominio de la tabla. tipo jsonb, obligatoria, por defecto ''{}''::jsonb.';
comment on column public.world_bosses.active is 'Bandera booleana de control. tipo boolean, obligatoria, por defecto true.';
comment on column public.world_bosses.metadata is 'Datos auxiliares en JSON no consultados por clave. tipo jsonb, obligatoria, por defecto ''{}''::jsonb.';
comment on column public.world_bosses.created_at is 'Marca temporal de creacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.world_bosses.updated_at is 'Marca temporal de la ultima actualizacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.world_bosses.image_url is 'Ruta o URL del arte asociado. tipo text, obligatoria.';

-- Sonda publica de cobertura documental de columnas para un conjunto de tablas
-- declarado por el repositorio (las tablas que el cliente consume). Solo metadatos.
create or replace function public.vexforge_column_doc_coverage(_tables text[])
returns table(total_columns integer, undocumented integer, missing text[])
language sql
stable
security definer
set search_path = public, pg_catalog
as $$
  with c as (
    select cl.relname || '.' || a.attname as ref,
           col_description(a.attrelid, a.attnum) as cmt
    from pg_attribute a
    join pg_class cl on cl.oid = a.attrelid
    join pg_namespace n on n.oid = cl.relnamespace
    where n.nspname = 'public'
      and cl.relkind = 'r'
      and a.attnum > 0
      and not a.attisdropped
      and cl.relname = any(_tables)
  )
  select
    count(*)::integer,
    count(*) filter (where cmt is null)::integer,
    coalesce(array_agg(ref order by ref) filter (where cmt is null), '{}'::text[])
  from c;
$$;

comment on function public.vexforge_column_doc_coverage(text[]) is
  'VE-DOC-4: cobertura documental de columnas para las tablas indicadas (total, sin comentario y referencias faltantes). Solo metadatos, sin datos de jugador.';

revoke all on function public.vexforge_column_doc_coverage(text[]) from public;
grant execute on function public.vexforge_column_doc_coverage(text[]) to anon, authenticated, service_role;
