-- VE-DOC-5-SUPPORT-COLUMN-COMMENTS
-- Higiene documental de columnas de tablas de soporte interno `vexforge_*` con dependencia
-- en funciones o vistas del catalogo vivo (alcance declarado en VE-DOC-4).
-- Solo metadatos: sin cambios de esquema, datos, RLS, grants, RPCs, economia autoritativa, Storage ni arte.

comment on column public.vexforge_asset_files.id is 'Identificador primario de la fila. tipo uuid, clave primaria, obligatoria, por defecto gen_random_uuid().';
comment on column public.vexforge_asset_files.asset_code is 'Codigo estable usado como clave de negocio legible. tipo text, obligatoria.';
comment on column public.vexforge_asset_files.asset_pack is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.vexforge_asset_files.internal_path is 'Ruta o URL del arte asociado. tipo text, obligatoria.';
comment on column public.vexforge_asset_files.file_name is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.vexforge_asset_files.semantic_role is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.vexforge_asset_files.display_name is 'Nombre visible en la interfaz. tipo text, obligatoria.';
comment on column public.vexforge_asset_files.source_zip_url is 'Ruta o URL del arte asociado. tipo text, obligatoria.';
comment on column public.vexforge_asset_files.official is 'Bandera booleana de control. tipo boolean, obligatoria, por defecto true.';
comment on column public.vexforge_asset_files.enabled is 'Bandera booleana de control. tipo boolean, obligatoria, por defecto true.';
comment on column public.vexforge_asset_files.created_at is 'Marca temporal de creacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.vexforge_branch_registry.id is 'Identificador primario de la fila. tipo uuid, clave primaria, obligatoria, por defecto gen_random_uuid().';
comment on column public.vexforge_branch_registry.branch_key is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.vexforge_branch_registry.branch_title is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.vexforge_branch_registry.canonical_domain is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.vexforge_branch_registry.source_chat is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.vexforge_branch_registry.status is 'Estado del ciclo de vida de la fila. tipo text, obligatoria, por defecto ''official''::text.';
comment on column public.vexforge_branch_registry.notes is 'Texto descriptivo mostrado al jugador. tipo text, opcional.';
comment on column public.vexforge_branch_registry.created_at is 'Marca temporal de creacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.vexforge_branch_registry.updated_at is 'Marca temporal de la ultima actualizacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.vexforge_card_fusion_log.id is 'Identificador primario de la fila. tipo uuid, clave primaria, obligatoria, por defecto gen_random_uuid().';
comment on column public.vexforge_card_fusion_log.player_id is 'Jugador propietario de la fila. tipo uuid, referencia a public.players.id, obligatoria.';
comment on column public.vexforge_card_fusion_log.source_card_id is 'Referencia a otra entidad del dominio. tipo uuid, referencia a public.cards.id, obligatoria.';
comment on column public.vexforge_card_fusion_log.target_card_id is 'Referencia a otra entidad del dominio. tipo uuid, referencia a public.cards.id, obligatoria.';
comment on column public.vexforge_card_fusion_log.source_rarity is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.vexforge_card_fusion_log.target_rarity is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.vexforge_card_fusion_log.source_cards_burned is 'Atributo de dominio de la tabla. tipo integer, obligatoria.';
comment on column public.vexforge_card_fusion_log.shards_burned is 'Atributo de dominio de la tabla. tipo integer, obligatoria.';
comment on column public.vexforge_card_fusion_log.vex_ingame_spent is 'Magnitud economica en la unidad definida por el diseno. tipo numeric, obligatoria.';
comment on column public.vexforge_card_fusion_log.source_card_name is 'Atributo de dominio de la tabla. tipo text, opcional.';
comment on column public.vexforge_card_fusion_log.target_card_name is 'Atributo de dominio de la tabla. tipo text, opcional.';
comment on column public.vexforge_card_fusion_log.metadata is 'Datos auxiliares en JSON no consultados por clave. tipo jsonb, obligatoria, por defecto ''{}''::jsonb.';
comment on column public.vexforge_card_fusion_log.created_at is 'Marca temporal de creacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.vexforge_card_fusion_policy.id is 'Identificador primario de la fila. tipo uuid, clave primaria, obligatoria, por defecto gen_random_uuid().';
comment on column public.vexforge_card_fusion_policy.source_rarity is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.vexforge_card_fusion_policy.target_rarity is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.vexforge_card_fusion_policy.required_cards is 'Atributo de dominio de la tabla. tipo integer, obligatoria.';
comment on column public.vexforge_card_fusion_policy.required_shards is 'Atributo de dominio de la tabla. tipo integer, obligatoria, por defecto 0.';
comment on column public.vexforge_card_fusion_policy.vex_ingame_cost is 'Magnitud economica en la unidad definida por el diseno. tipo numeric, obligatoria, por defecto 0.';
comment on column public.vexforge_card_fusion_policy.active is 'Bandera booleana de control. tipo boolean, obligatoria, por defecto true.';
comment on column public.vexforge_card_fusion_policy.notes is 'Texto descriptivo mostrado al jugador. tipo text, opcional.';
comment on column public.vexforge_card_fusion_policy.created_at is 'Marca temporal de creacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.vexforge_card_fusion_policy.updated_at is 'Marca temporal de la ultima actualizacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.vexforge_card_supply_policy.rarity is 'Atributo de dominio de la tabla. tipo text, clave primaria, obligatoria.';
comment on column public.vexforge_card_supply_policy.founder_cards is 'Atributo de dominio de la tabla. tipo integer, obligatoria, por defecto 4.';
comment on column public.vexforge_card_supply_policy.supply_per_card is 'Atributo de dominio de la tabla. tipo integer, obligatoria.';
comment on column public.vexforge_card_supply_policy.total_supply is 'Contador acumulado. tipo integer, obligatoria.';
comment on column public.vexforge_card_supply_policy.marketable is 'Bandera booleana de control. tipo boolean, obligatoria, por defecto true.';
comment on column public.vexforge_card_supply_policy.fusion_enabled is 'Bandera booleana de control. tipo boolean, obligatoria, por defecto true.';
comment on column public.vexforge_card_supply_policy.notes is 'Texto descriptivo mostrado al jugador. tipo text, opcional.';
comment on column public.vexforge_card_supply_policy.active is 'Bandera booleana de control. tipo boolean, obligatoria, por defecto true.';
comment on column public.vexforge_card_supply_policy.updated_at is 'Marca temporal de la ultima actualizacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.vexforge_card_supply_policy.pack_pct is 'Atributo de dominio de la tabla. tipo integer, opcional.';
comment on column public.vexforge_card_supply_policy.mission_pct is 'Atributo de dominio de la tabla. tipo integer, opcional.';
comment on column public.vexforge_card_supply_policy.chest_pct is 'Atributo de dominio de la tabla. tipo integer, opcional.';
comment on column public.vexforge_card_supply_policy.referral_pct is 'Atributo de dominio de la tabla. tipo integer, opcional.';
comment on column public.vexforge_card_supply_policy.max_supply_per_card is 'Atributo de dominio de la tabla. tipo bigint, opcional.';
comment on column public.vexforge_card_supply_policy.initial_mint_per_card is 'Atributo de dominio de la tabla. tipo bigint, opcional.';
comment on column public.vexforge_commercial_policy.policy_key is 'Atributo de dominio de la tabla. tipo text, clave primaria, obligatoria.';
comment on column public.vexforge_commercial_policy.policy_value_numeric is 'Atributo de dominio de la tabla. tipo numeric, opcional.';
comment on column public.vexforge_commercial_policy.policy_value_text is 'Atributo de dominio de la tabla. tipo text, opcional.';
comment on column public.vexforge_commercial_policy.policy_value_json is 'Datos auxiliares en JSON no consultados por clave. tipo jsonb, obligatoria, por defecto ''{}''::jsonb.';
comment on column public.vexforge_commercial_policy.updated_at is 'Marca temporal de la ultima actualizacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.vexforge_economy_policy.policy_key is 'Atributo de dominio de la tabla. tipo text, clave primaria, obligatoria.';
comment on column public.vexforge_economy_policy.policy_value_numeric is 'Atributo de dominio de la tabla. tipo numeric, opcional.';
comment on column public.vexforge_economy_policy.policy_value_text is 'Atributo de dominio de la tabla. tipo text, opcional.';
comment on column public.vexforge_economy_policy.policy_value_json is 'Datos auxiliares en JSON no consultados por clave. tipo jsonb, obligatoria, por defecto ''{}''::jsonb.';
comment on column public.vexforge_economy_policy.updated_at is 'Marca temporal de la ultima actualizacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.vexforge_market_policy.policy_key is 'Atributo de dominio de la tabla. tipo text, clave primaria, obligatoria.';
comment on column public.vexforge_market_policy.policy_value_numeric is 'Atributo de dominio de la tabla. tipo numeric, opcional.';
comment on column public.vexforge_market_policy.policy_value_text is 'Atributo de dominio de la tabla. tipo text, opcional.';
comment on column public.vexforge_market_policy.policy_value_json is 'Datos auxiliares en JSON no consultados por clave. tipo jsonb, obligatoria, por defecto ''{}''::jsonb.';
comment on column public.vexforge_market_policy.updated_at is 'Marca temporal de la ultima actualizacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.vexforge_mission_reward_policy.mission_type is 'Atributo de dominio de la tabla. tipo text, clave primaria, obligatoria.';
comment on column public.vexforge_mission_reward_policy.reward_xp_floor is 'Atributo de dominio de la tabla. tipo bigint, obligatoria, por defecto 0.';
comment on column public.vexforge_mission_reward_policy.reward_vex_ingame_floor is 'Magnitud economica en la unidad definida por el diseno. tipo numeric, obligatoria, por defecto 0.';
comment on column public.vexforge_mission_reward_policy.max_tradeable_per_claim is 'Atributo de dominio de la tabla. tipo numeric, obligatoria, por defecto 0.';
comment on column public.vexforge_mission_reward_policy.elo_required is 'Atributo de dominio de la tabla. tipo integer, obligatoria, por defecto 0.';
comment on column public.vexforge_mission_reward_policy.notes is 'Texto descriptivo mostrado al jugador. tipo text, opcional.';
comment on column public.vexforge_mission_reward_policy.active is 'Bandera booleana de control. tipo boolean, obligatoria, por defecto true.';
comment on column public.vexforge_mission_reward_policy.updated_at is 'Marca temporal de la ultima actualizacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.vexforge_object_action_map.id is 'Identificador primario de la fila. tipo uuid, clave primaria, obligatoria, por defecto gen_random_uuid().';
comment on column public.vexforge_object_action_map.object_type is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.vexforge_object_action_map.object_name is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.vexforge_object_action_map.domain is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.vexforge_object_action_map.action is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.vexforge_object_action_map.priority is 'Valor ordinal o de posicion. tipo integer, obligatoria, por defecto 100.';
comment on column public.vexforge_object_action_map.reason is 'Atributo de dominio de la tabla. tipo text, opcional.';
comment on column public.vexforge_object_action_map.source_table is 'Atributo de dominio de la tabla. tipo text, opcional.';
comment on column public.vexforge_object_action_map.target_table is 'Atributo de dominio de la tabla. tipo text, opcional.';
comment on column public.vexforge_object_action_map.notes is 'Texto descriptivo mostrado al jugador. tipo text, opcional.';
comment on column public.vexforge_object_action_map.created_at is 'Marca temporal de creacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.vexforge_object_action_map.updated_at is 'Marca temporal de la ultima actualizacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.vexforge_official_asset_manifest.id is 'Identificador primario de la fila. tipo uuid, clave primaria, obligatoria, por defecto gen_random_uuid().';
comment on column public.vexforge_official_asset_manifest.asset_pack is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.vexforge_official_asset_manifest.asset_code is 'Codigo estable usado como clave de negocio legible. tipo text, obligatoria.';
comment on column public.vexforge_official_asset_manifest.internal_path is 'Ruta o URL del arte asociado. tipo text, obligatoria.';
comment on column public.vexforge_official_asset_manifest.file_name is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.vexforge_official_asset_manifest.semantic_role is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.vexforge_official_asset_manifest.display_name is 'Nombre visible en la interfaz. tipo text, obligatoria.';
comment on column public.vexforge_official_asset_manifest.source_zip_url is 'Ruta o URL del arte asociado. tipo text, obligatoria.';
comment on column public.vexforge_official_asset_manifest.official is 'Bandera booleana de control. tipo boolean, opcional, por defecto true.';
comment on column public.vexforge_official_asset_manifest.enabled is 'Bandera booleana de control. tipo boolean, opcional, por defecto true.';
comment on column public.vexforge_official_asset_manifest.created_at is 'Marca temporal de creacion de la fila. tipo timestamp with time zone, opcional, por defecto now().';
comment on column public.vexforge_official_asset_manifest.updated_at is 'Marca temporal de la ultima actualizacion de la fila. tipo timestamp with time zone, opcional, por defecto now().';
comment on column public.vexforge_official_documents.id is 'Identificador primario de la fila. tipo uuid, clave primaria, obligatoria, por defecto gen_random_uuid().';
comment on column public.vexforge_official_documents.doc_key is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.vexforge_official_documents.doc_title is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.vexforge_official_documents.doc_category is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.vexforge_official_documents.doc_version is 'Atributo de dominio de la tabla. tipo text, opcional, por defecto ''1.0''::text.';
comment on column public.vexforge_official_documents.status is 'Estado del ciclo de vida de la fila. tipo text, opcional, por defecto ''official''::text.';
comment on column public.vexforge_official_documents.content_markdown is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.vexforge_official_documents.source_type is 'Atributo de dominio de la tabla. tipo text, opcional, por defecto ''chat_blueprint''::text.';
comment on column public.vexforge_official_documents.sort_order is 'Valor ordinal o de posicion. tipo integer, opcional, por defecto 0.';
comment on column public.vexforge_official_documents.created_at is 'Marca temporal de creacion de la fila. tipo timestamp with time zone, opcional, por defecto now().';
comment on column public.vexforge_official_documents.updated_at is 'Marca temporal de la ultima actualizacion de la fila. tipo timestamp with time zone, opcional, por defecto now().';
comment on column public.vexforge_official_module_specs.id is 'Identificador primario de la fila. tipo uuid, clave primaria, obligatoria, por defecto gen_random_uuid().';
comment on column public.vexforge_official_module_specs.module_key is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.vexforge_official_module_specs.module_name is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.vexforge_official_module_specs.domain is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.vexforge_official_module_specs.object_type is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.vexforge_official_module_specs.object_name is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.vexforge_official_module_specs.status is 'Estado del ciclo de vida de la fila. tipo text, obligatoria, por defecto ''draft''::text.';
comment on column public.vexforge_official_module_specs.spec is 'Datos auxiliares en JSON no consultados por clave. tipo jsonb, obligatoria, por defecto ''{}''::jsonb.';
comment on column public.vexforge_official_module_specs.created_at is 'Marca temporal de creacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.vexforge_official_module_specs.updated_at is 'Marca temporal de la ultima actualizacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.vexforge_official_modules.id is 'Identificador primario de la fila. tipo uuid, clave primaria, obligatoria, por defecto gen_random_uuid().';
comment on column public.vexforge_official_modules.module_key is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.vexforge_official_modules.module_title is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.vexforge_official_modules.module_category is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.vexforge_official_modules.module_summary is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.vexforge_official_modules.status is 'Estado del ciclo de vida de la fila. tipo text, opcional, por defecto ''official''::text.';
comment on column public.vexforge_official_modules.sort_order is 'Valor ordinal o de posicion. tipo integer, opcional, por defecto 0.';
comment on column public.vexforge_official_modules.created_at is 'Marca temporal de creacion de la fila. tipo timestamp with time zone, opcional, por defecto now().';
comment on column public.vexforge_official_modules.updated_at is 'Marca temporal de la ultima actualizacion de la fila. tipo timestamp with time zone, opcional, por defecto now().';
comment on column public.vexforge_official_seed_manifest.id is 'Identificador primario de la fila. tipo uuid, clave primaria, obligatoria, por defecto gen_random_uuid().';
comment on column public.vexforge_official_seed_manifest.module_key is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.vexforge_official_seed_manifest.target_table is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.vexforge_official_seed_manifest.record_key is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.vexforge_official_seed_manifest.payload is 'Datos auxiliares en JSON no consultados por clave. tipo jsonb, obligatoria, por defecto ''{}''::jsonb.';
comment on column public.vexforge_official_seed_manifest.source_system is 'Atributo de dominio de la tabla. tipo text, obligatoria, por defecto ''official_project''::text.';
comment on column public.vexforge_official_seed_manifest.status is 'Estado del ciclo de vida de la fila. tipo text, obligatoria, por defecto ''queued''::text.';
comment on column public.vexforge_official_seed_manifest.notes is 'Texto descriptivo mostrado al jugador. tipo text, opcional.';
comment on column public.vexforge_official_seed_manifest.created_at is 'Marca temporal de creacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.vexforge_official_seed_manifest.updated_at is 'Marca temporal de la ultima actualizacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.vexforge_project_deposits.id is 'Identificador primario de la fila. tipo uuid, clave primaria, obligatoria, por defecto gen_random_uuid().';
comment on column public.vexforge_project_deposits.source is 'Atributo de dominio de la tabla. tipo text, obligatoria, por defecto ''external_payment''::text.';
comment on column public.vexforge_project_deposits.chain is 'Atributo de dominio de la tabla. tipo text, obligatoria, por defecto ''BSC''::text.';
comment on column public.vexforge_project_deposits.token_symbol is 'Atributo de dominio de la tabla. tipo text, obligatoria, por defecto ''USDT''::text.';
comment on column public.vexforge_project_deposits.token_standard is 'Atributo de dominio de la tabla. tipo text, obligatoria, por defecto ''BEP20''::text.';
comment on column public.vexforge_project_deposits.treasury_wallet_address is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.vexforge_project_deposits.payer_wallet_address is 'Atributo de dominio de la tabla. tipo text, opcional.';
comment on column public.vexforge_project_deposits.player_id is 'Jugador propietario de la fila. tipo uuid, referencia a public.players.id, opcional.';
comment on column public.vexforge_project_deposits.amount_usdt is 'Magnitud economica en la unidad definida por el diseno. tipo numeric, obligatoria.';
comment on column public.vexforge_project_deposits.tx_hash is 'Atributo de dominio de la tabla. tipo text, opcional.';
comment on column public.vexforge_project_deposits.reference_type is 'Atributo de dominio de la tabla. tipo text, opcional.';
comment on column public.vexforge_project_deposits.reference_id is 'Atributo de dominio de la tabla. tipo text, opcional.';
comment on column public.vexforge_project_deposits.status is 'Estado del ciclo de vida de la fila. tipo text, obligatoria, por defecto ''pending_confirmation''::text.';
comment on column public.vexforge_project_deposits.metadata is 'Datos auxiliares en JSON no consultados por clave. tipo jsonb, obligatoria, por defecto ''{}''::jsonb.';
comment on column public.vexforge_project_deposits.created_at is 'Marca temporal de creacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.vexforge_project_deposits.updated_at is 'Marca temporal de la ultima actualizacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.vexforge_project_deposits.vex_credited is 'Magnitud economica en la unidad definida por el diseno. tipo numeric, opcional, por defecto 0.';
comment on column public.vexforge_project_deposits.approved_at is 'Marca temporal del evento indicado por el nombre. tipo timestamp with time zone, opcional.';
comment on column public.vexforge_project_deposits.notes is 'Texto descriptivo mostrado al jugador. tipo text, opcional.';
comment on column public.vexforge_shop_orders.id is 'Identificador primario de la fila. tipo uuid, clave primaria, obligatoria, por defecto gen_random_uuid().';
comment on column public.vexforge_shop_orders.player_id is 'Jugador propietario de la fila. tipo uuid, referencia a public.players.id, obligatoria.';
comment on column public.vexforge_shop_orders.item_key is 'Referencia a otra entidad del dominio. tipo text, referencia a public.vexforge_shop_catalog.item_key, obligatoria.';
comment on column public.vexforge_shop_orders.price_usdt is 'Magnitud economica en la unidad definida por el diseno. tipo numeric, obligatoria.';
comment on column public.vexforge_shop_orders.status is 'Estado del ciclo de vida de la fila. tipo text, obligatoria, por defecto ''pending_payment''::text.';
comment on column public.vexforge_shop_orders.fulfillment_status is 'Estado del ciclo de vida de la fila. tipo text, obligatoria, por defecto ''pending''::text.';
comment on column public.vexforge_shop_orders.client_reference is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.vexforge_shop_orders.payment_reference is 'Atributo de dominio de la tabla. tipo text, opcional.';
comment on column public.vexforge_shop_orders.tx_hash is 'Atributo de dominio de la tabla. tipo text, opcional.';
comment on column public.vexforge_shop_orders.treasury_wallet_address is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.vexforge_shop_orders.payer_wallet_address is 'Atributo de dominio de la tabla. tipo text, opcional.';
comment on column public.vexforge_shop_orders.metadata is 'Datos auxiliares en JSON no consultados por clave. tipo jsonb, obligatoria, por defecto ''{}''::jsonb.';
comment on column public.vexforge_shop_orders.created_at is 'Marca temporal de creacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.vexforge_shop_orders.updated_at is 'Marca temporal de la ultima actualizacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.vexforge_shop_orders.approved_at is 'Marca temporal del evento indicado por el nombre. tipo timestamp with time zone, opcional.';
comment on column public.vexforge_shop_orders.fulfilled_at is 'Marca temporal del evento indicado por el nombre. tipo timestamp with time zone, opcional.';
comment on column public.vexforge_shop_orders.notes is 'Texto descriptivo mostrado al jugador. tipo text, opcional.';
