-- VE-DOC-6-RESIDUAL-SUPPORT-COLUMN-COMMENTS
-- Cierra la cobertura documental de columnas en las tablas de soporte interno `vexforge_*`
-- restantes (sin consumidor ni dependencia detectada en funciones o vistas).
-- Solo metadatos: sin cambios de esquema, datos, RLS, grants, RPCs, economia autoritativa, Storage ni arte.

comment on column public.vexforge_asset_manifest.id is 'Identificador primario de la fila. tipo uuid, clave primaria, obligatoria, por defecto gen_random_uuid().';
comment on column public.vexforge_asset_manifest.asset_code is 'Codigo estable usado como clave de negocio legible. tipo text, obligatoria.';
comment on column public.vexforge_asset_manifest.asset_pack is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.vexforge_asset_manifest.internal_path is 'Ruta o URL del recurso asociado. tipo text, opcional.';
comment on column public.vexforge_asset_manifest.asset_type is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.vexforge_asset_manifest.display_name is 'Nombre visible en la interfaz. tipo text, opcional.';
comment on column public.vexforge_asset_manifest.official is 'Bandera booleana de control. tipo boolean, opcional, por defecto true.';
comment on column public.vexforge_asset_manifest.enabled is 'Bandera booleana de control. tipo boolean, opcional, por defecto true.';
comment on column public.vexforge_asset_manifest.created_at is 'Marca temporal de creacion de la fila. tipo timestamp with time zone, opcional, por defecto now().';
comment on column public.vexforge_asset_packs.id is 'Identificador primario de la fila. tipo uuid, clave primaria, obligatoria, por defecto gen_random_uuid().';
comment on column public.vexforge_asset_packs.asset_key is 'Codigo estable usado como clave de negocio legible. tipo text, obligatoria.';
comment on column public.vexforge_asset_packs.display_name is 'Nombre visible en la interfaz. tipo text, obligatoria.';
comment on column public.vexforge_asset_packs.category is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.vexforge_asset_packs.storage_url is 'Ruta o URL del recurso asociado. tipo text, obligatoria.';
comment on column public.vexforge_asset_packs.contains_multiple_assets is 'Bandera booleana de control. tipo boolean, opcional, por defecto true.';
comment on column public.vexforge_asset_packs.official is 'Bandera booleana de control. tipo boolean, opcional, por defecto true.';
comment on column public.vexforge_asset_packs.enabled is 'Bandera booleana de control. tipo boolean, opcional, por defecto true.';
comment on column public.vexforge_asset_packs.version is 'Valor numerico del dominio. tipo integer, opcional, por defecto 1.';
comment on column public.vexforge_asset_packs.notes is 'Texto descriptivo asociado a la fila. tipo text, opcional.';
comment on column public.vexforge_asset_packs.created_at is 'Marca temporal de creacion de la fila. tipo timestamp with time zone, opcional, por defecto now().';
comment on column public.vexforge_chat_branch_registry.id is 'Identificador primario de la fila. tipo uuid, clave primaria, obligatoria, por defecto gen_random_uuid().';
comment on column public.vexforge_chat_branch_registry.chat_key is 'Codigo estable usado como clave de negocio legible. tipo text, obligatoria.';
comment on column public.vexforge_chat_branch_registry.branch_name is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.vexforge_chat_branch_registry.branch_order is 'Valor numerico del dominio. tipo integer, obligatoria.';
comment on column public.vexforge_chat_branch_registry.status is 'Estado del ciclo de vida de la fila. tipo text, obligatoria, por defecto ''official''::text.';
comment on column public.vexforge_chat_branch_registry.official_payload is 'Estructura JSON con datos auxiliares de la fila. tipo jsonb, obligatoria, por defecto ''{}''::jsonb.';
comment on column public.vexforge_chat_branch_registry.created_at is 'Marca temporal de creacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.vexforge_chat_branch_registry.updated_at is 'Marca temporal de la ultima actualizacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.vexforge_core_registry.id is 'Identificador primario de la fila. tipo uuid, clave primaria, obligatoria, por defecto gen_random_uuid().';
comment on column public.vexforge_core_registry.table_name is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.vexforge_core_registry.domain is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.vexforge_core_registry.runtime_role is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.vexforge_core_registry.canonical is 'Bandera booleana de control. tipo boolean, obligatoria, por defecto true.';
comment on column public.vexforge_core_registry.notes is 'Texto descriptivo asociado a la fila. tipo text, opcional.';
comment on column public.vexforge_core_registry.created_at is 'Marca temporal de creacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.vexforge_core_registry.updated_at is 'Marca temporal de la ultima actualizacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.vexforge_deprecation_registry.id is 'Identificador primario de la fila. tipo uuid, clave primaria, obligatoria, por defecto gen_random_uuid().';
comment on column public.vexforge_deprecation_registry.table_name is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.vexforge_deprecation_registry.domain is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.vexforge_deprecation_registry.replacement_table is 'Atributo de dominio de la tabla. tipo text, opcional.';
comment on column public.vexforge_deprecation_registry.cleanup_action is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.vexforge_deprecation_registry.notes is 'Texto descriptivo asociado a la fila. tipo text, opcional.';
comment on column public.vexforge_deprecation_registry.created_at is 'Marca temporal de creacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.vexforge_deprecation_registry.updated_at is 'Marca temporal de la ultima actualizacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.vexforge_final_gap_report.id is 'Identificador primario de la fila. tipo uuid, clave primaria, obligatoria, por defecto gen_random_uuid().';
comment on column public.vexforge_final_gap_report.table_name is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.vexforge_final_gap_report.table_type is 'Atributo de dominio de la tabla. tipo text, opcional.';
comment on column public.vexforge_final_gap_report.gap_reason is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.vexforge_final_gap_report.created_at is 'Marca temporal de creacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.vexforge_final_handoff_status.id is 'Identificador primario de la fila. tipo uuid, clave primaria, obligatoria, por defecto gen_random_uuid().';
comment on column public.vexforge_final_handoff_status.freeze_key is 'Codigo estable usado como clave de negocio legible. tipo text, obligatoria.';
comment on column public.vexforge_final_handoff_status.status is 'Estado del ciclo de vida de la fila. tipo text, obligatoria.';
comment on column public.vexforge_final_handoff_status.ready_for_replit is 'Bandera booleana de control. tipo boolean, obligatoria, por defecto false.';
comment on column public.vexforge_final_handoff_status.notes is 'Texto descriptivo asociado a la fila. tipo text, opcional.';
comment on column public.vexforge_final_handoff_status.total_tables is 'Valor numerico del dominio. tipo integer, obligatoria, por defecto 0.';
comment on column public.vexforge_final_handoff_status.canonical_tables is 'Valor numerico del dominio. tipo integer, obligatoria, por defecto 0.';
comment on column public.vexforge_final_handoff_status.bridge_tables is 'Valor numerico del dominio. tipo integer, obligatoria, por defecto 0.';
comment on column public.vexforge_final_handoff_status.control_plane_tables is 'Valor numerico del dominio. tipo integer, obligatoria, por defecto 0.';
comment on column public.vexforge_final_handoff_status.memory_tables is 'Valor numerico del dominio. tipo integer, obligatoria, por defecto 0.';
comment on column public.vexforge_final_handoff_status.support_tables is 'Valor numerico del dominio. tipo integer, obligatoria, por defecto 0.';
comment on column public.vexforge_final_handoff_status.telegram_tables is 'Valor numerico del dominio. tipo integer, obligatoria, por defecto 0.';
comment on column public.vexforge_final_handoff_status.legacy_tables is 'Valor numerico del dominio. tipo integer, obligatoria, por defecto 0.';
comment on column public.vexforge_final_handoff_status.web_tables is 'Valor numerico del dominio. tipo integer, obligatoria, por defecto 0.';
comment on column public.vexforge_final_handoff_status.created_at is 'Marca temporal de creacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.vexforge_final_handoff_status.updated_at is 'Marca temporal de la ultima actualizacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.vexforge_frontend_source_files.id is 'Identificador primario de la fila. tipo uuid, clave primaria, obligatoria, por defecto gen_random_uuid().';
comment on column public.vexforge_frontend_source_files.file_path is 'Ruta o URL del recurso asociado. tipo text, obligatoria.';
comment on column public.vexforge_frontend_source_files.content is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.vexforge_frontend_source_files.file_type is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.vexforge_frontend_source_files.domain is 'Atributo de dominio de la tabla. tipo text, opcional.';
comment on column public.vexforge_frontend_source_files.description is 'Texto descriptivo asociado a la fila. tipo text, opcional.';
comment on column public.vexforge_frontend_source_files.project_version is 'Atributo de dominio de la tabla. tipo text, obligatoria, por defecto ''v1''::text.';
comment on column public.vexforge_frontend_source_files.created_at is 'Marca temporal de creacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.vexforge_frontend_source_files.updated_at is 'Marca temporal de la ultima actualizacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.vexforge_function_consolidation_registry.id is 'Identificador primario de la fila. tipo uuid, clave primaria, obligatoria, por defecto gen_random_uuid().';
comment on column public.vexforge_function_consolidation_registry.phase is 'Atributo de dominio de la tabla. tipo text, obligatoria, por defecto ''FASE_2_CONSOLIDACION_FUNCIONES_CRITICAS''::text.';
comment on column public.vexforge_function_consolidation_registry.critical_path is 'Ruta o URL del recurso asociado. tipo text, obligatoria.';
comment on column public.vexforge_function_consolidation_registry.original_name is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.vexforge_function_consolidation_registry.original_args is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.vexforge_function_consolidation_registry.original_oid is 'Valor numerico del dominio. tipo integer, obligatoria.';
comment on column public.vexforge_function_consolidation_registry.action is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.vexforge_function_consolidation_registry.new_name is 'Atributo de dominio de la tabla. tipo text, opcional.';
comment on column public.vexforge_function_consolidation_registry.official_counterpart is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.vexforge_function_consolidation_registry.reason is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.vexforge_function_consolidation_registry.original_definition is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.vexforge_function_consolidation_registry.created_at is 'Marca temporal de creacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.vexforge_icon_legacy.id is 'Identificador primario de la fila. tipo uuid, clave primaria, obligatoria, por defecto gen_random_uuid().';
comment on column public.vexforge_icon_legacy.source_table is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.vexforge_icon_legacy.source_column is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.vexforge_icon_legacy.row_key is 'Codigo estable usado como clave de negocio legible. tipo text, obligatoria.';
comment on column public.vexforge_icon_legacy.legacy_value is 'Atributo de dominio de la tabla. tipo text, opcional.';
comment on column public.vexforge_icon_legacy.canonical_value is 'Atributo de dominio de la tabla. tipo text, opcional.';
comment on column public.vexforge_icon_legacy.recorded_at is 'Marca temporal registrada por el sistema. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.vexforge_implementation_manifest.id is 'Identificador primario de la fila. tipo uuid, clave primaria, obligatoria, por defecto gen_random_uuid().';
comment on column public.vexforge_implementation_manifest.manifest_key is 'Codigo estable usado como clave de negocio legible. tipo text, obligatoria.';
comment on column public.vexforge_implementation_manifest.manifest_name is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.vexforge_implementation_manifest.version is 'Valor numerico del dominio. tipo integer, obligatoria, por defecto 1.';
comment on column public.vexforge_implementation_manifest.status is 'Estado del ciclo de vida de la fila. tipo text, obligatoria, por defecto ''draft''::text.';
comment on column public.vexforge_implementation_manifest.description is 'Texto descriptivo asociado a la fila. tipo text, opcional.';
comment on column public.vexforge_implementation_manifest.created_at is 'Marca temporal de creacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.vexforge_implementation_manifest.updated_at is 'Marca temporal de la ultima actualizacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.vexforge_nft_metadata.id is 'Identificador primario de la fila. tipo uuid, clave primaria, obligatoria, por defecto gen_random_uuid().';
comment on column public.vexforge_nft_metadata.card_id is 'Referencia a otra entidad del dominio. tipo uuid, referencia a public.cards.id, obligatoria.';
comment on column public.vexforge_nft_metadata.contract_id is 'Referencia a otra entidad del dominio. tipo uuid, referencia a public.vexforge_nft_contracts.id, opcional.';
comment on column public.vexforge_nft_metadata.token_id is 'Valor numerico del dominio. tipo integer, opcional.';
comment on column public.vexforge_nft_metadata.metadata_json is 'Estructura JSON con datos auxiliares de la fila. tipo jsonb, obligatoria, por defecto ''{}''::jsonb.';
comment on column public.vexforge_nft_metadata.image_url is 'Ruta o URL del recurso asociado. tipo text, opcional.';
comment on column public.vexforge_nft_metadata.created_at is 'Marca temporal de creacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.vexforge_official_seed_log.id is 'Identificador primario de la fila. tipo uuid, clave primaria, obligatoria, por defecto gen_random_uuid().';
comment on column public.vexforge_official_seed_log.manifest_id is 'Referencia a otra entidad del dominio. tipo uuid, referencia a public.vexforge_official_seed_manifest.id, opcional.';
comment on column public.vexforge_official_seed_log.target_table is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.vexforge_official_seed_log.record_key is 'Codigo estable usado como clave de negocio legible. tipo text, obligatoria.';
comment on column public.vexforge_official_seed_log.action is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.vexforge_official_seed_log.message is 'Atributo de dominio de la tabla. tipo text, opcional.';
comment on column public.vexforge_official_seed_log.created_at is 'Marca temporal de creacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.vexforge_pack_contents.id is 'Identificador primario de la fila. tipo uuid, clave primaria, obligatoria, por defecto gen_random_uuid().';
comment on column public.vexforge_pack_contents.pack_key is 'Referencia a otra entidad del dominio. tipo text, referencia a public.vexforge_pack_catalog.pack_key, obligatoria.';
comment on column public.vexforge_pack_contents.slot_index is 'Valor numerico del dominio. tipo integer, obligatoria.';
comment on column public.vexforge_pack_contents.item_type is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.vexforge_pack_contents.item_key is 'Codigo estable usado como clave de negocio legible. tipo text, opcional.';
comment on column public.vexforge_pack_contents.quantity_min is 'Valor numerico del dominio. tipo integer, obligatoria, por defecto 1.';
comment on column public.vexforge_pack_contents.quantity_max is 'Valor numerico del dominio. tipo integer, obligatoria, por defecto 1.';
comment on column public.vexforge_pack_contents.chance_pct is 'Valor numerico del dominio. tipo numeric, obligatoria, por defecto 100.';
comment on column public.vexforge_pack_contents.metadata is 'Estructura JSON con datos auxiliares de la fila. tipo jsonb, obligatoria, por defecto ''{}''::jsonb.';
comment on column public.vexforge_pack_contents.active is 'Bandera booleana de control. tipo boolean, obligatoria, por defecto true.';
comment on column public.vexforge_pack_contents.created_at is 'Marca temporal de creacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.vexforge_pack_contents.updated_at is 'Marca temporal de la ultima actualizacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.vexforge_project_audit.id is 'Identificador primario de la fila. tipo uuid, clave primaria, obligatoria, por defecto gen_random_uuid().';
comment on column public.vexforge_project_audit.entity_type is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.vexforge_project_audit.entity_key is 'Codigo estable usado como clave de negocio legible. tipo text, opcional.';
comment on column public.vexforge_project_audit.action is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.vexforge_project_audit.payload is 'Estructura JSON con datos auxiliares de la fila. tipo jsonb, obligatoria, por defecto ''{}''::jsonb.';
comment on column public.vexforge_project_audit.created_at is 'Marca temporal de creacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.vexforge_project_chat_registry.id is 'Identificador primario de la fila. tipo uuid, clave primaria, obligatoria, por defecto gen_random_uuid().';
comment on column public.vexforge_project_chat_registry.chat_number is 'Valor numerico del dominio. tipo integer, obligatoria.';
comment on column public.vexforge_project_chat_registry.chat_key is 'Codigo estable usado como clave de negocio legible. tipo text, obligatoria.';
comment on column public.vexforge_project_chat_registry.title is 'Nombre visible en la interfaz. tipo text, opcional.';
comment on column public.vexforge_project_chat_registry.summary is 'Texto descriptivo asociado a la fila. tipo text, opcional.';
comment on column public.vexforge_project_chat_registry.status is 'Estado del ciclo de vida de la fila. tipo text, obligatoria, por defecto ''official''::text.';
comment on column public.vexforge_project_chat_registry.official_payload is 'Estructura JSON con datos auxiliares de la fila. tipo jsonb, obligatoria, por defecto ''{}''::jsonb.';
comment on column public.vexforge_project_chat_registry.created_at is 'Marca temporal de creacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.vexforge_project_chat_registry.updated_at is 'Marca temporal de la ultima actualizacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.vexforge_project_decisions.id is 'Identificador primario de la fila. tipo uuid, clave primaria, obligatoria, por defecto gen_random_uuid().';
comment on column public.vexforge_project_decisions.decision_key is 'Codigo estable usado como clave de negocio legible. tipo text, obligatoria.';
comment on column public.vexforge_project_decisions.category is 'Atributo de dominio de la tabla. tipo text, opcional.';
comment on column public.vexforge_project_decisions.title is 'Nombre visible en la interfaz. tipo text, opcional.';
comment on column public.vexforge_project_decisions.description is 'Texto descriptivo asociado a la fila. tipo text, opcional.';
comment on column public.vexforge_project_decisions.adopted_in_chat is 'Valor numerico del dominio. tipo integer, opcional.';
comment on column public.vexforge_project_decisions.status is 'Estado del ciclo de vida de la fila. tipo text, obligatoria, por defecto ''official''::text.';
comment on column public.vexforge_project_decisions.official_payload is 'Estructura JSON con datos auxiliares de la fila. tipo jsonb, obligatoria, por defecto ''{}''::jsonb.';
comment on column public.vexforge_project_decisions.created_at is 'Marca temporal de creacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.vexforge_project_decisions.updated_at is 'Marca temporal de la ultima actualizacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.vexforge_project_documents.id is 'Identificador primario de la fila. tipo uuid, clave primaria, obligatoria, por defecto gen_random_uuid().';
comment on column public.vexforge_project_documents.document_key is 'Codigo estable usado como clave de negocio legible. tipo text, obligatoria.';
comment on column public.vexforge_project_documents.category is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.vexforge_project_documents.title is 'Nombre visible en la interfaz. tipo text, obligatoria.';
comment on column public.vexforge_project_documents.description is 'Texto descriptivo asociado a la fila. tipo text, opcional.';
comment on column public.vexforge_project_documents.version is 'Atributo de dominio de la tabla. tipo text, opcional.';
comment on column public.vexforge_project_documents.status is 'Estado del ciclo de vida de la fila. tipo text, obligatoria, por defecto ''official''::text.';
comment on column public.vexforge_project_documents.official_payload is 'Estructura JSON con datos auxiliares de la fila. tipo jsonb, obligatoria, por defecto ''{}''::jsonb.';
comment on column public.vexforge_project_documents.created_at is 'Marca temporal de creacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.vexforge_project_documents.updated_at is 'Marca temporal de la ultima actualizacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.vexforge_project_memory.id is 'Identificador primario de la fila. tipo uuid, clave primaria, obligatoria, por defecto gen_random_uuid().';
comment on column public.vexforge_project_memory.memory_key is 'Codigo estable usado como clave de negocio legible. tipo text, obligatoria.';
comment on column public.vexforge_project_memory.project_name is 'Atributo de dominio de la tabla. tipo text, obligatoria, por defecto ''VEXFORGE''::text.';
comment on column public.vexforge_project_memory.current_chat is 'Valor numerico del dominio. tipo integer, obligatoria.';
comment on column public.vexforge_project_memory.current_revision is 'Valor numerico del dominio. tipo integer, obligatoria, por defecto 1.';
comment on column public.vexforge_project_memory.status is 'Estado del ciclo de vida de la fila. tipo text, obligatoria, por defecto ''official''::text.';
comment on column public.vexforge_project_memory.official_payload is 'Estructura JSON con datos auxiliares de la fila. tipo jsonb, obligatoria, por defecto ''{}''::jsonb.';
comment on column public.vexforge_project_memory.checksum is 'Atributo de dominio de la tabla. tipo text, opcional.';
comment on column public.vexforge_project_memory.created_at is 'Marca temporal de creacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.vexforge_project_memory.updated_at is 'Marca temporal de la ultima actualizacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.vexforge_project_modules.id is 'Identificador primario de la fila. tipo uuid, clave primaria, obligatoria, por defecto gen_random_uuid().';
comment on column public.vexforge_project_modules.module_key is 'Codigo estable usado como clave de negocio legible. tipo text, obligatoria.';
comment on column public.vexforge_project_modules.module_name is 'Atributo de dominio de la tabla. tipo text, opcional.';
comment on column public.vexforge_project_modules.category is 'Atributo de dominio de la tabla. tipo text, opcional.';
comment on column public.vexforge_project_modules.description is 'Texto descriptivo asociado a la fila. tipo text, opcional.';
comment on column public.vexforge_project_modules.status is 'Estado del ciclo de vida de la fila. tipo text, opcional, por defecto ''official''::text.';
comment on column public.vexforge_project_modules.official_payload is 'Estructura JSON con datos auxiliares de la fila. tipo jsonb, obligatoria, por defecto ''{}''::jsonb.';
comment on column public.vexforge_project_modules.created_at is 'Marca temporal de creacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.vexforge_project_modules.updated_at is 'Marca temporal de la ultima actualizacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.vexforge_project_versions.id is 'Identificador primario de la fila. tipo uuid, clave primaria, obligatoria, por defecto gen_random_uuid().';
comment on column public.vexforge_project_versions.version_key is 'Codigo estable usado como clave de negocio legible. tipo text, obligatoria.';
comment on column public.vexforge_project_versions.chat_number is 'Valor numerico del dominio. tipo integer, obligatoria.';
comment on column public.vexforge_project_versions.title is 'Nombre visible en la interfaz. tipo text, opcional.';
comment on column public.vexforge_project_versions.description is 'Texto descriptivo asociado a la fila. tipo text, opcional.';
comment on column public.vexforge_project_versions.official_payload is 'Estructura JSON con datos auxiliares de la fila. tipo jsonb, obligatoria, por defecto ''{}''::jsonb.';
comment on column public.vexforge_project_versions.created_at is 'Marca temporal de creacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.vexforge_schema_audit.id is 'Identificador primario de la fila. tipo uuid, clave primaria, obligatoria, por defecto gen_random_uuid().';
comment on column public.vexforge_schema_audit.table_name is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.vexforge_schema_audit.domain is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.vexforge_schema_audit.canonical is 'Bandera booleana de control. tipo boolean, opcional, por defecto false.';
comment on column public.vexforge_schema_audit.replacement_table is 'Atributo de dominio de la tabla. tipo text, opcional.';
comment on column public.vexforge_schema_audit.status is 'Estado del ciclo de vida de la fila. tipo text, opcional.';
comment on column public.vexforge_schema_audit.notes is 'Texto descriptivo asociado a la fila. tipo text, opcional.';
comment on column public.vexforge_schema_audit.created_at is 'Marca temporal de creacion de la fila. tipo timestamp with time zone, opcional, por defecto now().';
comment on column public.vexforge_schema_freeze_status.id is 'Identificador primario de la fila. tipo uuid, clave primaria, obligatoria, por defecto gen_random_uuid().';
comment on column public.vexforge_schema_freeze_status.freeze_key is 'Codigo estable usado como clave de negocio legible. tipo text, obligatoria.';
comment on column public.vexforge_schema_freeze_status.status is 'Estado del ciclo de vida de la fila. tipo text, obligatoria.';
comment on column public.vexforge_schema_freeze_status.ready_for_replit is 'Bandera booleana de control. tipo boolean, obligatoria, por defecto false.';
comment on column public.vexforge_schema_freeze_status.total_canonical_tables is 'Valor numerico del dominio. tipo integer, obligatoria, por defecto 0.';
comment on column public.vexforge_schema_freeze_status.total_bridge_tables is 'Valor numerico del dominio. tipo integer, obligatoria, por defecto 0.';
comment on column public.vexforge_schema_freeze_status.total_control_plane_tables is 'Valor numerico del dominio. tipo integer, obligatoria, por defecto 0.';
comment on column public.vexforge_schema_freeze_status.total_memory_tables is 'Valor numerico del dominio. tipo integer, obligatoria, por defecto 0.';
comment on column public.vexforge_schema_freeze_status.total_support_tables is 'Valor numerico del dominio. tipo integer, obligatoria, por defecto 0.';
comment on column public.vexforge_schema_freeze_status.total_telegram_tables is 'Valor numerico del dominio. tipo integer, obligatoria, por defecto 0.';
comment on column public.vexforge_schema_freeze_status.total_legacy_tables is 'Valor numerico del dominio. tipo integer, obligatoria, por defecto 0.';
comment on column public.vexforge_schema_freeze_status.total_web_tables is 'Valor numerico del dominio. tipo integer, obligatoria, por defecto 0.';
comment on column public.vexforge_schema_freeze_status.gap_tables is 'Valor numerico del dominio. tipo integer, obligatoria, por defecto 0.';
comment on column public.vexforge_schema_freeze_status.notes is 'Texto descriptivo asociado a la fila. tipo text, opcional.';
comment on column public.vexforge_schema_freeze_status.created_at is 'Marca temporal de creacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.vexforge_schema_freeze_status.updated_at is 'Marca temporal de la ultima actualizacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.vexforge_support_registry.id is 'Identificador primario de la fila. tipo uuid, clave primaria, obligatoria, por defecto gen_random_uuid().';
comment on column public.vexforge_support_registry.table_name is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.vexforge_support_registry.domain is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.vexforge_support_registry.support_role is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.vexforge_support_registry.canonical is 'Bandera booleana de control. tipo boolean, obligatoria, por defecto true.';
comment on column public.vexforge_support_registry.notes is 'Texto descriptivo asociado a la fila. tipo text, opcional.';
comment on column public.vexforge_support_registry.created_at is 'Marca temporal de creacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.vexforge_support_registry.updated_at is 'Marca temporal de la ultima actualizacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.vexforge_surface_registry.id is 'Identificador primario de la fila. tipo uuid, clave primaria, obligatoria, por defecto gen_random_uuid().';
comment on column public.vexforge_surface_registry.table_name is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.vexforge_surface_registry.domain is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.vexforge_surface_registry.surface_role is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.vexforge_surface_registry.canonical is 'Bandera booleana de control. tipo boolean, obligatoria, por defecto true.';
comment on column public.vexforge_surface_registry.replacement_table is 'Atributo de dominio de la tabla. tipo text, opcional.';
comment on column public.vexforge_surface_registry.notes is 'Texto descriptivo asociado a la fila. tipo text, opcional.';
comment on column public.vexforge_surface_registry.created_at is 'Marca temporal de creacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.vexforge_surface_registry.updated_at is 'Marca temporal de la ultima actualizacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.vexforge_system_config.config_key is 'Codigo estable usado como clave de negocio legible. tipo text, clave primaria, obligatoria.';
comment on column public.vexforge_system_config.config_value is 'Estructura JSON con datos auxiliares de la fila. tipo jsonb, obligatoria.';
comment on column public.vexforge_system_config.description is 'Texto descriptivo asociado a la fila. tipo text, opcional.';
comment on column public.vexforge_system_config.updated_at is 'Marca temporal de la ultima actualizacion de la fila. tipo timestamp with time zone, opcional, por defecto now().';
comment on column public.vexforge_web_registry.id is 'Identificador primario de la fila. tipo uuid, clave primaria, obligatoria, por defecto gen_random_uuid().';
comment on column public.vexforge_web_registry.table_name is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.vexforge_web_registry.domain is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.vexforge_web_registry.web_role is 'Atributo de dominio de la tabla. tipo text, obligatoria.';
comment on column public.vexforge_web_registry.canonical is 'Bandera booleana de control. tipo boolean, obligatoria, por defecto true.';
comment on column public.vexforge_web_registry.notes is 'Texto descriptivo asociado a la fila. tipo text, opcional.';
comment on column public.vexforge_web_registry.created_at is 'Marca temporal de creacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
comment on column public.vexforge_web_registry.updated_at is 'Marca temporal de la ultima actualizacion de la fila. tipo timestamp with time zone, obligatoria, por defecto now().';
